package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"time"

	"github.com/obcode/tallox.go/graph/model"
	"github.com/obcode/tallox.go/internal/policy"
	"github.com/obcode/tallox.go/internal/principal"
)

// CreatePerson is the resolver for the createPerson field.
func (r *mutationResolver) CreatePerson(ctx context.Context, mail string, name *string) (*model.Person, error) {
	person, err := r.People.Create(ctx, principal.From(ctx), mail, deref(name))
	if err != nil {
		return nil, peopleFacing(err)
	}
	return personModel(*person), nil
}

// RenamePerson is the resolver for the renamePerson field.
func (r *mutationResolver) RenamePerson(ctx context.Context, id string, name string) (*model.Person, error) {
	personID, err := parseID(id)
	if err != nil {
		return nil, err
	}
	person, err := r.People.Rename(ctx, principal.From(ctx), personID, name)
	if err != nil {
		return nil, peopleFacing(err)
	}
	return personModel(*person), nil
}

// SetPersonRoles is the resolver for the setPersonRoles field.
func (r *mutationResolver) SetPersonRoles(ctx context.Context, id string, roles []policy.Role, expiresAt *time.Time) (*model.Person, error) {
	personID, err := parseID(id)
	if err != nil {
		return nil, err
	}

	var expiry time.Time
	if expiresAt != nil {
		expiry = *expiresAt
	}

	person, err := r.People.SetRoles(ctx, principal.From(ctx), personID, roles, expiry)
	if err != nil {
		return nil, peopleFacing(err)
	}
	return personModel(*person), nil
}

// SetPersonActive is the resolver for the setPersonActive field.
func (r *mutationResolver) SetPersonActive(ctx context.Context, id string, active bool) (*model.Person, error) {
	personID, err := parseID(id)
	if err != nil {
		return nil, err
	}
	person, err := r.People.SetActive(ctx, principal.From(ctx), personID, active)
	if err != nil {
		return nil, peopleFacing(err)
	}
	return personModel(*person), nil
}

// SetPersonProgrammes is the resolver for the setPersonProgrammes field.
func (r *mutationResolver) SetPersonProgrammes(ctx context.Context, id string, programmes []string) (*model.Person, error) {
	personID, err := parseID(id)
	if err != nil {
		return nil, err
	}
	person, err := r.People.SetProgrammes(ctx, principal.From(ctx), personID, programmes)
	if err != nil {
		return nil, peopleFacing(err)
	}
	return personModel(*person), nil
}

// People is the resolver for the people field.
func (r *queryResolver) People(ctx context.Context, search *string, includeInactive *bool) ([]*model.Person, error) {
	people, err := r.Resolver.People.List(ctx, principal.From(ctx), deref(search), deref(includeInactive))
	if err != nil {
		return nil, peopleFacing(err)
	}
	return personModels(people), nil
}

// Person is the resolver for the person field.
//
// A person who does not exist is null rather than an error: "there is nobody with that id" is
// a state an administration screen renders, not an exception it catches. A caller who is not
// allowed to ask still gets the refusal — the difference between "not found" and "not
// allowed" is one an administrator needs.
func (r *queryResolver) Person(ctx context.Context, id string) (*model.Person, error) {
	personID, err := parseID(id)
	if err != nil {
		return nil, err
	}
	person, err := r.Resolver.People.Get(ctx, principal.From(ctx), personID)
	if err != nil {
		if isNotFound(err) {
			return nil, nil
		}
		return nil, peopleFacing(err)
	}
	return personModel(*person), nil
}

// RoleGrants is the resolver for the roleGrants field.
func (r *queryResolver) RoleGrants(ctx context.Context, personID string) ([]*model.RoleGrant, error) {
	id, err := parseID(personID)
	if err != nil {
		return nil, err
	}
	actor := principal.From(ctx)
	grants, err := r.Resolver.People.Grants(ctx, actor, id)
	if err != nil {
		return nil, peopleFacing(err)
	}
	return r.Resolver.grantModels(ctx, actor, grants), nil
}

// DiagnoseAccess is the resolver for the diagnoseAccess field.
//
// Nobody at that address is null, like Person: the answer to "why can she not see it" is
// sometimes "because this installation has never heard of her", and that is a diagnosis the
// screen renders rather than an error.
func (r *queryResolver) DiagnoseAccess(ctx context.Context, mail string) (*model.AccessDiagnosis, error) {
	actor := principal.From(ctx)

	person, err := r.Resolver.People.ByMail(ctx, actor, mail)
	if err != nil {
		if isNotFound(err) {
			return nil, nil
		}
		return nil, peopleFacing(err)
	}

	grants, err := r.Resolver.People.Grants(ctx, actor, person.ID)
	if err != nil {
		return nil, peopleFacing(err)
	}

	return &model.AccessDiagnosis{
		Person:    personModel(*person),
		Active:    person.Active,
		Grants:    r.Resolver.grantModels(ctx, actor, grants),
		Decisions: diagnose(*person),
	}, nil
}
