package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/google/uuid"
	"github.com/obcode/tallox.go/graph/model"
	"github.com/obcode/tallox.go/internal/domain"
	"github.com/obcode/tallox.go/internal/principal"
)

// SetAssignment is the resolver for the setAssignment field.
func (r *mutationResolver) SetAssignment(ctx context.Context, instancePartID string, personID *string, teacherID *string, note *string, replacing *string) (*model.Assignment, error) {
	partID, err := parseID(instancePartID)
	if err != nil {
		return nil, err
	}

	// Both ids are parsed and neither is validated against the other here — "exactly one" is a
	// domain rule and is asserted there, so that the token path and any later caller get the same
	// answer rather than the one this resolver happens to check.
	var who domain.Assignee
	for _, arg := range []struct {
		raw  *string
		into *uuid.UUID
	}{
		{personID, &who.PersonID},
		{teacherID, &who.TeacherID},
	} {
		if arg.raw == nil {
			continue
		}
		id, err := parseID(*arg.raw)
		if err != nil {
			return nil, err
		}
		*arg.into = id
	}

	// Absent means "I believe this part is free", which is the safe direction: a call that names
	// nothing can only fill a part nobody holds.
	var replaced uuid.UUID
	if replacing != nil {
		replaced, err = parseID(*replacing)
		if err != nil {
			return nil, err
		}
	}

	text := ""
	if note != nil {
		text = *note
	}

	assignment, err := r.Staffing.Set(ctx, principal.From(ctx), partID, who, text, replaced)
	if err != nil {
		return nil, assignmentError(err)
	}
	return assignmentModel(*assignment), nil
}

// ClearAssignment is the resolver for the clearAssignment field.
func (r *mutationResolver) ClearAssignment(ctx context.Context, id string) (string, error) {
	assignmentID, err := parseID(id)
	if err != nil {
		return "", err
	}
	if err := r.Staffing.Clear(ctx, principal.From(ctx), assignmentID); err != nil {
		return "", assignmentError(err)
	}
	return id, nil
}

// MyAssignments is the resolver for the myAssignments field.
func (r *queryResolver) MyAssignments(ctx context.Context, semester *string) ([]*model.Assignment, error) {
	// A missing semester is every semester, not a refused query: these are the caller's own rows,
	// and the rule that is per-semester does not apply to them. See the field's own comment.
	code := ""
	if semester != nil {
		code = *semester
	}

	list, err := r.Staffing.Mine(ctx, principal.From(ctx), code)
	if err != nil {
		return nil, assignmentError(err)
	}
	return assignmentModels(list), nil
}

// Assignments is the resolver for the assignments field.
func (r *queryResolver) Assignments(ctx context.Context, semester string, programme *string, module *string, instance *string, person *string) ([]*model.Assignment, error) {
	query := domain.AssignmentQuery{SemesterCode: semester}
	if programme != nil {
		query.Programme = *programme
	}

	for _, arg := range []struct {
		raw  *string
		into *uuid.UUID
	}{
		{module, &query.Module},
		{instance, &query.Instance},
		{person, &query.Person},
	} {
		if arg.raw == nil {
			continue
		}
		id, err := parseID(*arg.raw)
		if err != nil {
			return nil, err
		}
		*arg.into = id
	}

	list, err := r.Staffing.List(ctx, principal.From(ctx), query)
	if err != nil {
		return nil, assignmentError(err)
	}
	return assignmentModels(list), nil
}
