package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/google/uuid"
	"github.com/obcode/tallox.go/graph/generated"
	"github.com/obcode/tallox.go/graph/model"
	"github.com/obcode/tallox.go/internal/domain"
	"github.com/obcode/tallox.go/internal/principal"
)

// DutyStatus is the resolver for the dutyStatus field.
func (r *moduleResolver) DutyStatus(ctx context.Context, obj *model.Module, programme string) (*domain.DutyStatus, error) {
	status, ok := obj.Source.DutyStatus(normaliseCode(programme))
	if !ok {
		// The module does not appear in that programme's catalogue at all, which is a different
		// thing from being elective in it.
		return nil, nil
	}
	return &status, nil
}

// InCatalogue is the resolver for the inCatalogue field.
func (r *moduleResolver) InCatalogue(ctx context.Context, obj *model.Module, programme string) (bool, error) {
	return obj.Source.InCatalogue(normaliseCode(programme)), nil
}

// ProposedComponents is the resolver for the proposedComponents field.
func (r *moduleResolver) ProposedComponents(ctx context.Context, obj *model.Module) ([]*model.ComponentProposal, error) {
	proposals := obj.Source.ProposedComponents()

	out := make([]*model.ComponentProposal, 0, len(proposals))
	for _, c := range proposals {
		out = append(out, &model.ComponentProposal{Kind: c.Kind, TeachingHours: c.TeachingHours})
	}
	return out, nil
}

// SplitIsEstimated is the resolver for the splitIsEstimated field.
func (r *moduleResolver) SplitIsEstimated(ctx context.Context, obj *model.Module) (bool, error) {
	return obj.Source.SplitIsEstimated(), nil
}

// Plannable is the resolver for the plannable field.
func (r *moduleResolver) Plannable(ctx context.Context, obj *model.Module) (bool, error) {
	return obj.Source.Plannable(), nil
}

// ProgrammeSemester is the resolver for the programmeSemester field.
func (r *moduleResolver) ProgrammeSemester(ctx context.Context, obj *model.Module, programme string) (*int, error) {
	semester, ok := obj.Source.ProgrammeSemester(normaliseCode(programme))
	if !ok {
		// The regulations do not say, which for an elective means "no restriction" rather than
		// a number — and is the state nearly half of them are in.
		return nil, nil
	}
	return &semester, nil
}

// SetModuleComponents is the resolver for the setModuleComponents field.
func (r *mutationResolver) SetModuleComponents(ctx context.Context, moduleID string, components []*model.ModuleComponentInput) (*model.Module, error) {
	actor := principal.From(ctx)

	id, err := uuid.Parse(moduleID)
	if err != nil {
		return nil, badRequest("MODULE_NOT_FOUND", domain.ErrModuleNotFound.Error())
	}

	module, err := r.Catalogue.SetModuleComponents(ctx, actor, id, componentsFrom(components))
	if err != nil {
		return nil, catalogueUserFacing(actor, err)
	}
	return moduleModel(*module), nil
}

// Programmes is the resolver for the programmes field.
func (r *queryResolver) Programmes(ctx context.Context) ([]*model.Programme, error) {
	actor := principal.From(ctx)

	programmes, err := r.Catalogue.Programmes(ctx, actor)
	if err != nil {
		return nil, catalogueUserFacing(actor, err)
	}

	out := make([]*model.Programme, 0, len(programmes))
	for _, p := range programmes {
		out = append(out, programmeModel(p))
	}
	return out, nil
}

// Programme is the resolver for the programme field.
func (r *queryResolver) Programme(ctx context.Context, code string) (*model.Programme, error) {
	actor := principal.From(ctx)

	programme, err := r.Catalogue.ProgrammeByCode(ctx, actor, code)
	if err != nil {
		return nil, catalogueUserFacing(actor, err)
	}
	if programme == nil {
		return nil, nil
	}
	return programmeModel(*programme), nil
}

// Modules is the resolver for the modules field.
func (r *queryResolver) Modules(ctx context.Context, filter *model.ModuleFilter) ([]*model.Module, error) {
	actor := principal.From(ctx)

	parsed, err := moduleFilterFrom(filter)
	if err != nil {
		return nil, err
	}

	modules, err := r.Catalogue.Modules(ctx, actor, parsed)
	if err != nil {
		return nil, catalogueUserFacing(actor, err)
	}
	return moduleModels(modules), nil
}

// Module is the resolver for the module field.
func (r *queryResolver) Module(ctx context.Context, id string) (*model.Module, error) {
	actor := principal.From(ctx)

	parsed, err := uuid.Parse(id)
	if err != nil {
		// A malformed id names no module, which is the same answer as an id that names none.
		// Distinguishing them would tell a caller whether a uuid they guessed exists.
		return nil, nil
	}

	module, err := r.Catalogue.ModuleByID(ctx, actor, parsed)
	if err != nil {
		return nil, catalogueUserFacing(actor, err)
	}
	if module == nil {
		return nil, nil
	}
	return moduleModel(*module), nil
}

// Teachers is the resolver for the teachers field.
func (r *queryResolver) Teachers(ctx context.Context, search *string, includeInactive *bool) ([]*model.Teacher, error) {
	actor := principal.From(ctx)

	filter := domain.TeacherFilter{}
	if search != nil {
		filter.Search = *search
	}
	if includeInactive != nil {
		filter.IncludeInactive = *includeInactive
	}

	teachers, err := r.Catalogue.Teachers(ctx, actor, filter)
	if err != nil {
		return nil, catalogueUserFacing(actor, err)
	}

	out := make([]*model.Teacher, 0, len(teachers))
	for _, t := range teachers {
		out = append(out, teacherModel(t))
	}
	return out, nil
}

// Module returns generated.ModuleResolver implementation.
func (r *Resolver) Module() generated.ModuleResolver { return &moduleResolver{r} }

type moduleResolver struct{ *Resolver }
