package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/google/uuid"
	"github.com/obcode/tallox.go/graph/model"
	"github.com/obcode/tallox.go/internal/domain"
	"github.com/obcode/tallox.go/internal/principal"
)

// DeclareCourseInstance is the resolver for the declareCourseInstance field.
func (r *mutationResolver) DeclareCourseInstance(ctx context.Context, input model.DeclareCourseInstanceInput) (*model.CourseInstance, error) {
	actor := principal.From(ctx)

	moduleID, err := uuid.Parse(input.ModuleID)
	if err != nil {
		// The same refusal an unknown id gets. "That is not a uuid" and "there is no such
		// module" are the same situation to the caller, and the second sentence is the useful
		// one.
		return nil, badRequest("MODULE_NOT_FOUND", domain.ErrModuleNotFound.Error())
	}

	spec := domain.DeclareInstance{
		SemesterCode:      input.Semester,
		Programme:         input.Programme,
		ModuleID:          moduleID,
		ProgrammeSemester: input.ProgrammeSemester,
	}
	if input.Track != nil {
		spec.Track = *input.Track
	}

	instance, err := r.Demand.Declare(ctx, actor, spec)
	if err != nil {
		return nil, demandUserFacing(actor, err)
	}
	return courseInstanceModel(*instance), nil
}

// DuplicateCourseInstance is the resolver for the duplicateCourseInstance field.
func (r *mutationResolver) DuplicateCourseInstance(ctx context.Context, id string, track string, sourceTrack *string) (*model.CourseInstance, error) {
	actor := principal.From(ctx)

	instanceID, err := uuid.Parse(id)
	if err != nil {
		return nil, badRequest("INSTANCE_NOT_FOUND", domain.ErrInstanceNotFound.Error())
	}

	var renamed string
	if sourceTrack != nil {
		renamed = *sourceTrack
	}

	instance, err := r.Demand.Duplicate(ctx, actor, instanceID, track, renamed)
	if err != nil {
		return nil, demandUserFacing(actor, err)
	}
	return courseInstanceModel(*instance), nil
}

// ChangeCourseInstance is the resolver for the changeCourseInstance field.
func (r *mutationResolver) ChangeCourseInstance(ctx context.Context, id string, track string, programmeSemester *int) (*model.CourseInstance, error) {
	actor := principal.From(ctx)

	instanceID, err := uuid.Parse(id)
	if err != nil {
		return nil, badRequest("INSTANCE_NOT_FOUND", domain.ErrInstanceNotFound.Error())
	}

	instance, err := r.Demand.Change(ctx, actor, instanceID, track, programmeSemester)
	if err != nil {
		return nil, demandUserFacing(actor, err)
	}
	return courseInstanceModel(*instance), nil
}

// WithdrawCourseInstance is the resolver for the withdrawCourseInstance field.
func (r *mutationResolver) WithdrawCourseInstance(ctx context.Context, id string) (string, error) {
	actor := principal.From(ctx)

	instanceID, err := uuid.Parse(id)
	if err != nil {
		return "", badRequest("INSTANCE_NOT_FOUND", domain.ErrInstanceNotFound.Error())
	}

	if err := r.Demand.Withdraw(ctx, actor, instanceID); err != nil {
		return "", demandUserFacing(actor, err)
	}
	return id, nil
}

// AddInstancePart is the resolver for the addInstancePart field.
func (r *mutationResolver) AddInstancePart(ctx context.Context, instanceID string, kind domain.InstancePartKind, teachingHours *float64) (*model.CourseInstance, error) {
	actor := principal.From(ctx)

	id, err := uuid.Parse(instanceID)
	if err != nil {
		return nil, badRequest("INSTANCE_NOT_FOUND", domain.ErrInstanceNotFound.Error())
	}

	instance, err := r.Demand.AddPart(ctx, actor, id, kind, teachingHours)
	if err != nil {
		return nil, demandUserFacing(actor, err)
	}
	return courseInstanceModel(*instance), nil
}

// ChangeInstancePart is the resolver for the changeInstancePart field.
func (r *mutationResolver) ChangeInstancePart(ctx context.Context, id string, kind domain.InstancePartKind, teachingHours *float64) (*model.CourseInstance, error) {
	actor := principal.From(ctx)

	partID, err := uuid.Parse(id)
	if err != nil {
		return nil, badRequest("PART_NOT_FOUND", domain.ErrPartNotFound.Error())
	}

	instance, err := r.Demand.ChangePart(ctx, actor, partID, kind, teachingHours)
	if err != nil {
		return nil, demandUserFacing(actor, err)
	}
	return courseInstanceModel(*instance), nil
}

// RemoveInstancePart is the resolver for the removeInstancePart field.
func (r *mutationResolver) RemoveInstancePart(ctx context.Context, id string) (*model.CourseInstance, error) {
	actor := principal.From(ctx)

	partID, err := uuid.Parse(id)
	if err != nil {
		return nil, badRequest("PART_NOT_FOUND", domain.ErrPartNotFound.Error())
	}

	instance, err := r.Demand.RemovePart(ctx, actor, partID)
	if err != nil {
		return nil, demandUserFacing(actor, err)
	}
	return courseInstanceModel(*instance), nil
}

// ShareInstancePartAcrossTracks is the resolver for the shareInstancePartAcrossTracks field.
func (r *mutationResolver) ShareInstancePartAcrossTracks(ctx context.Context, id string) (*model.CourseInstance, error) {
	actor := principal.From(ctx)

	partID, err := uuid.Parse(id)
	if err != nil {
		return nil, badRequest("PART_NOT_FOUND", domain.ErrPartNotFound.Error())
	}

	instance, err := r.Demand.SharePartAcrossTracks(ctx, actor, partID)
	if err != nil {
		return nil, demandUserFacing(actor, err)
	}
	return courseInstanceModel(*instance), nil
}

// SplitInstancePartAcrossTracks is the resolver for the splitInstancePartAcrossTracks field.
func (r *mutationResolver) SplitInstancePartAcrossTracks(ctx context.Context, id string) (*model.CourseInstance, error) {
	actor := principal.From(ctx)

	partID, err := uuid.Parse(id)
	if err != nil {
		return nil, badRequest("PART_NOT_FOUND", domain.ErrPartNotFound.Error())
	}

	instance, err := r.Demand.SplitPartAcrossTracks(ctx, actor, partID)
	if err != nil {
		return nil, demandUserFacing(actor, err)
	}
	return courseInstanceModel(*instance), nil
}

// CopyDemandFromSemester is the resolver for the copyDemandFromSemester field.
func (r *mutationResolver) CopyDemandFromSemester(ctx context.Context, from string, to string, programme string) (*model.CopyDemandReport, error) {
	actor := principal.From(ctx)

	report, err := r.Demand.CopyFrom(ctx, actor, from, to, programme)
	if err != nil {
		return nil, demandUserFacing(actor, err)
	}
	return copyReportModel(report), nil
}

// CourseInstances is the resolver for the courseInstances field.
func (r *queryResolver) CourseInstances(ctx context.Context, semester string, programme *string, module *string) ([]*model.CourseInstance, error) {
	actor := principal.From(ctx)

	filter := domain.DemandFilter{SemesterCode: semester}
	if programme != nil {
		filter.Programme = *programme
	}
	if module != nil {
		id, err := uuid.Parse(*module)
		if err != nil {
			return nil, badRequest("MODULE_NOT_FOUND", domain.ErrModuleNotFound.Error())
		}
		filter.Module = id
	}

	instances, err := r.Demand.Instances(ctx, actor, filter)
	if err != nil {
		return nil, demandUserFacing(actor, err)
	}

	out := make([]*model.CourseInstance, 0, len(instances))
	for _, i := range instances {
		out = append(out, courseInstanceModel(i))
	}
	return out, nil
}

// CourseInstance is the resolver for the courseInstance field.
func (r *queryResolver) CourseInstance(ctx context.Context, id string) (*model.CourseInstance, error) {
	actor := principal.From(ctx)

	instanceID, err := uuid.Parse(id)
	if err != nil {
		// Not a refusal: an id that names nothing answers null, like every other by-id lookup
		// in this schema, and a malformed one names nothing.
		return nil, nil
	}

	instance, err := r.Demand.Instance(ctx, actor, instanceID)
	if err != nil {
		return nil, demandUserFacing(actor, err)
	}
	if instance == nil {
		return nil, nil
	}
	return courseInstanceModel(*instance), nil
}
