package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/obcode/tallox.go/graph/model"
	"github.com/obcode/tallox.go/internal/policy"
	"github.com/obcode/tallox.go/internal/principal"
)

// Session is the resolver for the session field.
//
// Thin, like every resolver here, and it answers for anonymous callers rather than erroring:
// the interface renders a signed-out state from this field, and a query that failed would
// give it nothing to render from.
//
// Both role lists come off the same actor. Roles is the effective set — narrowed if the caller
// asked to be — and NarrowedFrom is what they hold. Reading them off the actor rather than
// looking anything up is what makes this answer necessarily the same one every rule in this
// request is judged by; a second lookup would be a second opinion.
func (r *queryResolver) Session(ctx context.Context) (*model.Session, error) {
	actor := principal.From(ctx)

	session := &model.Session{
		EffectiveRoles: policy.RolesOf(actor).Sorted(),
		GrantedRoles:   policy.RolesOf(actor).Sorted(),
		Narrowed:       actor.Narrowed(),
		Interactive:    actor.Interactive(),
	}

	if actor.Narrowed() {
		// The granted set has to be reconstructed from NarrowedFrom, because Roles no longer
		// holds it. Through the same policy.RolesOf, so a grant the policy does not recognise
		// is dropped here exactly as it is dropped everywhere else — telling somebody they
		// hold a role that grants nothing would be worse than not mentioning it.
		granted := actor
		granted.Roles = actor.NarrowedFrom
		session.GrantedRoles = policy.RolesOf(granted).Sorted()
	}

	if actor.Authenticated() {
		session.Person = &model.Person{
			ID:   actor.ID.String(),
			Mail: actor.Mail,
			Name: actor.Name,
			// True by construction: an inactive person does not authenticate, on either door.
			Active: true,
			// The person's own grants, which is what Person.roles means everywhere else too.
			// The narrowing lives in effectiveRoles, one level up; keeping it out of here is
			// what stops Person.roles meaning two different things depending on which person
			// it describes.
			Roles: session.GrantedRoles,
		}
	}

	return session, nil
}
