package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/google/uuid"
	"github.com/obcode/tallox.go/graph/generated"
	"github.com/obcode/tallox.go/graph/model"
	"github.com/obcode/tallox.go/internal/principal"
)

// CreateSubjectGroup is the resolver for the createSubjectGroup field.
func (r *mutationResolver) CreateSubjectGroup(ctx context.Context, code string, name string) (*model.SubjectGroup, error) {
	group, err := r.SubjectGroups.Create(ctx, principal.From(ctx), code, name)
	if err != nil {
		return nil, subjectGroupError(err)
	}
	return subjectGroupModel(*group), nil
}

// RenameSubjectGroup is the resolver for the renameSubjectGroup field.
func (r *mutationResolver) RenameSubjectGroup(ctx context.Context, id string, name string) (*model.SubjectGroup, error) {
	groupID, err := parseID(id)
	if err != nil {
		return nil, err
	}
	group, err := r.SubjectGroups.Rename(ctx, principal.From(ctx), groupID, name)
	if err != nil {
		return nil, subjectGroupError(err)
	}
	return subjectGroupModel(*group), nil
}

// SetSubjectGroupActive is the resolver for the setSubjectGroupActive field.
func (r *mutationResolver) SetSubjectGroupActive(ctx context.Context, id string, active bool) (*model.SubjectGroup, error) {
	groupID, err := parseID(id)
	if err != nil {
		return nil, err
	}
	group, err := r.SubjectGroups.SetActive(ctx, principal.From(ctx), groupID, active)
	if err != nil {
		return nil, subjectGroupError(err)
	}
	return subjectGroupModel(*group), nil
}

// SetModulesSubjectGroup is the resolver for the setModulesSubjectGroup field.
func (r *mutationResolver) SetModulesSubjectGroup(ctx context.Context, moduleIds []string, subjectGroup *string) (*model.SubjectGroupAssignmentReport, error) {
	actor := principal.From(ctx)

	modules, err := parseIDs(moduleIds)
	if err != nil {
		return nil, err
	}

	// A missing group is "take them out of every group" rather than an error: it is the same
	// screen's other button, and a module with no group is a normal state.
	var group uuid.NullUUID
	if subjectGroup != nil {
		id, err := parseID(*subjectGroup)
		if err != nil {
			return nil, err
		}
		group = uuid.NullUUID{UUID: id, Valid: true}
	}

	written, err := r.SubjectGroups.AssignModules(ctx, actor, modules, group)
	if err != nil {
		return nil, subjectGroupError(err)
	}

	report := &model.SubjectGroupAssignmentReport{ModulesAssigned: written}

	if group.Valid {
		assigned, err := r.SubjectGroups.Get(ctx, actor, group.UUID)
		if err != nil {
			return nil, subjectGroupError(err)
		}
		report.SubjectGroup = subjectGroupModel(*assigned)
	}

	// Read after the write, so that the number the screen shows is the one that is true now
	// rather than one recomputed from what the caller thinks it just did.
	remaining, err := r.SubjectGroups.ModulesWithoutSubjectGroup(ctx, actor)
	if err != nil {
		return nil, subjectGroupError(err)
	}
	report.ModulesWithoutSubjectGroup = remaining

	return report, nil
}

// SetSubjectGroupMembers is the resolver for the setSubjectGroupMembers field.
func (r *mutationResolver) SetSubjectGroupMembers(ctx context.Context, id string, personIds []string) (*model.SubjectGroup, error) {
	groupID, err := parseID(id)
	if err != nil {
		return nil, err
	}
	people, err := parseIDs(personIds)
	if err != nil {
		return nil, err
	}
	group, err := r.SubjectGroups.SetMembers(ctx, principal.From(ctx), groupID, people)
	if err != nil {
		return nil, subjectGroupError(err)
	}
	return subjectGroupModel(*group), nil
}

// SetMySubjectGroups is the resolver for the setMySubjectGroups field.
func (r *mutationResolver) SetMySubjectGroups(ctx context.Context, subjectGroupIds []string) ([]*model.SubjectGroup, error) {
	groups, err := parseIDs(subjectGroupIds)
	if err != nil {
		return nil, err
	}
	// The owner is the actor and comes from nowhere else: this mutation has no argument for
	// whose memberships these are, which is what makes it self-service rather than
	// administration by another name.
	mine, err := r.SubjectGroups.SetMine(ctx, principal.From(ctx), groups)
	if err != nil {
		return nil, subjectGroupError(err)
	}
	return subjectGroupModels(mine), nil
}

// SetSubjectGroupLeads is the resolver for the setSubjectGroupLeads field.
func (r *mutationResolver) SetSubjectGroupLeads(ctx context.Context, id string, personIds []string) (*model.SubjectGroup, error) {
	groupID, err := parseID(id)
	if err != nil {
		return nil, err
	}
	people, err := parseIDs(personIds)
	if err != nil {
		return nil, err
	}
	group, err := r.SubjectGroups.SetLeads(ctx, principal.From(ctx), groupID, people)
	if err != nil {
		return nil, subjectGroupError(err)
	}
	return subjectGroupModel(*group), nil
}

// SubjectGroups is the resolver for the subjectGroups field.
func (r *queryResolver) SubjectGroups(ctx context.Context, includeInactive *bool) ([]*model.SubjectGroup, error) {
	groups, err := r.Resolver.SubjectGroups.List(ctx, principal.From(ctx),
		includeInactive != nil && *includeInactive)
	if err != nil {
		return nil, subjectGroupError(err)
	}
	return subjectGroupModels(groups), nil
}

// SubjectGroup is the resolver for the subjectGroup field.
func (r *queryResolver) SubjectGroup(ctx context.Context, id string) (*model.SubjectGroup, error) {
	groupID, err := parseID(id)
	if err != nil {
		return nil, err
	}
	group, err := r.Resolver.SubjectGroups.Get(ctx, principal.From(ctx), groupID)
	// Nothing here is confidential, so "not found" is answered as null rather than as a refusal:
	// a link somebody followed to a group that has since been merged away should render an empty
	// page, not an error.
	if errorsIsSubjectGroupNotFound(err) {
		return nil, nil
	}
	if err != nil {
		return nil, subjectGroupError(err)
	}
	return subjectGroupModel(*group), nil
}

// MySubjectGroups is the resolver for the mySubjectGroups field.
func (r *queryResolver) MySubjectGroups(ctx context.Context) ([]*model.SubjectGroup, error) {
	groups, err := r.Resolver.SubjectGroups.Mine(ctx, principal.From(ctx))
	if err != nil {
		return nil, subjectGroupError(err)
	}
	return subjectGroupModels(groups), nil
}

// ModulesWithoutSubjectGroup is the resolver for the modulesWithoutSubjectGroup field.
func (r *queryResolver) ModulesWithoutSubjectGroup(ctx context.Context) (int, error) {
	n, err := r.Resolver.SubjectGroups.ModulesWithoutSubjectGroup(ctx, principal.From(ctx))
	if err != nil {
		return 0, subjectGroupError(err)
	}
	return n, nil
}

// SubjectGroupsWithoutLead is the resolver for the subjectGroupsWithoutLead field.
func (r *queryResolver) SubjectGroupsWithoutLead(ctx context.Context) (int, error) {
	n, err := r.Resolver.SubjectGroups.SubjectGroupsWithoutLead(ctx, principal.From(ctx))
	if err != nil {
		return 0, subjectGroupError(err)
	}
	return n, nil
}

// Modules is the resolver for the modules field.
func (r *subjectGroupResolver) Modules(ctx context.Context, obj *model.SubjectGroup) ([]*model.ModuleRef, error) {
	groupID, err := parseID(obj.ID)
	if err != nil {
		return nil, err
	}
	modules, err := r.Resolver.SubjectGroups.Modules(ctx, principal.From(ctx), groupID)
	if err != nil {
		return nil, subjectGroupError(err)
	}
	return moduleRefModels(modules), nil
}

// SubjectGroup returns generated.SubjectGroupResolver implementation.
func (r *Resolver) SubjectGroup() generated.SubjectGroupResolver { return &subjectGroupResolver{r} }

type subjectGroupResolver struct{ *Resolver }
