package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/google/uuid"
	"github.com/obcode/tallox.go/graph/model"
	"github.com/obcode/tallox.go/internal/domain"
	"github.com/obcode/tallox.go/internal/policy"
	"github.com/obcode/tallox.go/internal/principal"
)

// SyncZpaNow is the resolver for the syncZpaNow field.
func (r *mutationResolver) SyncZpaNow(ctx context.Context) (*model.ZpaSyncRun, error) {
	actor := principal.From(ctx)
	if !policy.MayTriggerZPASync(actor) {
		return nil, zpaForbidden()
	}

	// Checked before starting, so that a run refused for being too recent costs nothing and
	// says why. The interval lives in internal/domain beside its reasoning, and the interface
	// greys out the button using this same rule rather than a copy of the number.
	if err := r.Import.MayStartManualSync(ctx); err != nil {
		return nil, zpaUserFacing(err)
	}

	var startedBy *uuid.UUID
	if actor.ID != uuid.Nil {
		id := actor.ID
		startedBy = &id
	}

	run, err := r.Import.Sync(ctx, domain.ZPASyncTriggerManual, startedBy)
	if err != nil {
		return nil, zpaUserFacing(err)
	}
	return zpaRunModel(run), nil
}

// ProjectZpaCatalogue is the resolver for the projectZpaCatalogue field.
func (r *mutationResolver) ProjectZpaCatalogue(ctx context.Context) (*model.ZpaCatalogueProjection, error) {
	if !policy.MayTriggerZPASync(principal.From(ctx)) {
		return nil, zpaForbidden()
	}

	projection, err := r.Import.ProjectCatalogue(ctx)
	if err != nil {
		return nil, zpaUserFacing(err)
	}
	return projectionModel(projection), nil
}

// ZpaSyncRuns is the resolver for the zpaSyncRuns field.
func (r *queryResolver) ZpaSyncRuns(ctx context.Context, limit *int) ([]*model.ZpaSyncRun, error) {
	if err := mayReadImport(principal.From(ctx)); err != nil {
		return nil, err
	}

	wanted := 20
	if limit != nil {
		wanted = *limit
	}

	runs, err := r.Import.Runs(ctx, wanted)
	if err != nil {
		return nil, zpaUserFacing(err)
	}

	out := make([]*model.ZpaSyncRun, 0, len(runs))
	for _, run := range runs {
		out = append(out, zpaRunModel(run))
	}
	return out, nil
}

// ZpaSyncRun is the resolver for the zpaSyncRun field.
func (r *queryResolver) ZpaSyncRun(ctx context.Context, id string) (*model.ZpaSyncRun, error) {
	if err := mayReadImport(principal.From(ctx)); err != nil {
		return nil, err
	}

	runID, err := uuid.Parse(id)
	if err != nil {
		// A malformed id is "no such run", not an error. It is the same answer an id that
		// simply does not exist gets, which keeps this from being an oracle for which ids are
		// real.
		return nil, nil
	}

	run, err := r.Import.RunByID(ctx, runID)
	if err != nil {
		return nil, zpaUserFacing(err)
	}
	if run == nil {
		return nil, nil
	}
	return zpaRunModel(*run), nil
}

// ZpaChanges is the resolver for the zpaChanges field.
func (r *queryResolver) ZpaChanges(ctx context.Context, runID string) ([]*model.ZpaChange, error) {
	if err := mayReadImport(principal.From(ctx)); err != nil {
		return nil, err
	}

	id, err := uuid.Parse(runID)
	if err != nil {
		return []*model.ZpaChange{}, nil
	}

	changes, err := r.Import.Changes(ctx, id)
	if err != nil {
		return nil, zpaUserFacing(err)
	}

	out := make([]*model.ZpaChange, 0, len(changes))
	for _, change := range changes {
		out = append(out, zpaChangeModel(change))
	}
	return out, nil
}

// ZpaCatalogueProjections is the resolver for the zpaCatalogueProjections field.
func (r *queryResolver) ZpaCatalogueProjections(ctx context.Context, limit *int) ([]*model.ZpaCatalogueProjection, error) {
	if err := mayReadImport(principal.From(ctx)); err != nil {
		return nil, err
	}

	wanted := 20
	if limit != nil {
		wanted = *limit
	}

	projections, err := r.Import.CatalogueProjections(ctx, wanted)
	if err != nil {
		return nil, zpaUserFacing(err)
	}

	out := make([]*model.ZpaCatalogueProjection, 0, len(projections))
	for _, p := range projections {
		out = append(out, projectionModel(p))
	}
	return out, nil
}
