// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/obcode/tallox.go/internal/domain"
	"github.com/obcode/tallox.go/internal/policy"
)

// The headline figures of one window.
type AccessCounts struct {
	// Every entry in the window, refusals included.
	Total int `json:"total"`
	// Operations through the browser door.
	Interactive int `json:"interactive"`
	// Operations through the Personal Access Token door.
	Token int `json:"token"`
	// Operations that changed something.
	Mutations int `json:"mutations"`
	// Operations that ran and failed.
	Errors int `json:"errors"`
	// Sign-ins that were refused before reaching the schema.
	RefusedAuth int `json:"refusedAuth"`
	// Operations refused because the token's scopes did not cover them.
	RefusedScope int `json:"refusedScope"`
	// Operations refused because a token reached for an interactive-only field.
	RefusedInteractive int `json:"refusedInteractive"`
	// How many distinct people appear. Refused sign-ins have no person and are not counted here —
	// they are counted by `refusedAuth`, and named in `refused`.
	People int `json:"people"`
}

// Why somebody sees what they see.
//
// Answers with decisions, never with content: it says whether a rule lets this person past, and
// it never reads the thing behind the rule. That is what makes it usable for the ordinary
// support question — "why can my colleague not see this" — without becoming a way around the
// confidentiality it is describing.
type AccessDiagnosis struct {
	// The person the diagnosis is about.
	Person *Person `json:"person"`
	// An inactive person fails authentication on both doors, whatever roles they hold.
	Active bool `json:"active"`
	// Their grants, expired ones included.
	Grants []*RoleGrant `json:"grants"`
	// What the rules answer for this person, one entry per rule.
	Decisions []*PolicyDecision `json:"decisions"`
}

// One entry: one operation, or one sign-in that was refused before there was an operation.
type AccessLogEntry struct {
	ID string `json:"id"`
	// When it happened.
	At time.Time `json:"at"`
	// The person this was, when the request had one. `null` for a refused sign-in — which is
	// precisely the case worth looking at, because it is somebody this installation does not know.
	//
	// An id and a name rather than a `Person`. A `Person` carries `roles` and `active` as they are
	// **now**, and putting one on a log entry would place today's answer next to a record of what
	// was true at the time — which is the one confusion this whole table is built to avoid. Follow
	// the id to `person(id:)` to ask about today.
	PersonID *string `json:"personId,omitempty"`
	// The person's name as it stands today, `null` when there is no person row. A rendering
	// convenience, resolved through a join; the entry's own record of who this was is `mail`.
	PersonName *string `json:"personName,omitempty"`
	// The identity as asserted, whether or not it resolved to a person.
	Mail *string `json:"mail,omitempty"`
	// Which mount the request came through.
	Door AccessDoor `json:"door"`
	// The public half of the Personal Access Token used, `null` for the browser door.
	//
	// The same value the owner sees in their token list, so an entry can be matched to a token
	// without the token itself appearing anywhere.
	TokenID *string `json:"tokenId,omitempty"`
	// The roles the request was actually judged by.
	//
	// The effective set: a session that was narrowed counts under what it was narrowed to, which is
	// the honest reading of what the rules saw.
	Roles []policy.Role `json:"roles"`
	// The roles as held, when and only when the caller asked to be narrowed. `null` otherwise.
	NarrowedFrom []policy.Role `json:"narrowedFrom,omitempty"`
	// The operation name from the document. Client-supplied: a label, never a key.
	Operation *string `json:"operation,omitempty"`
	// The root fields the operation asked for. See the note at the top of this file.
	Fields []string `json:"fields"`
	// Whether the operation changed data.
	Mutation bool `json:"mutation"`
	// How it ended.
	Outcome AccessOutcome `json:"outcome"`
	// The error code of the first error, `null` when there was none — `INSUFFICIENT_SCOPE`,
	// `INTERACTIVE_ONLY`, `UNKNOWN_USER`.
	//
	// The code and never the message: the German sentences get reworded, and a log that stored them
	// would be a second place they have to match.
	ErrorCode *string `json:"errorCode,omitempty"`
	// How long the operation took, in milliseconds.
	DurationMs *int `json:"durationMs,omitempty"`
	// Where the request came from, `null` when it could not be determined.
	//
	// A stolen credential is recognised by where it is used and by nothing else, which is the only
	// reason this is recorded at all.
	SourceIP *string `json:"sourceIp,omitempty"`
}

// Narrows a page of the log. Everything is optional; omitting all of it means the whole log,
// newest first.
type AccessLogFilter struct {
	// One person, by id.
	PersonID *string `json:"personId,omitempty"`
	// A substring of the mail address — for the support question that starts with half an address.
	Mail *string `json:"mail,omitempty"`
	// One door — the browser or a Personal Access Token.
	Door *AccessDoor `json:"door,omitempty"`
	// Only entries that did not end in `OK`.
	OnlyRefused *bool `json:"onlyRefused,omitempty"`
	// Only entries that changed something.
	OnlyMutations *bool `json:"onlyMutations,omitempty"`
	// Only entries at or after this moment.
	From *time.Time `json:"from,omitempty"`
	// Only entries strictly before this moment.
	Until *time.Time `json:"until,omitempty"`
}

// One root field somebody changed something with, and how often.
type AccessMutationCount struct {
	// Who changed something.
	Mail string `json:"mail"`
	// The root field they changed it with.
	Field string `json:"field"`
	// How often, over the window.
	Calls int `json:"calls"`
	// The most recent call.
	LastAt time.Time `json:"lastAt"`
}

// How much happened under one effective role.
type AccessRoleCount struct {
	// The effective role the operations were judged by.
	Role policy.Role `json:"role"`
	// How many operations ran under it.
	Operations int `json:"operations"`
}

// What happened in one window.
//
// The same type the nightly report is built from, so the page and the mail cannot come to
// different conclusions about the same night.
type AccessSummary struct {
	// The start of the window, inclusive.
	From time.Time `json:"from"`
	// The end of the window, exclusive — so two consecutive windows cannot count the same entry.
	Until time.Time `json:"until"`
	// The headline figures.
	Counts *AccessCounts `json:"counts"`
	// How much happened under each effective role.
	Roles []*AccessRoleCount `json:"roles"`
	// The sign-ins that never got in. This is the part that names people, and it names them because
	// being turned away is itself the event worth reporting.
	Refused []*RefusedSignIn `json:"refused"`
	// Everything that was changed, by whom and with which root field.
	Mutations []*AccessMutationCount `json:"mutations"`
}

// A sibling cohort's shared part, seen from the cohort it is held for.
type BorrowedPart struct {
	// The part itself, as its owning cohort holds it.
	Part *InstancePart `json:"part"`
	// The cohort that owns the row — the A in "held together with IF3A".
	//
	// Empty is possible and means the sibling has no letter, which happens while somebody is in the
	// middle of splitting a single cohort into two.
	FromTrack string `json:"fromTrack"`
}

// One unit of a split nobody has stated yet.
//
// Separate from `ModuleComponent` because it has no id: there is no row to point at, and there is
// nothing to edit. It is what the software would enter if asked, and it is shown as such.
type ComponentProposal struct {
	// What kind of teaching this unit would be.
	Kind domain.InstancePartKind `json:"kind"`
	// Hours per week for one unit of this kind.
	TeachingHours float64 `json:"teachingHours"`
}

// What copying a semester's demand did.
//
// Reported even when nothing happened. A copy into a semester that already holds the same instances
// writes nothing at all, and "nothing happened" is indistinguishable from "it failed" to the person
// who pressed the button.
type CopyDemandReport struct {
	// The semester copied from.
	From string `json:"from"`
	// The semester copied into.
	To string `json:"to"`
	// The study programme whose demand was copied.
	Programme *Programme `json:"programme"`
	// How many instances were declared.
	Created int `json:"created"`
	// How many were already declared in the target and were left exactly as they are.
	//
	// A copy never overwrites work in the semester it copies into — including a cohort year somebody
	// has since corrected there.
	Skipped int `json:"skipped"`
	// How many parts came with the new instances.
	PartsCreated int `json:"partsCreated"`
	// The demand of the target semester afterwards — the whole list, not only the new rows.
	//
	// So that a screen can render the result of the copy from the answer to the copy, rather than
	// asking again and rendering a moment that is one round trip old.
	Instances []*CourseInstance `json:"instances"`
}

// One module, offered in one semester, for one study programme, to one parallel cohort.
//
// **This is what gets planned, and its parts are what get assigned.** The faculty's own sentence is
// "one person holds the lecture, another the laboratory", so a wish and an assignment will point at
// an `InstancePart` and never at the instance.
//
// The identity is the semester, the module, the programme and the cohort. Two things are
// deliberately not part of it:
//
//   - **The version of the examination regulations.** One lecture in the winter serves every valid
//     version at once — students under IF-2019 and IF-2025 sit in the same room with the same
//     person — so an instance per version would be the same event two to four times in every list.
//     Where the version matters, it is a question about `Module.offerings`.
//   - **The kind of teaching.** A lecture and its laboratories are one instance with several parts,
//     not several instances.
//
// The cohort *is* part of it, and that is the one people are surprised by. An instance is normally
// assigned to one person, and Software Engineering I runs in two cohorts held by two people — so if
// the cohort were a multiplicity inside the instance, "assign IF3A to somebody" would not be a
// sentence this schema could express.
type CourseInstance struct {
	ID string `json:"id"`
	// The semester, in this system's spelling: `2026-WS`.
	//
	// The year is the one the semester *starts* in, so the winter of 2026/27 is `2026-WS`.
	Semester string `json:"semester"`
	// Whose demand this is.
	//
	// Not necessarily the module's home programme. A module at home in one programme and offered by
	// another is exactly what the dean's office's import/export figures are about, and the difference
	// between the two declarations is the export.
	Programme *Programme `json:"programme"`
	// The catalogue entry this is an offering of, with its split and its offerings attached.
	//
	// The same `Module` the catalogue serves, so that "is this compulsory here" and "how do its hours
	// divide" are answerable on a demand screen without a second lookup.
	Module *Module `json:"module"`
	// The parallel cohort — the A in IF3A — and empty for a module that runs once, which is the
	// ordinary case.
	//
	// The letter only. The label a person reads is the programme's code, the cohort year and this,
	// assembled where they are read: storing the assembled string would denormalise two facts and go
	// stale on the third.
	Track string `json:"track"`
	// Which cohort year this is for — the 3 in IF3A — or `null` where nobody has said and the
	// regulations do not either.
	//
	// Seeded from the regulations when the instance is declared and a decision afterwards, rather
	// than derived on every read. Derived it would be a *set* rather than a number: 23 of 1076
	// module/programme pairs disagree across versions of the regulations, and it would change
	// retroactively when a new version lands, renaming a cohort that has already been taught.
	ProgrammeSemester *int `json:"programmeSemester,omitempty"`
	// The assignable units this cohort holds itself, in order.
	//
	// Made from the module's split when the instance is declared — one part per unit — and edited
	// afterwards. The number of laboratory *groups* is a planning decision and lives here, not in the
	// module: a two-hour laboratory in the split is one entry however many groups a cohort runs.
	Parts []*InstancePart `json:"parts"`
	// Parts of a sibling cohort that are held for this one as well.
	//
	// The other half of `InstancePart.sharedAcrossTracks`. A lecture given once for IF3A and IF3B is
	// one row, owned by one of them — and the other has to render it, or its screen shows a cohort
	// with laboratories and no lecture and looks like a planning mistake.
	//
	// Never counted in `teachingHours`: the point of holding a lecture once is that it costs the
	// faculty once.
	BorrowedParts []*BorrowedPart `json:"borrowedParts"`
	// What this instance costs the faculty: the sum over the parts it holds.
	//
	// **Not the module's own `contactHoursPerWeek`**, which is what a student attends. A four-hour
	// module running one lecture and three laboratory groups costs eight hours per cohort, and
	// summing the module's figure would give four — a plausible-looking wrong answer.
	//
	// A part whose hours nobody has stated yet contributes nothing rather than making the sum
	// unanswerable: an instance can be declared before the detail is settled, which is what a demand
	// deadline that comes before the detail requires.
	TeachingHours float64 `json:"teachingHours"`
	// When this instance was declared.
	CreatedAt time.Time `json:"createdAt"`
	// When it was last changed.
	UpdatedAt time.Time `json:"updatedAt"`
}

// A newly created token: the record, and the one and only sight of the secret.
type CreatedPersonalAccessToken struct {
	// The token as it will appear in your list from now on.
	Token *PersonalAccessToken `json:"token"`
	// The complete token, `tallox_<id>_<secret>` — put this in your script's environment.
	//
	// Shown once, here, and never again: the server keeps only a checksum. If you lose it, revoke
	// this token and create another one. That is a two-second inconvenience, and it is the reason
	// a leak of the database is not a leak of anybody's credentials.
	Secret string `json:"secret"`
}

// A demand about to be declared.
type DeclareCourseInstanceInput struct {
	// Four digits, a hyphen and SS or WS, for example `2027-SS`. Upper-cased and trimmed for you.
	Semester string `json:"semester"`
	// The study programme whose demand this is, by its short code.
	Programme string `json:"programme"`
	// The module, by id.
	//
	// The instance's parts are made from the module's split, or — while nobody has stated one — from
	// `Module.proposedComponents`. Only a module the catalogue states no hours for has neither, and
	// that answers `MODULE_NOT_DECOMPOSED`; the repair is `setModuleComponents`.
	ModuleID string `json:"moduleId"`
	// The parallel cohort, or empty for a module that runs once. One to three characters, upper-cased
	// and trimmed for you.
	//
	// Leave it empty at first: turning one cohort into two is `duplicateCourseInstance`, which names
	// both letters at once.
	Track *string `json:"track,omitempty"`
	// The cohort year, or `null` to take what the programme's regulations say — the earliest semester
	// the module may be taken in, across every version of them.
	ProgrammeSemester *int `json:"programmeSemester,omitempty"`
}

// One thing a plan did, or would do.
type DemandChange struct {
	// The module this cohort offers.
	ModuleID string `json:"moduleId"`
	// The module's name, so a summary can be read without a second query.
	ModuleName string `json:"moduleName"`
	// The cohort, after the change.
	Track string `json:"track"`
	// Where a cohort was renamed rather than created: the letter it had before.
	//
	// IF1 becoming IF1A when a second cohort appears beside it. The instance is the same one, which is
	// why its parts — and later the wishes on them — survive.
	TrackBefore *string `json:"trackBefore,omitempty"`
	// Where the number of groups changed: what it was.
	GroupsBefore *int `json:"groupsBefore,omitempty"`
	// Where the number of groups changed: what it is now.
	GroupsAfter *int `json:"groupsAfter,omitempty"`
}

// One row of a demand table: this module, in these cohorts.
type DemandEntryInput struct {
	// The module this row is about.
	ModuleID string `json:"moduleId"`
	// The cohorts to offer. **An empty list is the row whose tick was taken away** and means the
	// module is not offered — its instances are withdrawn.
	//
	// That is the whole difference between "leave it alone" and "withdraw it": a module the call does
	// not mention at all is untouched.
	Tracks []*DemandTrackInput `json:"tracks"`
	// The cohort year for every cohort of this module, or `null` to leave what is stored — and, for a
	// new instance, to take what the regulations say.
	ProgrammeSemester *int `json:"programmeSemester,omitempty"`
}

// What a save did, or — after a dry run — what it would do.
type DemandPlanReport struct {
	// True when nothing was written.
	DryRun bool `json:"dryRun"`
	// Cohorts that were declared.
	Created []*DemandChange `json:"created"`
	// Cohorts that were withdrawn — the rows whose tick was taken away.
	Withdrawn []*DemandChange `json:"withdrawn"`
	// Cohorts that were renamed, or whose number of groups changed.
	Changed []*DemandChange `json:"changed"`
	// What could not be done, one entry per cohort, with the rest of the plan applied.
	Refused []*DemandRefusal `json:"refused"`
	// The demand of that programme afterwards — the whole list, so that one answer redraws the
	// screen. After a dry run it is what is there now, because that is what is there.
	Instances []*CourseInstance `json:"instances"`
	// The teaching those instances cost the faculty, summed. A shared lecture counts once.
	TeachingHours float64 `json:"teachingHours"`
}

// One thing a plan could not do.
type DemandRefusal struct {
	// The module the refused cohort offers.
	ModuleID string `json:"moduleId"`
	// The module's name, so a summary can be read without a second query.
	ModuleName string `json:"moduleName"`
	// The cohort the refusal is about.
	Track string `json:"track"`
	// The machine-readable half: `INSTANCE_IN_USE`, `TRACK_TAKEN`, `MODULE_NOT_DECOMPOSED`.
	//
	// A refusal costs exactly the cohort it is about; the rest of the plan is applied. That is why
	// they are reported rather than raised: one module that cannot be withdrawn must not undo fifteen
	// that could be declared.
	Code string `json:"code"`
	// The sentence to show. `INSTANCE_IN_USE` deliberately says only that something hangs off the
	// instance — never what, never how many.
	Message string `json:"message"`
}

// One cohort of a module, on the way in: a letter and a number of parallel groups.
type DemandTrackInput struct {
	// The cohort letter — the A in IF3A — or empty for a module that runs once.
	//
	// Upper-cased and trimmed for you. One to three characters.
	Track string `json:"track"`
	// How many parallel groups of the practical unit this cohort runs — laboratories, exercises, or
	// the seminar of a module that is nothing else.
	//
	// A module that is nothing but a lecture has no such unit, and there this figure has no effect
	// rather than being an error: a screen that sends the same number for every row must not fail on
	// the one it cannot apply to.
	Groups int `json:"groups"`
}

// One assignable unit of an instance: a lecture, a laboratory group, a seminar.
//
// What a wish and an assignment will point at.
type InstancePart struct {
	ID string `json:"id"`
	// What kind of teaching this part is: a lecture, a laboratory group, a seminar.
	Kind domain.InstancePartKind `json:"kind"`
	// Order within the instance.
	Position int `json:"position"`
	// What a **lecturer** is credited with for holding this part.
	//
	// Starts as what the module's split says and is editable afterwards: the two are different
	// quantities that merely begin equal. `null` while nobody has stated it, which is a normal state
	// for an instance declared before the detail was settled.
	TeachingHours *float64 `json:"teachingHours,omitempty"`
	// This part is held once and serves the other cohorts of the same module as well.
	//
	// The shared lecture: one person gives it for IF3A and IF3B, it happens once, and its hours count
	// once — here, at the cohort that owns the row. Not the default and never automatic: a cohort
	// holds its own teaching unless somebody says otherwise, because sharing by default would make
	// the faculty's hours look smaller than they are until somebody noticed.
	SharedAcrossTracks bool `json:"sharedAcrossTracks"`
}

// A course the faculty enters itself, on the way in.
type LocalModuleInput struct {
	// The programme it is at home in, by its short code — and therefore who may enter it.
	//
	// Only on the way in. `changeLocalModule` does not accept it: the home programme is what the
	// permission is judged against, so allowing it to move would let somebody push a row out of
	// their own reach in the same request.
	Programme string `json:"programme"`
	// What it is called. Unique within the programme, case-insensitively — that is its identity.
	Name string `json:"name"`
	// An ordinary course, or a placeholder for an elective.
	Kind domain.ModuleKind `json:"kind"`
	// How the teaching breaks up, in the examination office's own vocabulary.
	//
	// It decides what `proposedComponents` suggests, so it is worth getting right even when a split
	// is stated here as well.
	CourseType domain.CourseType `json:"courseType"`
	// How often it runs. `ON_ANNOUNCEMENT` is the honest answer for most placeholders.
	Frequency domain.Frequency `json:"frequency"`
	// Contact hours a student attends per week. Not teaching load — see `Module.components`.
	ContactHoursPerWeek *int `json:"contactHoursPerWeek,omitempty"`
	// ECTS credits, or `null` where nobody has said.
	Credits *int `json:"credits,omitempty"`
	// False takes it out of every list without deleting anything.
	//
	// There is no delete and there will not be one: instances point at a module, and later wishes
	// will point at their parts. This is how a course nobody needs any more is retired.
	Active bool `json:"active"`
	// The split, or omitted to let `proposedComponents` stand in.
	//
	// Worth stating for a placeholder: a module the catalogue gives no hours for is refused with
	// `MODULE_NOT_DECOMPOSED` when somebody tries to declare an instance of it.
	Components []*ModuleComponentInput `json:"components,omitempty"`
}

// One unit of a module's split, on the way in.
type ModuleComponentInput struct {
	// What kind of teaching this unit is.
	Kind domain.InstancePartKind `json:"kind"`
	// Hours per week for one unit of this kind. Greater than zero.
	TeachingHours float64 `json:"teachingHours"`
}

// Which modules to list.
//
// An input type rather than separate arguments, unlike `people(search:, includeInactive:)`
// elsewhere in this schema: six filters is past the point where positional arguments read, the set
// will grow as subject groups and competences arrive, and an interface's form maps onto it field
// for field.
type ModuleFilter struct {
	// Relevant for this study programme, by its short code.
	//
	// Two things at once, and the second half is not redundant: the module counts in one of the
	// programme's sets of regulations, **or** the programme is its home. Twenty-six active modules
	// are only reachable through the second half, ten of them in the faculty's largest programme —
	// and the first thing somebody does is look for a module they are responsible for.
	Programme *string `json:"programme,omitempty"`
	// Narrow to one version of the regulations.
	//
	// No default, deliberately. Unfiltered, a programme's list is the union over every version it
	// has: a module dropped from the newest one is still being taught to the students of the older.
	Spo *string `json:"spo,omitempty"`
	// Keep only modules with one of these frequencies.
	//
	// To find what could run in a winter semester, ask for `EVERY_WINTER_SEMESTER`,
	// `EVERY_SEMESTER`, `ALTERNATING_WITHIN_SUBJECT_GROUP`, `ON_ANNOUNCEMENT` and `UNKNOWN` — the
	// last three say nothing about the term and are together more than half the catalogue, so
	// leaving them out hides far more than it removes.
	Frequency []domain.Frequency `json:"frequency,omitempty"`
	// Compulsory or elective. Requires `programme`, and is ignored without it — the answer is a
	// property of a module *in a programme*, not of a module.
	Duty *domain.DutyStatus `json:"duty,omitempty"`
	// A substring of the name or of one of the module codes. Case-insensitive.
	Search *string `json:"search,omitempty"`
	// Include modules the examination office has retired. About a hundred of them.
	IncludeInactive *bool `json:"includeInactive,omitempty"`
	// Only the modules this person is responsible for, by teacher id.
	Responsible *string `json:"responsible,omitempty"`
	// Keep only modules whose split nobody has confirmed yet — where `splitIsEstimated` is true.
	//
	// The work list. Planning works without it, because the proposal stands in; what this filter
	// finds is where the software is guessing and a person has not yet agreed. A bounded, finishable
	// task rather than an open form.
	WithoutComponents *bool `json:"withoutComponents,omitempty"`
}

// Everything that changes something.
//
// All of it is `@interactiveOnly` for now: writing happens in a signed-in browser session, not
// through a Personal Access Token.
type Mutation struct {
}

// A person in the planning.
//
// Carries identity and roles, nothing else. Teaching load and notes about people are not
// reachable here — see the `@interactiveOnly` note in the API documentation.
type Person struct {
	ID string `json:"id"`
	// The address the university's login asserts. Case-insensitive, and the key we match on.
	Mail string `json:"mail"`
	Name string `json:"name"`
	// Surname first, for a list — `Braun, Oliver` where `name` is `Prof. Dr. Oliver Braun`.
	//
	// Taken from the list the examination office publishes, matched on the address, and `null` for
	// everybody it does not know: which word of a written-out name is the surname is not something to
	// guess at. A list falls back to `name` for those, which is why they are still in it.
	//
	// Only the administration reads fill this in. It is a name for a list, and nothing else needs
	// one — `me` answers `null` here whoever asks.
	SortName *string `json:"sortName,omitempty"`
	// Whether this account can be used at all.
	//
	// An inactive person is refused at both doors, whatever roles they hold — deactivating is the
	// removal this system has, and it takes away every token in the same moment. Nobody is ever
	// deleted: the assignments they held stay in the history.
	Active bool `json:"active"`
	// The roles this person holds, in a stable order.
	Roles []policy.Role `json:"roles"`
	// The study programmes this person's study-programme leadership applies to.
	//
	// Empty for everybody who does not lead one — and empty for a lead nobody has assigned a
	// programme to yet, which is a state with consequences rather than a gap: such a lead may
	// declare no demand at all. An empty list here is **not** "every programme". The role leads
	// one; the role that means all of them is the dean's office.
	//
	// Readable through both doors, like `roles`: which programmes you may plan is the first thing a
	// script needs to know, and on `me` it is your own data.
	Programmes []*Programme `json:"programmes"`
}

// A Personal Access Token, as its owner sees it.
//
// The secret is not here and never will be: the server keeps only a checksum of it, so no query
// can hand it out a second time.
type PersonalAccessToken struct {
	// The public half of the token — the part between the two underscores in `tallox_…_…`.
	//
	// Safe to write down, safe to read out over the phone. It identifies the token in this list
	// and in the audit log, and it is what you pass to `revokePersonalAccessToken`.
	ID string `json:"id"`
	// What you called it. Shown in the list, so that revoking the right one is not guesswork.
	Description string `json:"description"`
	// The `area:verb` grants this token carries — see the `@scope` directive.
	//
	// **An empty list means unrestricted**: the token may do everything its owner's roles allow.
	// Scopes only ever narrow. There is currently no way to choose them when creating a token, so
	// in practice this list is empty; the enforcement is live, and tokens created now keep working
	// when the choice arrives.
	Scopes    []string  `json:"scopes"`
	CreatedAt time.Time `json:"createdAt"`
	// When this token stops working. There is no token without an expiry: 90 days by default, 365
	// at most.
	ExpiresAt time.Time `json:"expiresAt"`
	// Roughly when the token was last used, or `null` if it never was.
	//
	// Deliberately coarse — it is only updated when the previous value is more than five minutes
	// old. It answers "is this still in use, can I revoke it", which is what it is for.
	LastUsedAt *time.Time `json:"lastUsedAt,omitempty"`
	// When it was withdrawn, or `null` while it still works.
	RevokedAt *time.Time `json:"revokedAt,omitempty"`
}

// One rule, and what it answers for this person.
type PolicyDecision struct {
	// The rule, named as it is named in the source — so that a report can be acted on.
	Rule string `json:"rule"`
	// What the rule answers for this person right now.
	Allowed bool `json:"allowed"`
	// Why, in a sentence somebody without the source in front of them can use.
	Reason string `json:"reason"`
}

// Everything that can be read.
//
// Start with `me` to check that your token works and to see which roles you hold — the roles
// decide what the rest of these fields answer.
type Query struct {
}

// One identity that was turned away, grouped over the window.
//
// Grouped rather than listed: somebody whose account has no person row will retry, and twelve
// identical lines say nothing that one line with a count does not.
type RefusedSignIn struct {
	// The address the door was knocked on with, empty on the token door.
	//
	// Both this and `tokenId` can be empty at once: a credential too malformed to parse yields
	// neither, and is still a knock at the door.
	Mail string `json:"mail"`
	// The public half of the token presented, empty on the browser door.
	TokenID string `json:"tokenId"`
	// The refusal's error code, empty when the door did not name one.
	Reason string `json:"reason"`
	// Which mount was knocked on.
	Door AccessDoor `json:"door"`
	// How often, over the window.
	Attempts int `json:"attempts"`
	// The most recent attempt.
	LastAt time.Time `json:"lastAt"`
}

// One role grant, as stored — including one that has already expired.
//
// Deliberately unfiltered, unlike `Person.roles`. "DEANS_OFFICE, granted on Tuesday by X,
// expired on Wednesday" is the answer to the only question this record gets asked: who could see
// what, and when.
type RoleGrant struct {
	// The role that was granted.
	Role policy.Role `json:"role"`
	// When it was granted. Refreshed when the same grant is re-issued with a new expiry.
	GrantedAt time.Time `json:"grantedAt"`
	// Who granted it, or `null` for a grant no human decided — the reconciliation of the
	// protected administrators from the configuration file, or a future import.
	GrantedBy *Person `json:"grantedBy,omitempty"`
	// When it stops taking effect, or `null` if it does not expire.
	//
	// A grant with a date on it is how somebody steps over a threshold and has the database step
	// back over it for them. The intended use is "let me look at this until this evening", not a
	// way to hold a role for a semester — a grant meant to last that long should be visible as a
	// permanent one rather than as a date nobody rereads.
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
}

// One `area: verb` pair, when creating a token.
type ScopeGrantInput struct {
	// Which part of the API. The fields belonging to each area are listed on `ScopeArea`.
	Area policy.ScopeArea `json:"area"`
	// `READ` for queries, `WRITE` for mutations — and `WRITE` includes `READ` in the same area.
	Verb policy.ScopeVerb `json:"verb"`
}

// One semester, and where its planning stands.
//
// **Nobody creates a semester.** It is a name for a stretch of time and it is there the way next
// March is there — `semesters` lists the ones near now, and every code within reach can be asked
// about. What gets created is a *decision* about one: switching its phase, publishing its wishes.
// A semester nobody has decided anything about is in `DEMAND_PLANNING` with its wishes
// confidential, which is the start of the process and needs no act to arrive at.
type Semester struct {
	// The semester in the form `2026-WS` or `2026-SS`: four digits, a hyphen and the term.
	//
	// The digits are the year the term *starts* in, so the winter semester 2026/27 is `2026-WS`.
	// This is the spelling the faculty already uses — the examination office writes `WS 2026`, and
	// the hyphen is here because a space has to be quoted in a URL, a filename or a shell argument.
	//
	// Sorts chronologically as plain text (`2026-SS` < `2026-WS` < `2027-SS`), which is why it is
	// worth having in a filename or a script rather than the id.
	Code string `json:"code"`
	// Where the planning stands.
	Phase policy.Phase `json:"phase"`
	// Whether this is the semester the faculty is planning right now. At most one is.
	//
	// The answer to "which semester is this page about" before anybody has chosen one — a
	// preselection for every screen and a default for every script, so that neither has to guess.
	//
	// **Not derived from `phase`.** The obvious rule, "the newest one that is not `FINAL`", is
	// ambiguous exactly when it matters: while the summer is being assigned, the winter is already
	// in demand planning and both are open. Which of the two is meant is a decision somebody takes,
	// the same way the phase is.
	IsPlanningSemester bool `json:"isPlanningSemester"`
	// The phases this semester can be switched to right now — one step away, in either direction.
	//
	// Computed from the same rule the mutation enforces, so an interface can render exactly the
	// buttons that will work.
	ReachablePhases []policy.Phase `json:"reachablePhases"`
	// When the wishes of this semester became visible to everybody, or `null` while they are still
	// confidential.
	//
	// Separate from the phase on purpose, and not tied to it: the wish phase can end without
	// publishing, so that late entries stop while the planners work, and publication can happen
	// while the assignment is already running.
	//
	// There is no un-publishing. Once colleagues have seen each other's entries, clearing this
	// would only be a lie about it.
	WishesPublishedAt *time.Time `json:"wishesPublishedAt,omitempty"`
	// When the last decision about this semester was recorded, or `null` while none has been.
	//
	// Not "when the semester was created" — nothing creates one. It is the phase switch or the
	// publication that this timestamp belongs to, and `null` means the semester is simply sitting
	// in the calendar, untouched. A repeated `publishWishes` does not move it.
	DecidedAt *time.Time `json:"decidedAt,omitempty"`
}

// How the current request is being judged.
//
// Read this rather than `me` when the question is "what may I do right now": it accounts for a
// role narrowing, which `me` deliberately does not.
type Session struct {
	// Who you are, or `null` if you are not signed in. The same value as the `me` query.
	Person *Person `json:"person,omitempty"`
	// The roles this request is actually judged by.
	//
	// Equal to `grantedRoles` unless you asked to be narrowed. This is the list an interface
	// should render its navigation from.
	EffectiveRoles []policy.Role `json:"effectiveRoles"`
	// The roles you hold, whatever you are currently being judged by.
	//
	// What you get back by ending the narrowing — which is why the control that ends it must not
	// itself be hidden by the narrowing.
	GrantedRoles []policy.Role `json:"grantedRoles"`
	// Whether you asked to be judged by fewer roles than you hold.
	//
	// `true` means what you are looking at is a preview and not your own view. Say so visibly:
	// somebody who forgets they are narrowed will eventually report a missing feature as a bug.
	Narrowed bool `json:"narrowed"`
	// Whether this is a signed-in browser session rather than a Personal Access Token.
	//
	// `false` means the `@interactiveOnly` fields will answer `null` — worth checking before
	// concluding that something is empty.
	Interactive bool `json:"interactive"`
}

// A subject the faculty groups modules and people by.
//
// Three things hang off it and they are not the same thing:
//
//   - **Modules.** Exactly one group per module — "whose group fills this instance" is the sentence
//     the whole assignment phase is made of, and it has to have one answer.
//   - **Members.** The colleagues who work in these subjects. This is **not** a permission: it decides
//     what the wish screen offers first and nothing else.
//   - **Leads.** The colleagues who fill this group's instances — and, before publication, who read
//     the wishes on them. This one *is* a grant.
type SubjectGroup struct {
	ID string `json:"id"`
	// The short name the faculty says out loud: `MATHE`, `SWE`, `TI`.
	//
	// What belongs in a URL and in a colleague's evaluation script, like a programme's code. Up to
	// sixteen characters, so that a group split off another can carry a distinguishable suffix
	// (`MATHE-ML`) instead of encoding it into the name.
	Code string `json:"code"`
	// The name a person reads: `Mathematik (klassisch)`.
	Name string `json:"name"`
	// False for a group that has been retired — split into two, or wound up.
	//
	// There is no delete and there will not be one. A retired group still has to render in the
	// planning it was part of, and its modules keep their assignment: reassigning 506 modules is
	// weeks of somebody's judgement, and a delete that took it would be silent.
	Active bool `json:"active"`
	// The colleagues who lead this group, in the order a list reads.
	//
	// Empty is a real state, and the reason the faculty's "keine Fachgruppe ohne Person, die sich
	// ihrer annimmt" is a work list here rather than a constraint: a group has to be creatable before
	// its lead is decided, and a lead has to be revocable without destroying the group.
	//
	// A lead whose grant has expired is not in this list. The grant is what the scope narrows, so a
	// scope outliving it would be a permission nobody granted.
	Leads []*Person `json:"leads"`
	// The colleagues who work in this group's subjects.
	//
	// Readable by anybody with an account, and that is a decision rather than an oversight. The
	// kickoff asks for it — "jeder in einer Fachgruppe müsste alles lesen können" — and who teaches at
	// this faculty is already answerable through `teachers`. What that sentence does **not** extend to
	// is unpublished wishes: those are read by the lead alone, because the first-come-first-served
	// race the confidentiality rule ends plays out inside a subject group, not across them.
	//
	// Membership grants nothing. `policy.AssignmentScope` deliberately does not read it.
	Members []*Person `json:"members"`
	// How many modules are assigned to this group.
	//
	// Safe in a way a count over wishes never is: a module assignment is catalogue data, and nobody
	// is protected from it being known.
	ModuleCount int `json:"moduleCount"`
}

// What assigning a batch of modules did.
//
// Reported as a number even when it is zero, because "nothing happened" and "it failed" are
// indistinguishable to the person who pressed the button otherwise.
type SubjectGroupAssignmentReport struct {
	// The group the modules were put into, or `null` where they were taken out of every group.
	SubjectGroup *SubjectGroup `json:"subjectGroup,omitempty"`
	// How many module assignments were written or removed.
	ModulesAssigned int `json:"modulesAssigned"`
	// How many active modules still have no subject group at all.
	//
	// October's work list as a number: a bounded, finishable task, the same shape as "14 modules
	// without a split". Retired modules are not counted — a module the examination office stopped
	// publishing is not work anybody has to finish.
	ModulesWithoutSubjectGroup int `json:"modulesWithoutSubjectGroup"`
}

// Somebody the examination office publishes, together with the account they have here.
type TeacherAccount struct {
	// The person as the examination office publishes them. Importing them granted nothing.
	Teacher *Teacher `json:"teacher"`
	// Their account here, or `null` if nobody of this address may sign in.
	//
	// An account somebody deactivated is **not** `null`: it is an account with `active: false`.
	// The two look alike from outside and are not — one has never been admitted, the other has been
	// admitted and had it taken away — and the next step differs accordingly.
	Account *Person `json:"account,omitempty"`
}

// One rebuild of the module catalogue out of the cached payloads.
type ZpaCatalogueProjection struct {
	ID string `json:"id"`
	// The import run that triggered this, or `null` for a projection somebody asked for on its own.
	//
	// Both happen: every successful import projects, and the rules of the projection change often
	// enough that applying a new one to data already held has to be possible.
	RunID *string `json:"runId,omitempty"`
	// When it started. Written before the first statement, so a projection that crashed is still visible.
	StartedAt time.Time `json:"startedAt"`
	// When it ended, or `null` while it is still going.
	FinishedAt *time.Time `json:"finishedAt,omitempty"`
	// How it ended.
	Status domain.ProjectionStatus `json:"status"`
	// How many study programmes were written.
	ProgrammesWritten int `json:"programmesWritten"`
	// How many teachers were written.
	TeachersWritten int `json:"teachersWritten"`
	// How many modules were written.
	ModulesWritten int `json:"modulesWritten"`
	// How many entries of 'this module counts in these regulations' were written.
	OfferingsWritten int `json:"offeringsWritten"`
	// How many such entries were removed because the source stopped supporting them.
	//
	// The only thing a projection deletes, and it is safe because nothing points at one. A module
	// that disappears keeps its row and gains a retirement date instead.
	OfferingsRemoved int `json:"offeringsRemoved"`
	// Why it failed, or `null`.
	Error *string `json:"error,omitempty"`
	// What the projection made of the parts of the source that are not tidy.
	Notes []*ZpaProjectionNote `json:"notes"`
}

// One line of a run's report.
//
// Deliberately without the payloads. They are kept in the database for the durable answer months
// later, but shipping two documents per line into a list is a great many bytes for a view that
// renders field names.
type ZpaChange struct {
	ID string `json:"id"`
	// Which kind of object.
	Kind domain.ZPAKind `json:"kind"`
	// The object's identifier in the examination office's database.
	ZpaID string `json:"zpaId"`
	// A human-readable name, or `null` when the payload carries none.
	//
	// Modules have none today: their objects carry no name field at all, and the name exists only
	// inside the nested object of an association row.
	Label *string `json:"label,omitempty"`
	// What happened to it.
	Change domain.ZPAChangeType `json:"change"`
	// The top-level fields whose content differs, for a change; empty otherwise.
	//
	// Field names only. This is what turns "the content differs" into something readable — "the
	// hours per week and the person responsible changed" rather than two documents side by side.
	ChangedKeys []string `json:"changedKeys"`
	// When this was noticed.
	DetectedAt time.Time `json:"detectedAt"`
}

// One line of a projection's report: what it found, how often, and a few examples.
//
// Counts and samples rather than a row per object. The useful sentence is "665 associations across
// 12 sets of regulations", and whoever wants to chase one needs a handful of identifiers rather
// than all of them.
type ZpaProjectionNote struct {
	// What was found.
	Finding domain.ProjectionNoteCode `json:"finding"`
	// How many objects it applies to.
	Count int `json:"count"`
	// Up to twenty examples: examination office identifiers, or the phrases that were not
	// recognised, or the programme codes — whichever is the useful thing to look at for this
	// finding.
	Sample []string `json:"sample"`
}

// One run of the module master data import.
type ZpaSyncRun struct {
	ID string `json:"id"`
	// What started it.
	Trigger domain.ZPASyncTrigger `json:"trigger"`
	// The name of whoever asked for it, or `null` for the nightly job.
	//
	// A name rather than a `Person`, because that is all this answers: the question is "who set
	// this off", not "tell me about them", and a link into the people graph from here would be a
	// second route to person data with its own rules to get right.
	//
	// Only ever a person, never a token: asking for a run is an act with an effect outside this
	// database, so it stays attributable to somebody who signed in.
	StartedBy *string `json:"startedBy,omitempty"`
	// When it started. Written before the first fetch, so a run that crashed is still visible.
	StartedAt time.Time `json:"startedAt"`
	// When it ended, or `null` while it is still going.
	FinishedAt *time.Time `json:"finishedAt,omitempty"`
	// How it ended.
	Status domain.ZPASyncStatus `json:"status"`
	// How many objects were fetched in total.
	Fetched int `json:"fetched"`
	// How many were seen for the first time, or came back after an absence.
	Appeared int `json:"appeared"`
	// How many already held objects had different content.
	Changed int `json:"changed"`
	// How many a successful fetch stopped mentioning.
	Disappeared int `json:"disappeared"`
	// Why it failed or was only partly applied, or `null`.
	Error *string `json:"error,omitempty"`
	// What each endpoint did.
	Kinds []*ZpaSyncRunKind `json:"kinds"`
}

// What one endpoint did within a run.
type ZpaSyncRunKind struct {
	// Which endpoint.
	Kind domain.ZPAKind `json:"kind"`
	// Whether this endpoint was applied.
	Status domain.ZPASyncStatus `json:"status"`
	// How many objects it returned.
	Fetched int `json:"fetched"`
	// Why it failed, in the words the operator needs, or `null`.
	Error *string `json:"error,omitempty"`
}

// Which mount a request came through.
type AccessDoor string

const (
	// A person in a browser, behind the authentication proxy.
	AccessDoorInteractive AccessDoor = "INTERACTIVE"
	// A Personal Access Token: a script, a notebook, a cron job.
	AccessDoorToken AccessDoor = "TOKEN"
)

var AllAccessDoor = []AccessDoor{
	AccessDoorInteractive,
	AccessDoorToken,
}

func (e AccessDoor) IsValid() bool {
	switch e {
	case AccessDoorInteractive, AccessDoorToken:
		return true
	}
	return false
}

func (e AccessDoor) String() string {
	return string(e)
}

func (e *AccessDoor) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AccessDoor(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AccessDoor", str)
	}
	return nil
}

func (e AccessDoor) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AccessDoor) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AccessDoor) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// How a request ended.
//
// Three kinds of refusal rather than one, because they are three different events with three
// different answers. A refused sign-in is somebody who cannot get in at all. A scope refusal is a
// colleague's script asking for something its token was not minted for, and the fix is a new
// token. An interactive-only refusal is a script reaching for personnel data, and the fix is not a
// new token — it is the person, in a browser.
type AccessOutcome string

const (
	// The operation ran and returned no error.
	AccessOutcomeOk AccessOutcome = "OK"
	// The operation ran and failed.
	AccessOutcomeError AccessOutcome = "ERROR"
	// The request never reached the schema: an unknown identity, a deactivated person, an expired or
	// revoked token. The only outcome that appears without a person.
	AccessOutcomeRefusedAuth AccessOutcome = "REFUSED_AUTH"
	// The token's scopes did not cover what the operation asked for.
	AccessOutcomeRefusedScope AccessOutcome = "REFUSED_SCOPE"
	// A token reached for a field that is available only in an interactive session.
	AccessOutcomeRefusedInteractive AccessOutcome = "REFUSED_INTERACTIVE"
)

var AllAccessOutcome = []AccessOutcome{
	AccessOutcomeOk,
	AccessOutcomeError,
	AccessOutcomeRefusedAuth,
	AccessOutcomeRefusedScope,
	AccessOutcomeRefusedInteractive,
}

func (e AccessOutcome) IsValid() bool {
	switch e {
	case AccessOutcomeOk, AccessOutcomeError, AccessOutcomeRefusedAuth, AccessOutcomeRefusedScope, AccessOutcomeRefusedInteractive:
		return true
	}
	return false
}

func (e AccessOutcome) String() string {
	return string(e)
}

func (e *AccessOutcome) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AccessOutcome(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AccessOutcome", str)
	}
	return nil
}

func (e AccessOutcome) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AccessOutcome) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AccessOutcome) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
