// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: competence.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const competenceByID = `-- name: CompetenceByID :one
SELECT
    c.id, c.module_id, c.person_id, c.teacher_id, c.level, c.note, c.created_at, c.updated_at,
    m.name AS module_name,
    EXISTS (SELECT 1 FROM module_offering o WHERE o.module_id = m.id AND o.is_duty) AS compulsory,
    sg.id AS subject_group_id, sg.code AS subject_group_code, sg.name AS subject_group_name,
    COALESCE(person.name, t.full_name, '')::text AS holder_name,
    COALESCE(person.mail, t.mail, '')::citext AS holder_mail,
    COALESCE(NULLIF(ts.short_name, ''), NULLIF(t.short_name, ''), person.name, t.full_name, '')::text
        AS holder_sort_name,
    COALESCE(c.person_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM person_subject_group psg
        WHERE psg.person_id = c.person_id AND psg.subject_group_id = msg.subject_group_id
    ), false)::bool AS outside_subject_groups
FROM competence c
JOIN module m ON m.id = c.module_id
LEFT JOIN module_subject_group msg ON msg.module_id = m.id
LEFT JOIN subject_group sg ON sg.id = msg.subject_group_id
LEFT JOIN person ON person.id = c.person_id
LEFT JOIN teacher t ON t.id = c.teacher_id
LEFT JOIN teacher ts ON ts.mail = person.mail
WHERE c.id = $1::uuid
  AND (
      $2::text = 'all'
      OR ($2::text = 'own'
          AND c.person_id = $3::uuid)
      OR ($2::text = 'own_or_scoped'
          AND (c.person_id = $3::uuid
               OR m.home_programme_id = ANY ($4::uuid[])
               OR msg.subject_group_id = ANY ($5::uuid[])))
  )
`

type CompetenceByIDParams struct {
	ID              uuid.UUID
	Scope           string
	OwnerID         uuid.UUID
	ProgrammeIds    []uuid.UUID
	SubjectGroupIds []uuid.UUID
}

type CompetenceByIDRow struct {
	ID                   uuid.UUID
	ModuleID             uuid.UUID
	PersonID             uuid.NullUUID
	TeacherID            uuid.NullUUID
	Level                string
	Note                 string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	ModuleName           string
	Compulsory           bool
	SubjectGroupID       uuid.NullUUID
	SubjectGroupCode     *string
	SubjectGroupName     *string
	HolderName           string
	HolderMail           string
	HolderSortName       string
	OutsideSubjectGroups bool
}

// One competence, through the same filter.
func (q *Queries) CompetenceByID(ctx context.Context, arg CompetenceByIDParams) (CompetenceByIDRow, error) {
	row := q.db.QueryRow(ctx, competenceByID,
		arg.ID,
		arg.Scope,
		arg.OwnerID,
		arg.ProgrammeIds,
		arg.SubjectGroupIds,
	)
	var i CompetenceByIDRow
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.PersonID,
		&i.TeacherID,
		&i.Level,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModuleName,
		&i.Compulsory,
		&i.SubjectGroupID,
		&i.SubjectGroupCode,
		&i.SubjectGroupName,
		&i.HolderName,
		&i.HolderMail,
		&i.HolderSortName,
		&i.OutsideSubjectGroups,
	)
	return i, err
}

const competenceModuleContext = `-- name: CompetenceModuleContext :one
SELECT
    m.id,
    COALESCE(m.active AND m.retired_at IS NULL, false)::bool AS open,
    msg.subject_group_id,
    EXISTS (
        SELECT 1 FROM person_subject_group psg
        WHERE psg.person_id = $1::uuid
          AND psg.subject_group_id = msg.subject_group_id
    ) AS is_member
FROM module m
LEFT JOIN module_subject_group msg ON msg.module_id = m.id
WHERE m.id = $2::uuid
`

type CompetenceModuleContextParams struct {
	PersonID uuid.UUID
	ModuleID uuid.UUID
}

type CompetenceModuleContextRow struct {
	ID             uuid.UUID
	Open           bool
	SubjectGroupID uuid.NullUUID
	IsMember       bool
}

// What the write rule needs about a module: whether it may be stated for at all, its subject
// group, and whether this person is a member of that group.
//
// One statement, so that the decision is taken against one state. A module in no subject group
// answers with a NULL group and is_member false: nobody can state a competence for it yet, because
// the rule is "the subjects of your groups" and it is in none.
func (q *Queries) CompetenceModuleContext(ctx context.Context, arg CompetenceModuleContextParams) (CompetenceModuleContextRow, error) {
	row := q.db.QueryRow(ctx, competenceModuleContext, arg.PersonID, arg.ModuleID)
	var i CompetenceModuleContextRow
	err := row.Scan(
		&i.ID,
		&i.Open,
		&i.SubjectGroupID,
		&i.IsMember,
	)
	return i, err
}

const competences = `-- name: Competences :many

SELECT
    c.id, c.module_id, c.person_id, c.teacher_id, c.level, c.note, c.created_at, c.updated_at,
    m.name AS module_name,
    -- Compulsory somewhere: under at least one version of some programme's regulations. What the
    -- kickoff means by "Pflichtkatalog", and what the minimum counts.
    EXISTS (SELECT 1 FROM module_offering o WHERE o.module_id = m.id AND o.is_duty) AS compulsory,
    sg.id AS subject_group_id, sg.code AS subject_group_code, sg.name AS subject_group_name,
    COALESCE(person.name, t.full_name, '')::text AS holder_name,
    COALESCE(person.mail, t.mail, '')::citext AS holder_mail,
    COALESCE(NULLIF(ts.short_name, ''), NULLIF(t.short_name, ''), person.name, t.full_name, '')::text
        AS holder_sort_name,
    -- A person's entry on a module outside every subject group they are in. Stays readable and
    -- removable — silently deleting somebody's statement because they left a group loses what
    -- they typed — and is shown as such. Always false for a teacher row, who has no memberships.
    COALESCE(c.person_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM person_subject_group psg
        WHERE psg.person_id = c.person_id AND psg.subject_group_id = msg.subject_group_id
    ), false)::bool AS outside_subject_groups
FROM competence c
JOIN module m ON m.id = c.module_id
LEFT JOIN module_subject_group msg ON msg.module_id = m.id
LEFT JOIN subject_group sg ON sg.id = msg.subject_group_id
LEFT JOIN person ON person.id = c.person_id
LEFT JOIN teacher t ON t.id = c.teacher_id
LEFT JOIN teacher ts ON ts.mail = person.mail
WHERE ($1::uuid IS NULL OR c.module_id = $1::uuid)
  AND ($2::uuid IS NULL
       OR msg.subject_group_id = $2::uuid)
  AND ($3::uuid IS NULL OR c.person_id = $3::uuid)
  AND ($4::uuid IS NULL OR c.teacher_id = $4::uuid)
  AND (
      $5::text = 'all'
      OR ($5::text = 'own'
          AND c.person_id = $6::uuid)
      OR ($5::text = 'own_or_scoped'
          AND (c.person_id = $6::uuid
               OR m.home_programme_id = ANY ($7::uuid[])
               OR msg.subject_group_id = ANY ($8::uuid[])))
  )
ORDER BY m.name, m.id, c.level,
         COALESCE(NULLIF(ts.short_name, ''), NULLIF(t.short_name, ''), person.name, t.full_name),
         c.id
`

type CompetencesParams struct {
	Module          uuid.NullUUID
	SubjectGroup    uuid.NullUUID
	Person          uuid.NullUUID
	Teacher         uuid.NullUUID
	Scope           string
	OwnerID         uuid.UUID
	ProgrammeIds    []uuid.UUID
	SubjectGroupIds []uuid.UUID
}

type CompetencesRow struct {
	ID                   uuid.UUID
	ModuleID             uuid.UUID
	PersonID             uuid.NullUUID
	TeacherID            uuid.NullUUID
	Level                string
	Note                 string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	ModuleName           string
	Compulsory           bool
	SubjectGroupID       uuid.NullUUID
	SubjectGroupCode     *string
	SubjectGroupName     *string
	HolderName           string
	HolderMail           string
	HolderSortName       string
	OutsideSubjectGroups bool
}

// Competences: who can teach which module, and who would like to.
//
// # THE RULE THIS FILE IS MADE OF
//
// Every SELECT that returns rows about other people carries the same four filter parameters, the
// way wish.sql does, and for the same reason: WOULD_LIKE is a wish without a semester, and a query
// written without the predicate is not a slow query, it is a leak.
//
//	@scope = 'all'            no restriction
//	@scope = 'own'            the caller's own entries
//	@scope = 'own_or_scoped'  their own, plus the modules of the programmes and subject groups
//	                          they lead
//	anything else             nothing at all
//
// The programme of a competence is the module's HOME programme. A competence has no instance and
// therefore no demanding programme; the home programme is the one responsible for the module.
//
// The three aggregates at the end are not filtered by that predicate, and
// store.TestEveryCompetenceQueryIsFiltered knows them by name: the first counts only the caller's
// own rows, the other two are refused in internal/domain unless the caller may read the whole
// subject group they count over. That is the same rule applied before the query instead of inside
// it — acceptable exactly because the answer is about one group the caller either reaches or not.
// The competences the filter allows, narrowed by whatever the caller asked for.
// The examination office's short name for a holder who has an account, as in assignment.sql.
func (q *Queries) Competences(ctx context.Context, arg CompetencesParams) ([]CompetencesRow, error) {
	rows, err := q.db.Query(ctx, competences,
		arg.Module,
		arg.SubjectGroup,
		arg.Person,
		arg.Teacher,
		arg.Scope,
		arg.OwnerID,
		arg.ProgrammeIds,
		arg.SubjectGroupIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CompetencesRow{}
	for rows.Next() {
		var i CompetencesRow
		if err := rows.Scan(
			&i.ID,
			&i.ModuleID,
			&i.PersonID,
			&i.TeacherID,
			&i.Level,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ModuleName,
			&i.Compulsory,
			&i.SubjectGroupID,
			&i.SubjectGroupCode,
			&i.SubjectGroupName,
			&i.HolderName,
			&i.HolderMail,
			&i.HolderSortName,
			&i.OutsideSubjectGroups,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteOwnCompetence = `-- name: DeleteOwnCompetence :execrows
DELETE FROM competence WHERE id = $1::uuid AND person_id = $2::uuid
`

type DeleteOwnCompetenceParams struct {
	ID       uuid.UUID
	PersonID uuid.UUID
}

// Withdraw one's own. Ownership in the WHERE clause, as DeleteOwnWish does: "not there" and "not
// yours" are the same empty result.
func (q *Queries) DeleteOwnCompetence(ctx context.Context, arg DeleteOwnCompetenceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOwnCompetence, arg.ID, arg.PersonID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTeacherCompetence = `-- name: DeleteTeacherCompetence :execrows
DELETE FROM competence WHERE id = $1::uuid AND teacher_id IS NOT NULL
`

// Withdraw a teacher row. Only teacher rows: a person's statement is removed by that person.
func (q *Queries) DeleteTeacherCompetence(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTeacherCompetence, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const memberCompulsoryCounts = `-- name: MemberCompulsoryCounts :many
SELECT
    person.id, person.name, person.mail::text AS mail,
    COALESCE(t.short_name, '')::text AS sort_name,
    (SELECT COUNT(*) FROM competence c
       JOIN module_subject_group msg ON msg.module_id = c.module_id
       JOIN module m ON m.id = c.module_id
      WHERE c.person_id = person.id
        AND msg.subject_group_id = psg.subject_group_id
        AND c.level = 'CAN_TEACH'
        AND m.active AND m.retired_at IS NULL
        AND EXISTS (SELECT 1 FROM module_offering o WHERE o.module_id = m.id AND o.is_duty)
    )::int AS can_teach_compulsory
FROM person_subject_group psg
JOIN person ON person.id = psg.person_id
LEFT JOIN teacher t ON t.mail = person.mail
WHERE psg.subject_group_id = $1::uuid
  AND person.active
ORDER BY COALESCE(NULLIF(t.short_name, ''), person.name), person.id
`

type MemberCompulsoryCountsRow struct {
	ID                 uuid.UUID
	Name               string
	Mail               string
	SortName           string
	CanTeachCompulsory int32
}

// For one subject group: every member and how many of its compulsory modules they can teach.
// Refused in internal/domain unless the caller may read every competence in the group.
func (q *Queries) MemberCompulsoryCounts(ctx context.Context, subjectGroupID uuid.UUID) ([]MemberCompulsoryCountsRow, error) {
	rows, err := q.db.Query(ctx, memberCompulsoryCounts, subjectGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MemberCompulsoryCountsRow{}
	for rows.Next() {
		var i MemberCompulsoryCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Mail,
			&i.SortName,
			&i.CanTeachCompulsory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const modulesWithoutCompetence = `-- name: ModulesWithoutCompetence :many
SELECT m.id, m.name,
       EXISTS (SELECT 1 FROM module_offering o WHERE o.module_id = m.id AND o.is_duty) AS compulsory
FROM module_subject_group msg
JOIN module m ON m.id = msg.module_id
WHERE msg.subject_group_id = $1::uuid
  AND m.active AND m.retired_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM competence c WHERE c.module_id = m.id AND c.level = 'CAN_TEACH'
  )
ORDER BY (m.name = ''), m.name, m.id
`

type ModulesWithoutCompetenceRow struct {
	ID         uuid.UUID
	Name       string
	Compulsory bool
}

// The active modules of one subject group that nobody has said they can teach — "wenn es brennt,
// kann es niemand". Refused in internal/domain on the same terms as the query above.
func (q *Queries) ModulesWithoutCompetence(ctx context.Context, subjectGroupID uuid.UUID) ([]ModulesWithoutCompetenceRow, error) {
	rows, err := q.db.Query(ctx, modulesWithoutCompetence, subjectGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModulesWithoutCompetenceRow{}
	for rows.Next() {
		var i ModulesWithoutCompetenceRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Compulsory); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ownCompulsoryCounts = `-- name: OwnCompulsoryCounts :many
SELECT
    sg.id, sg.code, sg.name,
    COUNT(c.id)::int AS can_teach_compulsory
FROM person_subject_group psg
JOIN subject_group sg ON sg.id = psg.subject_group_id
LEFT JOIN module_subject_group msg ON msg.subject_group_id = sg.id
LEFT JOIN module m ON m.id = msg.module_id
LEFT JOIN competence c ON c.module_id = m.id
    AND c.person_id = psg.person_id
    AND c.level = 'CAN_TEACH'
    AND m.active AND m.retired_at IS NULL
    AND EXISTS (SELECT 1 FROM module_offering o WHERE o.module_id = m.id AND o.is_duty)
WHERE psg.person_id = $1::uuid
  AND sg.active
GROUP BY sg.id, sg.code, sg.name
ORDER BY sg.name, sg.id
`

type OwnCompulsoryCountsRow struct {
	ID                 uuid.UUID
	Code               string
	Name               string
	CanTeachCompulsory int32
}

// For each subject group the caller is in: how many of its compulsory modules the caller has
// stated they can teach. Only the caller's own rows are counted — the answer is their own number.
func (q *Queries) OwnCompulsoryCounts(ctx context.Context, personID uuid.UUID) ([]OwnCompulsoryCountsRow, error) {
	rows, err := q.db.Query(ctx, ownCompulsoryCounts, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OwnCompulsoryCountsRow{}
	for rows.Next() {
		var i OwnCompulsoryCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.CanTeachCompulsory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const teacherCompetenceContext = `-- name: TeacherCompetenceContext :one
SELECT c.id, msg.subject_group_id
FROM competence c
LEFT JOIN module_subject_group msg ON msg.module_id = c.module_id
WHERE c.id = $1::uuid AND c.teacher_id IS NOT NULL
`

type TeacherCompetenceContextRow struct {
	ID             uuid.UUID
	SubjectGroupID uuid.NullUUID
}

// The subject group of a teacher row's module, for the guard on removing it. No row for an id that
// is not a teacher row.
func (q *Queries) TeacherCompetenceContext(ctx context.Context, id uuid.UUID) (TeacherCompetenceContextRow, error) {
	row := q.db.QueryRow(ctx, teacherCompetenceContext, id)
	var i TeacherCompetenceContextRow
	err := row.Scan(&i.ID, &i.SubjectGroupID)
	return i, err
}

const upsertOwnCompetence = `-- name: UpsertOwnCompetence :one
INSERT INTO competence (module_id, person_id, level, note, entered_by)
VALUES ($1::uuid, $2::uuid, $3::text,
        $4::text, $2::uuid)
ON CONFLICT (person_id, module_id) WHERE person_id IS NOT NULL DO UPDATE
SET level = EXCLUDED.level,
    note = EXCLUDED.note,
    updated_at = now()
RETURNING id
`

type UpsertOwnCompetenceParams struct {
	ModuleID uuid.UUID
	PersonID uuid.UUID
	Level    string
	Note     string
}

// State one's own competence for a module, or change it. person_id and entered_by are both the
// caller, and the CHECK says they have to be.
func (q *Queries) UpsertOwnCompetence(ctx context.Context, arg UpsertOwnCompetenceParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertOwnCompetence,
		arg.ModuleID,
		arg.PersonID,
		arg.Level,
		arg.Note,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertTeacherCompetence = `-- name: UpsertTeacherCompetence :one
INSERT INTO competence (module_id, teacher_id, level, note, entered_by)
VALUES ($1::uuid, $2::uuid, $3::text,
        $4::text, $5::uuid)
ON CONFLICT (teacher_id, module_id) WHERE teacher_id IS NOT NULL DO UPDATE
SET level = EXCLUDED.level,
    note = EXCLUDED.note,
    entered_by = EXCLUDED.entered_by,
    updated_at = now()
RETURNING id
`

type UpsertTeacherCompetenceParams struct {
	ModuleID  uuid.UUID
	TeacherID uuid.UUID
	Level     string
	Note      string
	EnteredBy uuid.UUID
}

// State a teacher's competence on their behalf — only for somebody without an account, which
// internal/domain makes sure of. entered_by moves to whoever changed it last.
func (q *Queries) UpsertTeacherCompetence(ctx context.Context, arg UpsertTeacherCompetenceParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertTeacherCompetence,
		arg.ModuleID,
		arg.TeacherID,
		arg.Level,
		arg.Note,
		arg.EnteredBy,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
