// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package store

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CourseInstance struct {
	ID                uuid.UUID
	SemesterID        uuid.UUID
	ModuleID          uuid.UUID
	ProgrammeID       uuid.UUID
	Track             string
	ProgrammeSemester *int32
	CreatedBy         uuid.NullUUID
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type InstancePart struct {
	ID                  uuid.UUID
	CourseInstanceID    uuid.UUID
	Kind                string
	Position            int32
	TeachingHours       pgtype.Numeric
	ServesSiblingTracks bool
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type Module struct {
	ID                   uuid.UUID
	HomeProgrammeID      uuid.UUID
	Name                 string
	CourseType           string
	CourseTypeSource     string
	Frequency            string
	FrequencySource      string
	ContactHoursPerWeek  *int32
	Credits              *int32
	Active               bool
	Official             bool
	RetiredAt            pgtype.Timestamptz
	ZpaModuleRef         *int64
	CreatedAt            time.Time
	UpdatedAt            time.Time
	ResponsibleTeacherID uuid.NullUUID
}

type ModuleComponent struct {
	ID            uuid.UUID
	ModuleID      uuid.UUID
	Kind          string
	TeachingHours pgtype.Numeric
	Position      int32
	CreatedBy     uuid.NullUUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type ModuleOffering struct {
	ID                   uuid.UUID
	ModuleID             uuid.UUID
	SpoID                uuid.UUID
	IsDuty               bool
	ModuleCodes          []string
	Focuses              []string
	MinProgrammeSemester *int32
	SourceRows           int32
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type Person struct {
	ID        uuid.UUID
	Mail      string
	Name      string
	Active    bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type PersonProgrammeScope struct {
	PersonID    uuid.UUID
	Role        string
	ProgrammeID uuid.UUID
	GrantedAt   time.Time
	GrantedBy   uuid.NullUUID
}

type PersonRole struct {
	PersonID  uuid.UUID
	Role      string
	GrantedAt time.Time
	GrantedBy uuid.NullUUID
	// When this grant stops taking effect. NULL means it does not expire. An expired row is kept rather than deleted: it is the record that the grant was held, which is exactly what the audit question "who could see this in October" needs.
	ExpiresAt pgtype.Timestamptz
}

type PersonalAccessToken struct {
	TokenID     string
	OwnerID     uuid.UUID
	SecretHash  []byte
	Description string
	Scopes      []string
	CreatedAt   time.Time
	ExpiresAt   time.Time
	LastUsedAt  pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
}

type Programme struct {
	ID              uuid.UUID
	Code            string
	Title           string
	Active          bool
	ZpaProgrammeRef *int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Semester struct {
	ID                uuid.UUID
	Code              string
	Phase             string
	WishesPublishedAt pgtype.Timestamptz
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type Spo struct {
	ID          uuid.UUID
	ProgrammeID uuid.UUID
	Version     int32
	ValidFrom   pgtype.Date
	PrimussID   *string
	ZpaSpoRef   *int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Teacher struct {
	ID                   uuid.UUID
	ZpaTeacherRef        *int64
	Mail                 *string
	FullName             string
	ShortName            string
	IsProfessor          bool
	IsLecturerOnContract bool
	IsHonoraryProfessor  bool
	IsStaff              bool
	Active               bool
	Faculty              *string
	LastSemester         *string
	RetiredAt            pgtype.Timestamptz
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type ZpaBasketV struct {
	BasketID      int64
	Name          string
	IsDuty        bool
	FocusID       int64
	FocusShort    string
	Focus         string
	Present       interface{}
	LastChangedAt time.Time
}

type ZpaCatalogueProjection struct {
	ID                uuid.UUID
	RunID             uuid.NullUUID
	StartedAt         time.Time
	FinishedAt        pgtype.Timestamptz
	Status            string
	ProgrammesWritten int32
	ModulesWritten    int32
	OfferingsWritten  int32
	OfferingsRemoved  int32
	Error             *string
	TeachersWritten   int32
}

type ZpaCatalogueProjectionNote struct {
	ProjectionID uuid.UUID
	Code         string
	Count        int32
	Sample       []string
}

type ZpaChange struct {
	ID            uuid.UUID
	RunID         uuid.UUID
	ObjectID      uuid.UUID
	Kind          string
	ZpaID         int64
	Label         *string
	Change        string
	PayloadBefore []byte
	PayloadAfter  []byte
	ChangedKeys   []string
	DetectedAt    time.Time
}

type ZpaModuleV struct {
	ModuleID        int64
	Name            string
	HomeProgramme   string
	CourseType      string
	Sws             int32
	Credits         int32
	Active          bool
	Official        bool
	RepeaterExam    bool
	Responsible     string
	Frequency       string
	Languages       string
	DefaultLanguage string
	Present         interface{}
	LastChangedAt   time.Time
}

type ZpaMsbaV struct {
	MsbaID               int64
	ModuleID             int64
	ModuleName           string
	SpoID                int64
	SpoVersion           int32
	SpoValidFrom         pgtype.Date
	BasketID             int64
	BasketName           string
	ModuleCode           string
	MinProgrammeSemester int32
	ExamTypeCount        int32
	Present              interface{}
	LastChangedAt        time.Time
}

type ZpaObject struct {
	ID            uuid.UUID
	Kind          string
	ZpaID         int64
	Payload       []byte
	ContentHash   *string
	Label         *string
	FirstSeenAt   time.Time
	LastSeenAt    time.Time
	LastChangedAt time.Time
	GoneAt        pgtype.Timestamptz
}

type ZpaSpoV struct {
	SpoID         int64
	Version       int32
	ValidFrom     pgtype.Date
	PrimussID     string
	ProgrammeID   int64
	Programme     string
	Present       interface{}
	LastChangedAt time.Time
}

type ZpaSyncRun struct {
	ID          uuid.UUID
	Trigger     string
	StartedBy   uuid.NullUUID
	StartedAt   time.Time
	FinishedAt  pgtype.Timestamptz
	Status      string
	Fetched     int32
	Appeared    int32
	Changed     int32
	Disappeared int32
	Error       *string
}

type ZpaSyncRunKind struct {
	RunID   uuid.UUID
	Kind    string
	Status  string
	Fetched int32
	Error   *string
}

type ZpaTeacherV struct {
	TeacherID            int64
	Mail                 string
	FullName             string
	ShortName            string
	IsProfessor          bool
	IsLecturerOnContract bool
	IsHonoraryProfessor  bool
	IsStaff              bool
	Active               bool
	Faculty              string
	LastSemester         interface{}
	Present              interface{}
	LastChangedAt        time.Time
}
