// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: module.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertModuleComponent = `-- name: InsertModuleComponent :exec
INSERT INTO module_component (module_id, kind, teaching_hours, position, created_by)
VALUES ($1, $2, $3, $4, $5)
`

type InsertModuleComponentParams struct {
	ModuleID      uuid.UUID
	Kind          string
	TeachingHours pgtype.Numeric
	Position      int32
	CreatedBy     uuid.NullUUID
}

func (q *Queries) InsertModuleComponent(ctx context.Context, arg InsertModuleComponentParams) error {
	_, err := q.db.Exec(ctx, insertModuleComponent,
		arg.ModuleID,
		arg.Kind,
		arg.TeachingHours,
		arg.Position,
		arg.CreatedBy,
	)
	return err
}

const listModules = `-- name: ListModules :many
SELECT m.id, m.name, m.home_programme_id, m.responsible_teacher_id, m.course_type, m.frequency,
       m.contact_hours_per_week, m.credits, m.active, m.official, m.retired_at, m.zpa_module_ref
FROM module m
WHERE ($1::uuid IS NULL
       OR m.responsible_teacher_id = $1::uuid)
  AND ($2::text IS NULL
       OR EXISTS (SELECT 1 FROM programme hp
                   WHERE hp.id = m.home_programme_id AND hp.code = $2::text)
       OR EXISTS (SELECT 1
                    FROM module_offering o
                    JOIN spo s ON s.id = o.spo_id
                    JOIN programme p ON p.id = s.programme_id
                   WHERE o.module_id = m.id
                     AND p.code = $2::text
                     AND ($3::uuid IS NULL OR s.id = $3::uuid)))
  -- Narrowing to one version without naming a programme still means "counts in this version".
  AND ($3::uuid IS NULL
       OR EXISTS (SELECT 1 FROM module_offering o
                   WHERE o.module_id = m.id AND o.spo_id = $3::uuid))
  AND ($4::boolean
       OR m.frequency = ANY ($5::text[]))
  AND ($6::text IS NULL OR $2::text IS NULL
       OR (SELECT CASE
                      WHEN bool_and(o.is_duty) THEN 'COMPULSORY'
                      WHEN bool_or(o.is_duty) THEN 'MIXED'
                      ELSE 'ELECTIVE'
                  END
             FROM module_offering o
             JOIN spo s ON s.id = o.spo_id
             JOIN programme p ON p.id = s.programme_id
            WHERE o.module_id = m.id
              AND p.code = $2::text
              AND ($3::uuid IS NULL OR s.id = $3::uuid)
          ) = $6::text)
  AND ($7::text IS NULL
       OR m.name ILIKE '%' || $7::text || '%'
       OR EXISTS (SELECT 1 FROM module_offering o
                   WHERE o.module_id = m.id
                     AND array_to_string(o.module_codes, ' ')
                         ILIKE '%' || $7::text || '%'))
  AND ($8::boolean OR (m.active AND m.retired_at IS NULL))
  AND (NOT $9::boolean
       OR NOT EXISTS (SELECT 1 FROM module_component c WHERE c.module_id = m.id))
ORDER BY (m.name = ''), m.name, m.id
`

type ListModulesParams struct {
	Responsible       uuid.NullUUID
	Programme         *string
	Spo               uuid.NullUUID
	AnyFrequency      bool
	Frequencies       []string
	Duty              *string
	Search            *string
	IncludeInactive   bool
	WithoutComponents bool
}

type ListModulesRow struct {
	ID                   uuid.UUID
	Name                 string
	HomeProgrammeID      uuid.UUID
	ResponsibleTeacherID uuid.NullUUID
	CourseType           string
	Frequency            string
	ContactHoursPerWeek  *int32
	Credits              *int32
	Active               bool
	Official             bool
	RetiredAt            pgtype.Timestamptz
	ZpaModuleRef         *int64
}

// The catalogue, filtered.
//
// The programme filter is a union of two conditions and the second is not redundant: a module
// counts in one of the programme's sets of regulations, OR the programme is its home. Measured
// against the real catalogue, 26 active modules are reachable only through the second half, ten
// of them in the largest programme — and the first thing a programme lead does is look for a
// module they are responsible for.
//
// The duty filter is applied through the same subquery rather than beside it, so that
// "compulsory in this programme" cannot accidentally mean "compulsory anywhere". MIXED is
// expressed as "has both", which is what makes it a filter rather than a label.
// A module with no name sorts last rather than first: the empty string would otherwise put the
// handful of nameless ones at the top of every list in the system.
func (q *Queries) ListModules(ctx context.Context, arg ListModulesParams) ([]ListModulesRow, error) {
	rows, err := q.db.Query(ctx, listModules,
		arg.Responsible,
		arg.Programme,
		arg.Spo,
		arg.AnyFrequency,
		arg.Frequencies,
		arg.Duty,
		arg.Search,
		arg.IncludeInactive,
		arg.WithoutComponents,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListModulesRow{}
	for rows.Next() {
		var i ListModulesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.HomeProgrammeID,
			&i.ResponsibleTeacherID,
			&i.CourseType,
			&i.Frequency,
			&i.ContactHoursPerWeek,
			&i.Credits,
			&i.Active,
			&i.Official,
			&i.RetiredAt,
			&i.ZpaModuleRef,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgrammes = `-- name: ListProgrammes :many

SELECT id, code, title, active
FROM programme
ORDER BY code
`

type ListProgrammesRow struct {
	ID     uuid.UUID
	Code   string
	Title  string
	Active bool
}

// Reading the module catalogue.
//
// The shape of this file is set by one decision: a list of modules is loaded in a fixed number
// of statements rather than one per row. Four for a filtered list — the modules, their
// components, their offerings, and the programmes — stitched together in Go. The catalogue is
// 506 modules and 1784 offerings, so loading what a screen needs and joining it in memory is
// both simpler than a loader framework and faster than the query-per-field it replaces.
// Every study programme, including the one with no current regulations.
//
// Ordered by code, which is how the faculty says them and how a picker should show them.
func (q *Queries) ListProgrammes(ctx context.Context) ([]ListProgrammesRow, error) {
	rows, err := q.db.Query(ctx, listProgrammes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProgrammesRow{}
	for rows.Next() {
		var i ListProgrammesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Title,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpos = `-- name: ListSpos :many
SELECT s.id, s.programme_id, s.version, s.valid_from, s.primuss_id, p.code AS programme_code
FROM spo s
JOIN programme p ON p.id = s.programme_id
ORDER BY p.code, s.version DESC
`

type ListSposRow struct {
	ID            uuid.UUID
	ProgrammeID   uuid.UUID
	Version       int32
	ValidFrom     pgtype.Date
	PrimussID     *string
	ProgrammeCode string
}

// Every version of every programme's regulations, newest first within a programme.
//
// Loaded whole rather than per programme: 29 rows, and every screen that shows one programme's
// versions also has the others in a picker beside it.
func (q *Queries) ListSpos(ctx context.Context) ([]ListSposRow, error) {
	rows, err := q.db.Query(ctx, listSpos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSposRow{}
	for rows.Next() {
		var i ListSposRow
		if err := rows.Scan(
			&i.ID,
			&i.ProgrammeID,
			&i.Version,
			&i.ValidFrom,
			&i.PrimussID,
			&i.ProgrammeCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeachers = `-- name: ListTeachers :many
SELECT t.id, COALESCE(t.mail::text, '')::text AS mail, t.full_name, t.short_name,
       t.is_professor, t.is_lecturer_on_contract, t.is_honorary_professor, t.is_staff,
       t.active, t.faculty, t.last_semester,
       (p.id IS NOT NULL)::boolean AS is_user
FROM teacher t
LEFT JOIN person p ON p.mail = t.mail
WHERE t.retired_at IS NULL
  AND ($1::boolean OR t.active)
  AND ($2::text IS NULL
       OR t.full_name ILIKE '%' || $2::text || '%'
       OR t.short_name ILIKE '%' || $2::text || '%'
       OR t.mail::text ILIKE '%' || $2::text || '%')
ORDER BY t.short_name, t.id
`

type ListTeachersParams struct {
	IncludeInactive bool
	Search          *string
}

type ListTeachersRow struct {
	ID                   uuid.UUID
	Mail                 string
	FullName             string
	ShortName            string
	IsProfessor          bool
	IsLecturerOnContract bool
	IsHonoraryProfessor  bool
	IsStaff              bool
	Active               bool
	Faculty              *string
	LastSemester         *string
	IsUser               bool
}

// The people who teach, with whether somebody of that address may sign in here.
//
// The LEFT JOIN to person is the link between the two lists, and it is done here rather than
// stored as a column so that somebody admitted this morning is connected now rather than after
// the next import. `mail` is citext on both sides, so the casing the identity provider happens
// to use does not decide the answer.
//
// Retired teachers — ones a successful import stopped mentioning — are left out entirely,
// unlike the source's own `active` flag which is a column and a filter. The two are different
// questions: "no longer teaching" is worth seeing, "no longer published" is not.
// COALESCE, and it is not cosmetic: three of the 257 carry no address, sqlc cannot know that a
// cast is nullable, and scanning NULL into a string fails at runtime rather than at build time.
// Empty means absent, which is what the domain type says too.
func (q *Queries) ListTeachers(ctx context.Context, arg ListTeachersParams) ([]ListTeachersRow, error) {
	rows, err := q.db.Query(ctx, listTeachers, arg.IncludeInactive, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeachersRow{}
	for rows.Next() {
		var i ListTeachersRow
		if err := rows.Scan(
			&i.ID,
			&i.Mail,
			&i.FullName,
			&i.ShortName,
			&i.IsProfessor,
			&i.IsLecturerOnContract,
			&i.IsHonoraryProfessor,
			&i.IsStaff,
			&i.Active,
			&i.Faculty,
			&i.LastSemester,
			&i.IsUser,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moduleByID = `-- name: ModuleByID :one
SELECT id, name, home_programme_id, responsible_teacher_id, course_type, frequency,
       contact_hours_per_week, credits, active, official, retired_at, zpa_module_ref
FROM module
WHERE id = $1
`

type ModuleByIDRow struct {
	ID                   uuid.UUID
	Name                 string
	HomeProgrammeID      uuid.UUID
	ResponsibleTeacherID uuid.NullUUID
	CourseType           string
	Frequency            string
	ContactHoursPerWeek  *int32
	Credits              *int32
	Active               bool
	Official             bool
	RetiredAt            pgtype.Timestamptz
	ZpaModuleRef         *int64
}

func (q *Queries) ModuleByID(ctx context.Context, id uuid.UUID) (ModuleByIDRow, error) {
	row := q.db.QueryRow(ctx, moduleByID, id)
	var i ModuleByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HomeProgrammeID,
		&i.ResponsibleTeacherID,
		&i.CourseType,
		&i.Frequency,
		&i.ContactHoursPerWeek,
		&i.Credits,
		&i.Active,
		&i.Official,
		&i.RetiredAt,
		&i.ZpaModuleRef,
	)
	return i, err
}

const moduleComponentsFor = `-- name: ModuleComponentsFor :many
SELECT id, module_id, kind, teaching_hours, position
FROM module_component
WHERE module_id = ANY ($1::uuid[])
ORDER BY module_id, position
`

type ModuleComponentsForRow struct {
	ID            uuid.UUID
	ModuleID      uuid.UUID
	Kind          string
	TeachingHours pgtype.Numeric
	Position      int32
}

// The splits of a set of modules, in one statement.
func (q *Queries) ModuleComponentsFor(ctx context.Context, moduleIds []uuid.UUID) ([]ModuleComponentsForRow, error) {
	rows, err := q.db.Query(ctx, moduleComponentsFor, moduleIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModuleComponentsForRow{}
	for rows.Next() {
		var i ModuleComponentsForRow
		if err := rows.Scan(
			&i.ID,
			&i.ModuleID,
			&i.Kind,
			&i.TeachingHours,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moduleOfferingsFor = `-- name: ModuleOfferingsFor :many
SELECT o.id, o.module_id, o.spo_id, o.is_duty, o.module_codes, o.focuses,
       o.min_programme_semester,
       s.version AS spo_version, s.valid_from AS spo_valid_from, s.primuss_id AS spo_primuss_id,
       p.id AS programme_id, p.code AS programme_code, p.title AS programme_title,
       p.active AS programme_active
FROM module_offering o
JOIN spo s ON s.id = o.spo_id
JOIN programme p ON p.id = s.programme_id
WHERE o.module_id = ANY ($1::uuid[])
ORDER BY o.module_id, p.code, s.version DESC
`

type ModuleOfferingsForRow struct {
	ID                   uuid.UUID
	ModuleID             uuid.UUID
	SpoID                uuid.UUID
	IsDuty               bool
	ModuleCodes          []string
	Focuses              []string
	MinProgrammeSemester *int32
	SpoVersion           int32
	SpoValidFrom         pgtype.Date
	SpoPrimussID         *string
	ProgrammeID          uuid.UUID
	ProgrammeCode        string
	ProgrammeTitle       string
	ProgrammeActive      bool
}

// Where a set of modules counts, in one statement, joined to the regulations they count in.
//
// Unfiltered by programme on purpose, even when the list was filtered by one. A module's
// offerings are what "where does this count" means, and answering it with only the programme
// somebody happened to filter by would make the same module look different depending on how it
// was found.
func (q *Queries) ModuleOfferingsFor(ctx context.Context, moduleIds []uuid.UUID) ([]ModuleOfferingsForRow, error) {
	rows, err := q.db.Query(ctx, moduleOfferingsFor, moduleIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModuleOfferingsForRow{}
	for rows.Next() {
		var i ModuleOfferingsForRow
		if err := rows.Scan(
			&i.ID,
			&i.ModuleID,
			&i.SpoID,
			&i.IsDuty,
			&i.ModuleCodes,
			&i.Focuses,
			&i.MinProgrammeSemester,
			&i.SpoVersion,
			&i.SpoValidFrom,
			&i.SpoPrimussID,
			&i.ProgrammeID,
			&i.ProgrammeCode,
			&i.ProgrammeTitle,
			&i.ProgrammeActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const programmeByCode = `-- name: ProgrammeByCode :one
SELECT id, code, title, active
FROM programme
WHERE code = $1
`

type ProgrammeByCodeRow struct {
	ID     uuid.UUID
	Code   string
	Title  string
	Active bool
}

func (q *Queries) ProgrammeByCode(ctx context.Context, code string) (ProgrammeByCodeRow, error) {
	row := q.db.QueryRow(ctx, programmeByCode, code)
	var i ProgrammeByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Title,
		&i.Active,
	)
	return i, err
}

const programmesByIDs = `-- name: ProgrammesByIDs :many
SELECT id, code, title, active
FROM programme
WHERE id = ANY ($1::uuid[])
ORDER BY code
`

type ProgrammesByIDsRow struct {
	ID     uuid.UUID
	Code   string
	Title  string
	Active bool
}

// A handful of programmes by id, without their regulations.
//
// For `me`, which has to turn the programme ids an actor carries into codes a person reads. The
// full list with its regulations attached would be two statements and 29 rows of examination
// regulations for a field that renders two letters.
func (q *Queries) ProgrammesByIDs(ctx context.Context, ids []uuid.UUID) ([]ProgrammesByIDsRow, error) {
	rows, err := q.db.Query(ctx, programmesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProgrammesByIDsRow{}
	for rows.Next() {
		var i ProgrammesByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Title,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceModuleComponents = `-- name: ReplaceModuleComponents :exec
DELETE FROM module_component WHERE module_id = $1
`

// Clear a module's split, so the caller can write the new one in the same transaction.
//
// Delete-then-insert rather than a diff, because the entries only mean anything together: what
// is being replaced is one statement about a module, not a set of independent rows. Inside a
// transaction, so nobody reads the empty moment in between.
func (q *Queries) ReplaceModuleComponents(ctx context.Context, moduleID uuid.UUID) error {
	_, err := q.db.Exec(ctx, replaceModuleComponents, moduleID)
	return err
}

const teachersByID = `-- name: TeachersByID :many
SELECT t.id, COALESCE(t.mail::text, '')::text AS mail, t.full_name, t.short_name,
       t.is_professor, t.is_lecturer_on_contract, t.is_honorary_professor, t.is_staff,
       t.active, t.faculty, t.last_semester,
       (p.id IS NOT NULL)::boolean AS is_user
FROM teacher t
LEFT JOIN person p ON p.mail = t.mail
WHERE t.id = ANY ($1::uuid[])
`

type TeachersByIDRow struct {
	ID                   uuid.UUID
	Mail                 string
	FullName             string
	ShortName            string
	IsProfessor          bool
	IsLecturerOnContract bool
	IsHonoraryProfessor  bool
	IsStaff              bool
	Active               bool
	Faculty              *string
	LastSemester         *string
	IsUser               bool
}

// A handful of teachers by id, for attaching them to the modules they are responsible for.
// COALESCE, and it is not cosmetic: three of the 257 carry no address, sqlc cannot know that a
// cast is nullable, and scanning NULL into a string fails at runtime rather than at build time.
// Empty means absent, which is what the domain type says too.
func (q *Queries) TeachersByID(ctx context.Context, ids []uuid.UUID) ([]TeachersByIDRow, error) {
	rows, err := q.db.Query(ctx, teachersByID, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeachersByIDRow{}
	for rows.Next() {
		var i TeachersByIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Mail,
			&i.FullName,
			&i.ShortName,
			&i.IsProfessor,
			&i.IsLecturerOnContract,
			&i.IsHonoraryProfessor,
			&i.IsStaff,
			&i.Active,
			&i.Faculty,
			&i.LastSemester,
			&i.IsUser,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
