// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: person.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignProgramme = `-- name: AssignProgramme :exec
INSERT INTO person_programme_scope (person_id, role, programme_id, granted_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (person_id, role, programme_id) DO NOTHING
`

type AssignProgrammeParams struct {
	PersonID    uuid.UUID
	Role        string
	ProgrammeID uuid.UUID
	GrantedBy   uuid.NullUUID
}

// Give somebody's grant one more programme.
//
// ON CONFLICT DO NOTHING rather than an error: setting the same list twice is not a mistake, and
// the caller replaces the whole set anyway. The foreign key to person_role is what refuses an
// assignment to somebody who does not hold the role — the check is the schema's, not a race
// somebody has to remember here.
func (q *Queries) AssignProgramme(ctx context.Context, arg AssignProgrammeParams) error {
	_, err := q.db.Exec(ctx, assignProgramme,
		arg.PersonID,
		arg.Role,
		arg.ProgrammeID,
		arg.GrantedBy,
	)
	return err
}

const countOtherActiveAdmins = `-- name: CountOtherActiveAdmins :one
SELECT count(*)
FROM person_role pr
JOIN person p ON p.id = pr.person_id
WHERE pr.role = 'ADMIN'
  AND p.active
  AND (pr.expires_at IS NULL OR pr.expires_at > now())
  AND pr.person_id <> $1
`

// How many people other than this one could still administer the installation.
//
// "Could still": active person, unexpired grant. A deactivated administrator and one whose
// temporary grant ran out are both people who cannot let anybody back in, and counting them
// would make the last-administrator guard pass at exactly the moment it is needed.
//
// Called under the advisory lock, never on its own.
func (q *Queries) CountOtherActiveAdmins(ctx context.Context, personID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOtherActiveAdmins, personID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPerson = `-- name: CreatePerson :one

INSERT INTO person (id, mail, name)
VALUES ($1, $2, $3)
RETURNING id, mail, name, active, created_at, updated_at
`

type CreatePersonParams struct {
	ID   uuid.UUID
	Mail string
	Name string
}

// People and their role grants.
//
// Every read that resolves an identity returns the roles with it, in one round trip. Two
// queries would mean a window in which a person exists and their grants do not, and the
// authenticator would have to decide what to do with a caller whose permissions it could not
// read — a decision with only bad answers.
//
// The expiry filter sits in the JOIN condition rather than in a WHERE clause, in every query
// below. That is not a style preference: in a LEFT JOIN, a WHERE on the right-hand table
// turns the join into an inner one, so a person whose only grant has expired would disappear
// from the list entirely instead of appearing with no roles. The version that leaks is the
// one that hides people from the administration screen.
// The id is supplied by the caller rather than defaulted, so that a fixture, a seed and an
// import can all say who they are creating before the insert happens.
func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, createPerson, arg.ID, arg.Mail, arg.Name)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.Mail,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ensurePerson = `-- name: EnsurePerson :one
INSERT INTO person (id, mail, name)
VALUES ($1, $2, $3)
ON CONFLICT (mail) DO UPDATE
SET updated_at = person.updated_at
RETURNING id, mail, name, active, created_at, updated_at
`

type EnsurePersonParams struct {
	ID   uuid.UUID
	Mail string
	Name string
}

// Get this mail address a person row, creating one if there is none.
//
// The reconciliation of the protected administrators runs through here on every start, so it
// has to be a no-op on the ordinary case. ON CONFLICT DO UPDATE rather than DO NOTHING,
// because DO NOTHING returns no row and the caller would need a second query to find the id
// of the person it just did not create.
//
// name is only written when the row is created: a person renamed through the interface, or by
// a future ZPA import, must not be renamed back on the next restart by a value somebody typed
// into a YAML file once. The DO UPDATE therefore writes a column back to itself — a true
// no-op that still produces a row to return, which DO NOTHING does not.
func (q *Queries) EnsurePerson(ctx context.Context, arg EnsurePersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, ensurePerson, arg.ID, arg.Mail, arg.Name)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.Mail,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const grantRole = `-- name: GrantRole :exec
INSERT INTO person_role (person_id, role, granted_by, expires_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (person_id, role) DO UPDATE
SET granted_by = EXCLUDED.granted_by,
    granted_at = now(),
    expires_at = EXCLUDED.expires_at
`

type GrantRoleParams struct {
	PersonID  uuid.UUID
	Role      string
	GrantedBy uuid.NullUUID
	ExpiresAt pgtype.Timestamptz
}

// Idempotent in the sense that matters: granting a role somebody already holds updates its
// expiry rather than failing, so "give me DEANS_OFFICE for another hour" is one call and not
// a read-then-write race.
//
// granted_at is refreshed with it. The row records the grant that is in force, and a
// timestamp that pointed at a superseded one would be the wrong answer to the audit question.
func (q *Queries) GrantRole(ctx context.Context, arg GrantRoleParams) error {
	_, err := q.db.Exec(ctx, grantRole,
		arg.PersonID,
		arg.Role,
		arg.GrantedBy,
		arg.ExpiresAt,
	)
	return err
}

const listPeople = `-- name: ListPeople :many
SELECT
    p.id,
    p.mail,
    p.name,
    -- Empty for everybody the examination office does not publish. The screen shows this where
    -- it has it, so that the order it sorts by is the order somebody can read.
    COALESCE(t.short_name, '')::text AS sort_name,
    p.active,
    COALESCE(
        array_agg(pr.role ORDER BY pr.role) FILTER (WHERE pr.role IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS roles,
    COALESCE((
        SELECT jsonb_agg(jsonb_build_object('role', s.role, 'programme', s.programme_id)
                         ORDER BY s.role, s.programme_id)
        FROM person_programme_scope s
        JOIN person_role r ON r.person_id = s.person_id AND r.role = s.role
        WHERE s.person_id = p.id
          AND (r.expires_at IS NULL OR r.expires_at > now())
    ), '[]'::jsonb)::jsonb AS role_scopes
FROM person p
LEFT JOIN person_role pr
    ON pr.person_id = p.id
   AND (pr.expires_at IS NULL OR pr.expires_at > now())
LEFT JOIN teacher t ON t.mail = p.mail
WHERE ($1::text IS NULL
       OR p.mail ILIKE '%' || $1::text || '%'
       OR p.name ILIKE '%' || $1::text || '%'
       OR t.short_name ILIKE '%' || $1::text || '%')
  AND ($2::boolean OR p.active)
GROUP BY p.id, t.short_name
ORDER BY COALESCE(NULLIF(t.short_name, ''), p.name), p.mail
`

type ListPeopleParams struct {
	Search          *string
	IncludeInactive bool
}

type ListPeopleRow struct {
	ID         uuid.UUID
	Mail       string
	Name       string
	SortName   string
	Active     bool
	Roles      []string
	RoleScopes []byte
}

// The administration screen: everybody, or everybody active, optionally narrowed by a
// substring of the mail address or the name.
//
// Ordered by the surname, which is why the teacher list is joined in. `person.name` is the name
// as somebody wrote it — "Prof. Dr. Vorname Nachname" — and a list sorted by that is a list
// sorted by academic title. The examination office publishes the surname-first spelling for
// everybody it knows, and joining it on the address costs nothing to keep in step: somebody
// admitted this morning sorts correctly now rather than after the next import. Whoever it does
// not know keeps their own name as the key, because the alternative is guessing which word of it
// is the surname.
//
// Then by mail, so that the order is stable between calls — an administration table whose rows
// move between reloads is one where somebody eventually clicks the wrong row. People with no
// name yet sort first, which is also where the work is.
func (q *Queries) ListPeople(ctx context.Context, arg ListPeopleParams) ([]ListPeopleRow, error) {
	rows, err := q.db.Query(ctx, listPeople, arg.Search, arg.IncludeInactive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPeopleRow{}
	for rows.Next() {
		var i ListPeopleRow
		if err := rows.Scan(
			&i.ID,
			&i.Mail,
			&i.Name,
			&i.SortName,
			&i.Active,
			&i.Roles,
			&i.RoleScopes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeacherAccounts = `-- name: ListTeacherAccounts :many
SELECT
    t.id AS teacher_id,
    COALESCE(t.mail::text, '')::text AS mail,
    t.full_name,
    t.short_name,
    t.is_professor,
    t.is_lecturer_on_contract,
    t.is_honorary_professor,
    t.is_staff,
    t.active,
    t.faculty,
    t.last_semester,
    p.id AS person_id,
    COALESCE(p.mail::text, '')::text AS person_mail,
    COALESCE(p.name, '')::text AS person_name,
    COALESCE(p.active, false)::boolean AS person_active,
    COALESCE(
        array_agg(pr.role ORDER BY pr.role) FILTER (WHERE pr.role IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS roles
FROM teacher t
LEFT JOIN person p ON p.mail = t.mail
LEFT JOIN person_role pr
    ON pr.person_id = p.id
   AND (pr.expires_at IS NULL OR pr.expires_at > now())
WHERE t.retired_at IS NULL
GROUP BY t.id, p.id
ORDER BY t.short_name, t.id
`

type ListTeacherAccountsRow struct {
	TeacherID            uuid.UUID
	Mail                 string
	FullName             string
	ShortName            string
	IsProfessor          bool
	IsLecturerOnContract bool
	IsHonoraryProfessor  bool
	IsStaff              bool
	Active               bool
	Faculty              *string
	LastSemester         *string
	PersonID             uuid.NullUUID
	PersonMail           string
	PersonName           string
	PersonActive         bool
	Roles                []string
}

// The people the examination office publishes, each with the account they have here.
//
// The same LEFT JOIN on the address that Teacher.is_user is derived from, and deliberately
// without `AND p.active`: this list is the one screen that has to tell "nobody of this address
// may sign in" apart from "somebody deactivated them", and those are two different next steps.
// person_id is what distinguishes them; the other person columns are COALESCEd because a
// LEFT JOIN makes NOT NULL columns nullable and scanning NULL into a string fails at runtime.
//
// Retired teachers — ones a successful import stopped mentioning — are left out. People the
// source marks as no longer teaching are not: five such people are still named as responsible
// for a module, and somebody who left has an account that still has to be closable.
func (q *Queries) ListTeacherAccounts(ctx context.Context) ([]ListTeacherAccountsRow, error) {
	rows, err := q.db.Query(ctx, listTeacherAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeacherAccountsRow{}
	for rows.Next() {
		var i ListTeacherAccountsRow
		if err := rows.Scan(
			&i.TeacherID,
			&i.Mail,
			&i.FullName,
			&i.ShortName,
			&i.IsProfessor,
			&i.IsLecturerOnContract,
			&i.IsHonoraryProfessor,
			&i.IsStaff,
			&i.Active,
			&i.Faculty,
			&i.LastSemester,
			&i.PersonID,
			&i.PersonMail,
			&i.PersonName,
			&i.PersonActive,
			&i.Roles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAdminGrants = `-- name: LockAdminGrants :exec
SELECT 1 FROM person_role WHERE role = 'ADMIN' FOR UPDATE
`

// Serialise every change that could remove the last administrator.
//
// The rule to protect is "at least one active person holds an unexpired ADMIN grant", and it
// is a statement about a *set* of rows. Two administrators can each check it, each see the
// other, and each commit a change that was only safe while the other did not happen — the
// textbook write skew, and here its outcome is an installation nobody can get into.
//
// A single clever statement does not fix it, because the two dangerous operations touch
// different tables: revoking ADMIN writes person_role, deactivating an administrator writes
// person. What they have in common is these rows, so both take this lock first and the second
// one waits and then re-reads.
//
// Row locks rather than an advisory lock on a constant: this is scoped to the current schema,
// which is what lets the integration tests run in parallel, and it needs no magic number that
// somebody else could pick again for something unrelated.
func (q *Queries) LockAdminGrants(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockAdminGrants)
	return err
}

const personByID = `-- name: PersonByID :one
SELECT
    p.id,
    p.mail,
    p.name,
    COALESCE(t.short_name, '')::text AS sort_name,
    p.active,
    COALESCE(
        array_agg(pr.role ORDER BY pr.role) FILTER (WHERE pr.role IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS roles,
    COALESCE((
        SELECT jsonb_agg(jsonb_build_object('role', s.role, 'programme', s.programme_id)
                         ORDER BY s.role, s.programme_id)
        FROM person_programme_scope s
        JOIN person_role r ON r.person_id = s.person_id AND r.role = s.role
        WHERE s.person_id = p.id
          AND (r.expires_at IS NULL OR r.expires_at > now())
    ), '[]'::jsonb)::jsonb AS role_scopes
FROM person p
LEFT JOIN person_role pr
    ON pr.person_id = p.id
   AND (pr.expires_at IS NULL OR pr.expires_at > now())
LEFT JOIN teacher t ON t.mail = p.mail
WHERE p.id = $1
GROUP BY p.id, t.short_name
`

type PersonByIDRow struct {
	ID         uuid.UUID
	Mail       string
	Name       string
	SortName   string
	Active     bool
	Roles      []string
	RoleScopes []byte
}

// Joined to the teacher list like ListPeople, so that one person and the list agree about the
// name a list is sorted by. Not so for PersonByMail above: that one authenticates every request
// on the browser door, and a join it has no use for does not belong on that path.
func (q *Queries) PersonByID(ctx context.Context, id uuid.UUID) (PersonByIDRow, error) {
	row := q.db.QueryRow(ctx, personByID, id)
	var i PersonByIDRow
	err := row.Scan(
		&i.ID,
		&i.Mail,
		&i.Name,
		&i.SortName,
		&i.Active,
		&i.Roles,
		&i.RoleScopes,
	)
	return i, err
}

const personByMail = `-- name: PersonByMail :one
SELECT
    p.id,
    p.mail,
    p.name,
    p.active,
    COALESCE(
        array_agg(pr.role ORDER BY pr.role) FILTER (WHERE pr.role IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS roles,
    COALESCE((
        SELECT jsonb_agg(jsonb_build_object('role', s.role, 'programme', s.programme_id)
                         ORDER BY s.role, s.programme_id)
        FROM person_programme_scope s
        JOIN person_role r ON r.person_id = s.person_id AND r.role = s.role
        WHERE s.person_id = p.id
          AND (r.expires_at IS NULL OR r.expires_at > now())
    ), '[]'::jsonb)::jsonb AS role_scopes  -- cast: without it sqlc types the column interface{}
FROM person p
LEFT JOIN person_role pr
    ON pr.person_id = p.id
   AND (pr.expires_at IS NULL OR pr.expires_at > now())
WHERE p.mail = $1
GROUP BY p.id
`

type PersonByMailRow struct {
	ID         uuid.UUID
	Mail       string
	Name       string
	Active     bool
	Roles      []string
	RoleScopes []byte
}

// The authentication query of the browser door. mail is citext, so the comparison is
// case-insensitive without a lower() that would defeat the unique index.
//
// role_scopes carries the grants that name a thing as well as an action — leading *one* study
// programme rather than leading in general. A correlated subquery rather than a second LEFT
// JOIN, because joining two one-to-many tables in one SELECT multiplies their rows and the
// roles array would repeat every role once per scope.
//
// It applies the same expiry filter as the roles above, for the same reason: a grant the
// database considers over must not still take effect, and a scope belonging to an expired grant
// is exactly that. The composite foreign key means a scope cannot outlive a *revoked* grant;
// this covers the one that merely ran out.
func (q *Queries) PersonByMail(ctx context.Context, mail string) (PersonByMailRow, error) {
	row := q.db.QueryRow(ctx, personByMail, mail)
	var i PersonByMailRow
	err := row.Scan(
		&i.ID,
		&i.Mail,
		&i.Name,
		&i.Active,
		&i.Roles,
		&i.RoleScopes,
	)
	return i, err
}

const programmeScopesFor = `-- name: ProgrammeScopesFor :many
SELECT s.person_id, s.role, p.id AS programme_id, p.code, p.title, p.active
FROM person_programme_scope s
JOIN programme p ON p.id = s.programme_id
JOIN person_role r ON r.person_id = s.person_id AND r.role = s.role
WHERE s.person_id = ANY ($1::uuid[])
  AND (r.expires_at IS NULL OR r.expires_at > now())
ORDER BY s.person_id, p.code
`

type ProgrammeScopesForRow struct {
	PersonID    uuid.UUID
	Role        string
	ProgrammeID uuid.UUID
	Code        string
	Title       string
	Active      bool
}

// Which study programmes a set of people lead.
//
// For a list of people in one statement rather than one per row, the same shape the catalogue
// uses. Joined through person_role with the expiry filter, so a grant the database considers
// over carries no programmes — the composite foreign key covers a revoked grant, and this covers
// one that merely ran out.
func (q *Queries) ProgrammeScopesFor(ctx context.Context, personIds []uuid.UUID) ([]ProgrammeScopesForRow, error) {
	rows, err := q.db.Query(ctx, programmeScopesFor, personIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProgrammeScopesForRow{}
	for rows.Next() {
		var i ProgrammeScopesForRow
		if err := rows.Scan(
			&i.PersonID,
			&i.Role,
			&i.ProgrammeID,
			&i.Code,
			&i.Title,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeRole = `-- name: RevokeRole :exec
DELETE FROM person_role
WHERE person_id = $1 AND role = $2
`

type RevokeRoleParams struct {
	PersonID uuid.UUID
	Role     string
}

func (q *Queries) RevokeRole(ctx context.Context, arg RevokeRoleParams) error {
	_, err := q.db.Exec(ctx, revokeRole, arg.PersonID, arg.Role)
	return err
}

const roleGrantsByPerson = `-- name: RoleGrantsByPerson :many
SELECT
    pr.role,
    pr.granted_at,
    pr.granted_by,
    pr.expires_at
FROM person_role pr
WHERE pr.person_id = $1
ORDER BY pr.role
`

type RoleGrantsByPersonRow struct {
	Role      string
	GrantedAt time.Time
	GrantedBy uuid.NullUUID
	ExpiresAt pgtype.Timestamptz
}

// One person's grants as they actually are, expired ones included.
//
// Deliberately not filtered: this is the detail view, and "DEANS_OFFICE, granted on Tuesday
// by X, expired on Wednesday" is the answer to the only question this table gets asked —
// who could see what, when. The permission lookups above are the ones that filter.
func (q *Queries) RoleGrantsByPerson(ctx context.Context, personID uuid.UUID) ([]RoleGrantsByPersonRow, error) {
	rows, err := q.db.Query(ctx, roleGrantsByPerson, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoleGrantsByPersonRow{}
	for rows.Next() {
		var i RoleGrantsByPersonRow
		if err := rows.Scan(
			&i.Role,
			&i.GrantedAt,
			&i.GrantedBy,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPersonActive = `-- name: SetPersonActive :exec
UPDATE person
SET active = $2,
    updated_at = now()
WHERE id = $1
`

type SetPersonActiveParams struct {
	ID     uuid.UUID
	Active bool
}

// Deactivation is how a leaver loses access to everything at once, tokens included.
//
// The guard against deactivating the last administrator is not here. It cannot be: it depends
// on a count over other rows, and a single statement that read that count would still race
// with a concurrent deactivation. internal/store takes an advisory lock and checks first —
// see AdminGrantLockKey.
func (q *Queries) SetPersonActive(ctx context.Context, arg SetPersonActiveParams) error {
	_, err := q.db.Exec(ctx, setPersonActive, arg.ID, arg.Active)
	return err
}

const setPersonName = `-- name: SetPersonName :exec
UPDATE person
SET name = $2,
    updated_at = now()
WHERE id = $1
`

type SetPersonNameParams struct {
	ID   uuid.UUID
	Name string
}

// Renaming somebody. Separate from the role and activity paths because it is the one edit
// here that is not a permission change, and mixing it in would make every rename look like
// one in the audit log.
func (q *Queries) SetPersonName(ctx context.Context, arg SetPersonNameParams) error {
	_, err := q.db.Exec(ctx, setPersonName, arg.ID, arg.Name)
	return err
}

const teacherAccountByID = `-- name: TeacherAccountByID :one
SELECT
    t.id AS teacher_id,
    COALESCE(t.mail::text, '')::text AS mail,
    t.full_name,
    t.short_name,
    t.is_professor,
    t.is_lecturer_on_contract,
    t.is_honorary_professor,
    t.is_staff,
    t.active,
    t.faculty,
    t.last_semester,
    p.id AS person_id,
    COALESCE(p.mail::text, '')::text AS person_mail,
    COALESCE(p.name, '')::text AS person_name,
    COALESCE(p.active, false)::boolean AS person_active,
    COALESCE(
        array_agg(pr.role ORDER BY pr.role) FILTER (WHERE pr.role IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS roles
FROM teacher t
LEFT JOIN person p ON p.mail = t.mail
LEFT JOIN person_role pr
    ON pr.person_id = p.id
   AND (pr.expires_at IS NULL OR pr.expires_at > now())
WHERE t.id = $1::uuid
GROUP BY t.id, p.id
`

type TeacherAccountByIDRow struct {
	TeacherID            uuid.UUID
	Mail                 string
	FullName             string
	ShortName            string
	IsProfessor          bool
	IsLecturerOnContract bool
	IsHonoraryProfessor  bool
	IsStaff              bool
	Active               bool
	Faculty              *string
	LastSemester         *string
	PersonID             uuid.NullUUID
	PersonMail           string
	PersonName           string
	PersonActive         bool
	Roles                []string
}

// One teacher and their account, by teacher id.
//
// No retired filter, unlike the list above. The id always comes from that list, so the only way
// to be here with a retired teacher is that the import withdrew them between the screen loading
// and somebody clicking — and answering "no such teacher" to a change that has already been
// written would be a worse answer than the truth.
func (q *Queries) TeacherAccountByID(ctx context.Context, teacherID uuid.UUID) (TeacherAccountByIDRow, error) {
	row := q.db.QueryRow(ctx, teacherAccountByID, teacherID)
	var i TeacherAccountByIDRow
	err := row.Scan(
		&i.TeacherID,
		&i.Mail,
		&i.FullName,
		&i.ShortName,
		&i.IsProfessor,
		&i.IsLecturerOnContract,
		&i.IsHonoraryProfessor,
		&i.IsStaff,
		&i.Active,
		&i.Faculty,
		&i.LastSemester,
		&i.PersonID,
		&i.PersonMail,
		&i.PersonName,
		&i.PersonActive,
		&i.Roles,
	)
	return i, err
}

const unassignProgrammes = `-- name: UnassignProgrammes :exec
DELETE FROM person_programme_scope WHERE person_id = $1 AND role = $2
`

type UnassignProgrammesParams struct {
	PersonID uuid.UUID
	Role     string
}

// Take away every programme of one grant, so the caller can write the new set in the same
// transaction.
//
// Delete-then-insert rather than a diff: what is being replaced is one statement about who leads
// what, and inside a transaction nobody reads the empty moment in between.
func (q *Queries) UnassignProgrammes(ctx context.Context, arg UnassignProgrammesParams) error {
	_, err := q.db.Exec(ctx, unassignProgrammes, arg.PersonID, arg.Role)
	return err
}
