// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: planning_marks.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const announceDemandComplete = `-- name: AnnounceDemandComplete :one
INSERT INTO demand_completion (semester_id, programme_id, completed_by)
SELECT s.id, pr.id, $1::uuid
  FROM semester s, programme pr
 WHERE s.code = $2::text AND pr.code = $3::text
ON CONFLICT (semester_id, programme_id) DO UPDATE
   SET completed_at = now(), completed_by = EXCLUDED.completed_by
RETURNING semester_id, programme_id, completed_at, completed_by
`

type AnnounceDemandCompleteParams struct {
	CompletedBy uuid.NullUUID
	Semester    string
	Programme   string
}

// Announce, or re-announce after adding something.
//
// ON CONFLICT DO UPDATE and not DO NOTHING: re-announcing is the ordinary act after a late
// instance, and what it moves is the timestamp — a reader wants to know how fresh the statement
// is, not when it was first made. That is the opposite of the publication marks, which keep their
// first timestamp because they record an irreversible event.
func (q *Queries) AnnounceDemandComplete(ctx context.Context, arg AnnounceDemandCompleteParams) (DemandCompletion, error) {
	row := q.db.QueryRow(ctx, announceDemandComplete, arg.CompletedBy, arg.Semester, arg.Programme)
	var i DemandCompletion
	err := row.Scan(
		&i.SemesterID,
		&i.ProgrammeID,
		&i.CompletedAt,
		&i.CompletedBy,
	)
	return i, err
}

const demandCompletionsOfSemester = `-- name: DemandCompletionsOfSemester :many

SELECT dc.semester_id, dc.programme_id, dc.completed_at, dc.completed_by,
       prog.code AS programme_code, prog.title AS programme_title
FROM demand_completion dc
JOIN programme prog ON prog.id = dc.programme_id
JOIN semester s ON s.id = dc.semester_id
WHERE s.code = $1::text
ORDER BY prog.code
`

type DemandCompletionsOfSemesterRow struct {
	SemesterID     uuid.UUID
	ProgrammeID    uuid.UUID
	CompletedAt    time.Time
	CompletedBy    uuid.NullUUID
	ProgrammeCode  string
	ProgrammeTitle string
}

// What opens and closes the planning, at the grain the planning actually happens in.
//
// Named marks and not windows, and that is not a matter of taste: sqlc names the generated file
// after this one, and Go reads `planning_windows.sql.go` as a file that only builds on Windows —
// the GOOS suffix is matched before the `.sql.go` extension is stripped. The package compiled,
// the queries were simply absent, and the error pointed at querier.go.
//
// Two tables, two shapes, and the difference is the point (see migration 18):
// demand_completion is an announcement that blocks nothing, wish_window is a door.
//
// Neither is filtered by a visibility rule. Both are facts about the *process* rather than about
// people: which programmes have settled their demand and which subjects are taking entries is
// exactly what a colleague needs to know to do their part, and hiding it would produce a tool
// that refuses writes without saying why.
// Which study programmes have announced their demand as settled, for one semester.
func (q *Queries) DemandCompletionsOfSemester(ctx context.Context, semester string) ([]DemandCompletionsOfSemesterRow, error) {
	rows, err := q.db.Query(ctx, demandCompletionsOfSemester, semester)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DemandCompletionsOfSemesterRow{}
	for rows.Next() {
		var i DemandCompletionsOfSemesterRow
		if err := rows.Scan(
			&i.SemesterID,
			&i.ProgrammeID,
			&i.CompletedAt,
			&i.CompletedBy,
			&i.ProgrammeCode,
			&i.ProgrammeTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const programmeIDByCode = `-- name: ProgrammeIDByCode :one
SELECT id FROM programme WHERE code = $1::text
`

// The id behind a code somebody named. For the permission check, which asks about ids.
func (q *Queries) ProgrammeIDByCode(ctx context.Context, code string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, programmeIDByCode, code)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const setWishWindow = `-- name: SetWishWindow :one
INSERT INTO wish_window (semester_id, subject_group_id, open, changed_by)
SELECT s.id, $1::uuid, $2::boolean,
       $3::uuid
  FROM semester s
 WHERE s.code = $4::text
ON CONFLICT (semester_id, subject_group_id) DO UPDATE
   SET open = EXCLUDED.open, changed_at = now(), changed_by = EXCLUDED.changed_by
RETURNING semester_id, subject_group_id, open, changed_at, changed_by
`

type SetWishWindowParams struct {
	SubjectGroupID uuid.UUID
	Open           bool
	ChangedBy      uuid.NullUUID
	Semester       string
}

// Open or shut one subject group's wish round.
//
// Upsert, and the row is kept when it is opened again rather than deleted. Unlike the
// announcement above, the two states are not the same: a window that was shut and reopened means
// somebody took two decisions, and the second one is worth being able to see.
func (q *Queries) SetWishWindow(ctx context.Context, arg SetWishWindowParams) (WishWindow, error) {
	row := q.db.QueryRow(ctx, setWishWindow,
		arg.SubjectGroupID,
		arg.Open,
		arg.ChangedBy,
		arg.Semester,
	)
	var i WishWindow
	err := row.Scan(
		&i.SemesterID,
		&i.SubjectGroupID,
		&i.Open,
		&i.ChangedAt,
		&i.ChangedBy,
	)
	return i, err
}

const wishWindowsOfSemester = `-- name: WishWindowsOfSemester :many
SELECT ww.semester_id, ww.subject_group_id, ww.open, ww.changed_at, ww.changed_by,
       g.code AS subject_group_code, g.name AS subject_group_name
FROM wish_window ww
JOIN subject_group g ON g.id = ww.subject_group_id
JOIN semester s ON s.id = ww.semester_id
WHERE s.code = $1::text
ORDER BY g.code
`

type WishWindowsOfSemesterRow struct {
	SemesterID       uuid.UUID
	SubjectGroupID   uuid.UUID
	Open             bool
	ChangedAt        time.Time
	ChangedBy        uuid.NullUUID
	SubjectGroupCode string
	SubjectGroupName string
}

// The subject groups somebody has decided something about, for one semester.
//
// Only those: an absent row means open, so this list is the exceptions and not the state of every
// group. A caller that wants the state of one group asks for it and reads "open" when it is not
// here, which is what domain.WishWindowsBySubjectGroup does.
func (q *Queries) WishWindowsOfSemester(ctx context.Context, semester string) ([]WishWindowsOfSemesterRow, error) {
	rows, err := q.db.Query(ctx, wishWindowsOfSemester, semester)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WishWindowsOfSemesterRow{}
	for rows.Next() {
		var i WishWindowsOfSemesterRow
		if err := rows.Scan(
			&i.SemesterID,
			&i.SubjectGroupID,
			&i.Open,
			&i.ChangedAt,
			&i.ChangedBy,
			&i.SubjectGroupCode,
			&i.SubjectGroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const wishWriteContext = `-- name: WishWriteContext :one
SELECT s.id, s.code, s.phase, s.wishes_published_at,
       msg.subject_group_id,
       COALESCE(ww.open, true)::boolean AS wish_window_open
FROM course_instance ci
JOIN semester s ON s.id = ci.semester_id
JOIN module m ON m.id = ci.module_id
LEFT JOIN module_subject_group msg ON msg.module_id = m.id
LEFT JOIN wish_window ww
       ON ww.semester_id = s.id AND ww.subject_group_id = msg.subject_group_id
WHERE ci.id = $1::uuid
`

type WishWriteContextRow struct {
	ID                uuid.UUID
	Code              string
	Phase             string
	WishesPublishedAt pgtype.Timestamptz
	SubjectGroupID    uuid.NullUUID
	WishWindowOpen    bool
}

// Everything the wish write rule needs about one instance, in one statement.
//
// The semester decides whether anything may be written at all, and the wish window of the
// module's subject group decides whether *this* subject is taking entries. Reading them
// separately would be two round trips and two chances to decide against a state that has moved.
//
// COALESCE(ww.open, true) is the fail-open default written where it is read: a module in no
// subject group has no window, and a subject group nobody has decided anything about has no row.
// Both are open, which is the rule — closing is the intervention. See migration 18 for why this
// one direction is the opposite of every other default in the schema.
func (q *Queries) WishWriteContext(ctx context.Context, instanceID uuid.UUID) (WishWriteContextRow, error) {
	row := q.db.QueryRow(ctx, wishWriteContext, instanceID)
	var i WishWriteContextRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Phase,
		&i.WishesPublishedAt,
		&i.SubjectGroupID,
		&i.WishWindowOpen,
	)
	return i, err
}

const wishWriteContextByWishID = `-- name: WishWriteContextByWishID :one
SELECT s.id, s.code, s.phase, s.wishes_published_at,
       msg.subject_group_id,
       COALESCE(ww.open, true)::boolean AS wish_window_open
FROM wish w
JOIN course_instance ci ON ci.id = w.course_instance_id
JOIN semester s ON s.id = ci.semester_id
JOIN module m ON m.id = ci.module_id
LEFT JOIN module_subject_group msg ON msg.module_id = m.id
LEFT JOIN wish_window ww
       ON ww.semester_id = s.id AND ww.subject_group_id = msg.subject_group_id
WHERE w.id = $1::uuid
`

type WishWriteContextByWishIDRow struct {
	ID                uuid.UUID
	Code              string
	Phase             string
	WishesPublishedAt pgtype.Timestamptz
	SubjectGroupID    uuid.NullUUID
	WishWindowOpen    bool
}

// The same, reached from a wish rather than from an instance. For withdrawing one.
func (q *Queries) WishWriteContextByWishID(ctx context.Context, id uuid.UUID) (WishWriteContextByWishIDRow, error) {
	row := q.db.QueryRow(ctx, wishWriteContextByWishID, id)
	var i WishWriteContextByWishIDRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Phase,
		&i.WishesPublishedAt,
		&i.SubjectGroupID,
		&i.WishWindowOpen,
	)
	return i, err
}

const withdrawDemandComplete = `-- name: WithdrawDemandComplete :execrows
DELETE FROM demand_completion
 WHERE semester_id = (SELECT id FROM semester WHERE code = $1::text)
   AND programme_id = (SELECT id FROM programme WHERE code = $2::text)
`

type WithdrawDemandCompleteParams struct {
	Semester  string
	Programme string
}

// Take the announcement back. Deleting the row rather than a flag: "never announced" and
// "announced, then withdrawn" are the same state — the demand is not settled — and a table that
// kept the difference would be keeping something nobody reads.
func (q *Queries) WithdrawDemandComplete(ctx context.Context, arg WithdrawDemandCompleteParams) (int64, error) {
	result, err := q.db.Exec(ctx, withdrawDemandComplete, arg.Semester, arg.Programme)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
