// Package store is the storage layer and the only package in this module that is allowed to
// talk to PostgreSQL. The architecture test in internal/arch enforces that.
//
// The reason is the wish-visibility rule. If resolvers, the domain layer or a future CSV
// export handler could reach pgx directly, every one of them would have to remember to apply
// the filter, and one forgotten call site is not a bug in this project — it is the political
// failure the whole system is meant to prevent. Funnelling every read through this package
// means the filter has exactly one home.
//
// Most of this package is generated by sqlc from db/queries/*.sql. The hand-written part is
// what sqlc does not do: opening the pool and applying migrations.
package store

import (
	"context"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
)

// Pool is the connection pool, named here so that the packages that merely hold one — the
// wiring in bootstrap — can say its type without importing pgxpool.
//
// An alias rather than a defined type: it has to remain assignable to what pgxpool returns,
// and the point is naming, not wrapping. Without it, bootstrap can pass a pool from one
// function to another only as long as it never writes a signature that mentions it, which is
// the sort of constraint that quietly breaks the moment somebody extracts a helper — and the
// arch test that stops them is right to.
type Pool = *pgxpool.Pool

// Open creates a connection pool and verifies it can actually reach the database.
//
// The ping is not ceremony: without it a wrong DSN surfaces later, on the first query, as a
// failure of whatever request happened to arrive first. Failing here means the server refuses
// to start, which the container healthcheck and the deploy script both understand.
func Open(ctx context.Context, dsn string) (*pgxpool.Pool, error) {
	cfg, err := pgxpool.ParseConfig(dsn)
	if err != nil {
		return nil, fmt.Errorf("cannot parse database url: %w", err)
	}

	// Every session lands in Europe/Berlin, matching time.Local as pinned in main.go.
	// Milestone deadlines and phase boundaries are local-time; a pool whose sessions default
	// to UTC would make date_trunc and ::date in a query disagree with the same computation
	// in Go, and only for the hours where it matters.
	if cfg.ConnConfig.RuntimeParams == nil {
		cfg.ConnConfig.RuntimeParams = map[string]string{}
	}
	if _, set := cfg.ConnConfig.RuntimeParams["timezone"]; !set {
		cfg.ConnConfig.RuntimeParams["timezone"] = "Europe/Berlin"
	}

	pool, err := pgxpool.NewWithConfig(ctx, cfg)
	if err != nil {
		return nil, fmt.Errorf("cannot create connection pool: %w", err)
	}

	pingCtx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()
	if err := pool.Ping(pingCtx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("cannot reach database: %w", err)
	}

	return pool, nil
}

// WaitReady blocks until the database answers a ping, or until timeout elapses.
//
// It exists because of what happens after a host reboot, and the mechanism is worth writing
// down: docker compose's `depends_on: condition: service_healthy` orders containers only
// within a `docker compose up`. When the Docker DAEMON restarts containers by their restart
// policy after the machine comes back, it starts them in parallel and honours no dependency
// at all. Measured on tallox on 2026-09-14: every container's StartedAt fell inside 30 ms of
// the others, the server reached its migration before Postgres was accepting connections, and
// died with "connection refused". `restart: unless-stopped` recovered it 0.8 s later, so the
// only visible damage was one FATAL line per boot — but a server that exits because its
// database is four seconds late is reporting a failure it does not have.
//
// Retries every error rather than trying to classify it. A wrong password and a database that
// is still starting are not reliably distinguishable from the client side, and the expensive
// case is the same either way: the timeout expires and the last error is returned, exactly as
// a single attempt would have reported it. onWait, if non-nil, is called once on the first
// failure, so a caller can say WHY it is waiting instead of going quiet for a minute.
func WaitReady(ctx context.Context, dsn string, timeout time.Duration, onWait func(error)) error {
	cfg, err := pgxpool.ParseConfig(dsn)
	if err != nil {
		return fmt.Errorf("cannot parse database url: %w", err)
	}

	// One pool for every attempt: pgxpool connects lazily, so NewWithConfig only validates the
	// configuration and each Ping is a fresh connection attempt. Building a pool per try would
	// re-parse and re-allocate for no gain.
	pool, err := pgxpool.NewWithConfig(ctx, cfg)
	if err != nil {
		return fmt.Errorf("cannot create connection pool: %w", err)
	}
	defer pool.Close()

	deadline := time.Now().Add(timeout)
	const retryEvery = 500 * time.Millisecond
	notified := false

	for attempt := 1; ; attempt++ {
		// Per-attempt timeout, so one hung connect cannot eat the whole budget in silence.
		pingCtx, cancel := context.WithTimeout(ctx, 3*time.Second)
		err = pool.Ping(pingCtx)
		cancel()
		if err == nil {
			return nil
		}

		if !notified && onWait != nil {
			onWait(err)
			notified = true
		}

		// The caller's context losing patience is not the same as the database being down, and
		// must not be reported as it.
		if ctx.Err() != nil {
			return fmt.Errorf("cancelled while waiting for the database: %w", ctx.Err())
		}
		if !time.Now().Add(retryEvery).Before(deadline) {
			return fmt.Errorf("database not reachable within %s: %w", timeout, err)
		}

		select {
		case <-ctx.Done():
			return fmt.Errorf("cancelled while waiting for the database: %w", ctx.Err())
		case <-time.After(retryEvery):
		}
	}
}
