// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	// How much happened under each role, for one window.
	//
	// Over the EFFECTIVE roles, so a narrowed session counts under what it was narrowed to. That is
	// the honest reading: the request was judged by those roles, whatever the person holds.
	AccessLogByRole(ctx context.Context, arg AccessLogByRoleParams) ([]AccessLogByRoleRow, error)
	// The headline figures for one window, in one pass.
	//
	// One query rather than six, because the nightly report and the page both want all of them and
	// six round trips to count the same rows six times is how a report becomes something one is
	// reluctant to run.
	AccessLogCounts(ctx context.Context, arg AccessLogCountsParams) (AccessLogCountsRow, error)
	// One page of the log, newest first.
	//
	// Keyset pagination on (at, id) rather than OFFSET: the table grows at the head while somebody
	// is reading it, and OFFSET would silently skip or repeat rows exactly when the log is busiest —
	// which is when somebody is most likely to be reading it because something happened.
	AccessLogEntries(ctx context.Context, arg AccessLogEntriesParams) ([]AccessLogEntriesRow, error)
	// Every change made in one window, by whom and to what — grouped by person and root field.
	//
	// The field name is as specific as this gets, and deliberately so: see the note in the
	// migration. "setPersonRoles, three times, by X" is a report; the arguments would be a copy of
	// the data with none of the policy on it.
	AccessLogMutations(ctx context.Context, arg AccessLogMutationsParams) ([]AccessLogMutationsRow, error)
	// Who was turned away, and why, for one window.
	//
	// Grouped rather than listed: somebody whose account has no person row will retry, and twelve
	// identical lines say nothing that one line with a count does not. This is the part of the
	// nightly report that names people, and it names them because being turned away is the event.
	//
	// Both identifiers, and NEITHER is required. A refusal on the browser door has an address and
	// no token; a refusal on the token door has a token id and no address; a credential too
	// malformed to parse has neither and is still a knock at the door. An earlier version required
	// an address here and silently dropped every refused token — which is the half an administrator
	// most wants to see, because a token being tried repeatedly is what a leaked one looks like.
	AccessLogRefusedSignIns(ctx context.Context, arg AccessLogRefusedSignInsParams) ([]AccessLogRefusedSignInsRow, error)
	// The foreign key to person_role is what refuses a lead who does not hold the role. The service
	// checks first so that the ordinary case gets a sentence; this is the race the constraint closes.
	AddSubjectGroupLead(ctx context.Context, arg AddSubjectGroupLeadParams) error
	AddSubjectGroupMembership(ctx context.Context, arg AddSubjectGroupMembershipParams) error
	// Compare-and-set: $3 is the phase the caller believes the semester is in, and no rows come
	// back if it has moved on since they looked.
	//
	// That is what makes "one step at a time" hold under concurrency. Without the second
	// predicate, two switches issued together would both read DEMAND_PLANNING, and the second
	// would write ASSIGNMENT over the first one's WISHES — a skipped phase, arrived at by nobody's
	// decision, and invisible afterwards because the row looks like somebody chose it.
	AdvanceSemesterPhase(ctx context.Context, arg AdvanceSemesterPhaseParams) (Semester, error)
	// A batch, because the task this exists for is assigning 506 modules and a screen that saves one
	// row per click is a task nobody finishes.
	//
	// An upsert rather than delete-then-insert: moving a module between groups is one statement, so
	// there is no moment in which the module belongs to nothing. assigned_by moves with it, because
	// the question this column answers — who says this module is mathematics — is about the current
	// assignment and not about the first one.
	AssignModulesToSubjectGroup(ctx context.Context, arg AssignModulesToSubjectGroupParams) (int64, error)
	// Give somebody's grant one more programme.
	//
	// ON CONFLICT DO NOTHING rather than an error: setting the same list twice is not a mistake, and
	// the caller replaces the whole set anyway. The foreign key to person_role is what refuses an
	// assignment to somebody who does not hold the role — the check is the schema's, not a race
	// somebody has to remember here.
	AssignProgramme(ctx context.Context, arg AssignProgrammeParams) error
	// The parts of *sibling* cohorts that are held for this one as well.
	//
	// The other half of instance_part.serves_sibling_tracks. A lecture given once for IF3A and IF3B
	// is one row, owned by one of them; the other has to render it, or its screen shows a cohort
	// with laboratories and no lecture and looks like a planning mistake.
	//
	// Siblings are the instances of the same module, in the same semester, for the same programme —
	// which is the identity minus the parallel cohort, and exactly what course_instance_cohort_idx
	// covers. Sharing reaches no further than that on purpose: a part shared between two programmes
	// would belong to both, and the import/export figure would lose its denominator.
	BorrowedInstancePartsFor(ctx context.Context, instanceIds []uuid.UUID) ([]BorrowedInstancePartsForRow, error)
	CatalogueProjectionNotes(ctx context.Context, projectionID uuid.UUID) ([]CatalogueProjectionNotesRow, error)
	// Taking modules out of every group, which is the same screen's other button. A module with no
	// group is a normal state and the whole of October's work list.
	ClearModulesSubjectGroup(ctx context.Context, moduleIds []uuid.UUID) (int64, error)
	// Take the mark off whichever semester carries it, except the one about to receive it.
	//
	// Runs first in the transaction that moves the mark, and that order is what makes concurrency
	// boring: this UPDATE takes a row lock on the current planning semester, so two people setting
	// different semesters at the same moment serialise here instead of colliding on the unique
	// index afterwards. The second one wins, which is the right outcome for a decision somebody is
	// taking on purpose.
	//
	// The exception for the target is not decoration: without it, setting the semester that is
	// already set would clear the mark and then set it again, moving planning_set_at and making a
	// no-op look like a decision.
	ClearPlanningSemester(ctx context.Context, id uuid.UUID) error
	ClearSubjectGroupLeads(ctx context.Context, subjectGroupID uuid.UUID) error
	ClearSubjectGroupMembers(ctx context.Context, subjectGroupID uuid.UUID) error
	// The person side of the membership table.
	//
	// Its own statement rather than a filter on the group side, because the two are different acts:
	// an administrator sets up a group, and a colleague says which subjects they work in. Both write
	// this table and neither may quietly rewrite the other's rows.
	ClearSubjectGroupsOfPerson(ctx context.Context, personID uuid.UUID) error
	// Not projected, and the largest of the nine: 665 real rows over 12 sets of regulations the
	// endpoint stopped returning — the historical ones and a placeholder dated 2099.
	//
	// Grouped by regulations in the sample rather than by association, because the useful thing to
	// see is which twelve, not which six hundred.
	CountAssociationsWithUnknownRegulations(ctx context.Context) (CountAssociationsWithUnknownRegulationsRow, error)
	// Must be zero, and is the one line here that is an alarm rather than a note.
	//
	// The grain of module_offering rests on compulsory-or-elective being determined by (module,
	// regulations) — measured at 0 conflicts over 2386 pairs. If the source ever contradicts that,
	// the fold silently picks one answer, and this is what says so.
	CountDutyConflicts(ctx context.Context) (CountDutyConflictsRow, error)
	// Projected with the flag, never hidden. "What did this programme offer in 2024" is a question
	// worth being able to answer.
	//
	// Same restriction as above, and here it bites: deactivating a local course is how one is
	// retired, so without the predicate every retired placeholder would appear as a finding of the
	// next night's import.
	CountInactiveModules(ctx context.Context) (CountInactiveModulesRow, error)
	// Folded with min(). Two real pairs are in this state, and both are a module sitting in an
	// ordinary catalogue slot and a specialisation of the same version that disagree about the
	// earliest semester a student may take it.
	// The count is of pairs and the sample is of modules, deliberately: one module can be in this
	// state in two versions of the regulations at once, and printing its identifier twice would
	// read as two different modules.
	CountMinSemesterConflicts(ctx context.Context) (CountMinSemesterConflictsRow, error)
	// The source names somebody the teacher list does not contain.
	//
	// Sixteen of 506 today: seven placeholders ("N.N", "ex_prof_003") and nine addresses. The
	// sample carries the module identifiers rather than the addresses — the whole reason these are
	// not stored is that a mail address belongs in the table about people, and a report is not an
	// exception to that.
	CountModulesWithUnknownResponsible(ctx context.Context) (CountModulesWithUnknownResponsibleRow, error)
	// The report
	// ----------
	//
	// Nine things the projection decides about untidy input, each counted with a handful of
	// examples. Counts and samples rather than a row per object: the useful sentence is "665
	// associations across 12 sets of regulations", and whoever wants to chase one needs a few
	// identifiers, not all of them.
	//
	// Every one of these runs inside the same transaction as the statements above, against the same
	// snapshot — so the report describes the projection that happened rather than the cache as it
	// looked a moment later.
	// Skipped entirely. The source writes the string "None" and zpa_text() has already turned it
	// into a NULL, which is the difference between "absent" and "a programme called None".
	CountModulesWithoutHomeProgramme(ctx context.Context) (CountModulesWithoutHomeProgrammeRow, error)
	// Projected with an empty name, because the alternative is worse.
	//
	// The source's module objects carry no name field at all; the name is borrowed from an
	// association row, so a module in no set of regulations has none anywhere. Skipping them would
	// mean a programme lead searching for a module they are responsible for and not finding it.
	//
	// Restricted to the rows the projection wrote. A module the faculty entered itself is not a
	// finding of an import that has never heard of it — and a nameless one is impossible there
	// anyway, since somebody typed the name. Without the predicate every local row with an empty
	// sample would turn up in the nightly report.
	CountModulesWithoutName(ctx context.Context) (CountModulesWithoutNameRow, error)
	// How many people other than this one could still administer the installation.
	//
	// "Could still": active person, unexpired grant. A deactivated administrator and one whose
	// temporary grant ran out are both people who cannot let anybody back in, and counting them
	// would make the last-administrator guard pass at exactly the moment it is needed.
	//
	// Called under the advisory lock, never on its own.
	CountOtherActiveAdmins(ctx context.Context, personID uuid.UUID) (int64, error)
	// Projected and marked inactive. Their modules stay planable, which is the point: the real one
	// has six modules behind it and four of them are still active.
	CountProgrammesWithoutRegulations(ctx context.Context) (CountProgrammesWithoutRegulationsRow, error)
	// A teacher the source gives no address for. Three of 257, and they can never be connected to a
	// person in this installation — worth seeing, not worth refusing.
	CountTeachersWithoutMail(ctx context.Context) (CountTeachersWithoutMailRow, error)
	// Became DEPENDS_ON_SUBJECT. Same reasoning, and the same exclusion of the empty phrase —
	// except that the source really does write "je nach Fach", which maps to the same value and is
	// therefore excluded here too, or 23 modules would be reported as a problem every night.
	CountUnmappedCourseTypes(ctx context.Context, dependsOnSubjectPhrase string) (CountUnmappedCourseTypesRow, error)
	// Became UNKNOWN. An empty phrase is not counted: absent is a state the source is entitled to
	// be in, and eleven modules are in it — burying the genuinely new phrases under them would
	// defeat the purpose of the line.
	CountUnmappedFrequencies(ctx context.Context) (CountUnmappedFrequenciesRow, error)
	CourseInstanceByID(ctx context.Context, id uuid.UUID) (CourseInstanceByIDRow, error)
	// The instance a part belongs to, for the permission check on a part-level write.
	//
	// One statement rather than "read the part, then read its instance": the thing being decided is
	// whether this actor may write this programme's demand in this phase, and both halves of that
	// come off the instance.
	CourseInstanceByPartID(ctx context.Context, id uuid.UUID) (CourseInstanceByPartIDRow, error)
	// What one programme declared in one semester, by id — the input of a copy and of a plan.
	//
	// Addressed by semester id rather than by code, unlike the list above, because both callers
	// already hold the semester as a row: looking it up again by code inside the transaction would be
	// a second chance to disagree about which semester is meant.
	CourseInstancesOfProgramme(ctx context.Context, arg CourseInstancesOfProgrammeParams) ([]CourseInstancesOfProgrammeRow, error)
	// People and their role grants.
	//
	// Every read that resolves an identity returns the roles with it, in one round trip. Two
	// queries would mean a window in which a person exists and their grants do not, and the
	// authenticator would have to decide what to do with a caller whose permissions it could not
	// read — a decision with only bad answers.
	//
	// The expiry filter sits in the JOIN condition rather than in a WHERE clause, in every query
	// below. That is not a style preference: in a LEFT JOIN, a WHERE on the right-hand table
	// turns the join into an inner one, so a person whose only grant has expired would disappear
	// from the list entirely instead of appearing with no roles. The version that leaks is the
	// one that hides people from the administration screen.
	// The id is supplied by the caller rather than defaulted, so that a fixture, a seed and an
	// import can all say who they are creating before the insert happens.
	CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error)
	CreateSubjectGroup(ctx context.Context, arg CreateSubjectGroupParams) (CreateSubjectGroupRow, error)
	// Personal Access Tokens: the second door.
	// The secret is generated and hashed by the caller (internal/auth), never here: a secret that
	// travelled through a query is a secret in a log somewhere.
	CreateToken(ctx context.Context, arg CreateTokenParams) (CreateTokenRow, error)
	// Withdraw an instance. Its parts go with it; anything else pointing at it stops it.
	//
	// instance_part is ON DELETE CASCADE, which is what makes this one statement. Everything that
	// will later hang off a part — a wish, an assignment — is a foreign key that refuses, and the Go
	// side maps that refusal to one opaque answer without a count. A message naming what stopped the
	// withdrawal would be a wish oracle: "this instance has 3 wishes" is the confidential fact, with
	// the names removed and nothing else.
	DeleteCourseInstance(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteInstancePart(ctx context.Context, id uuid.UUID) (int64, error)
	// The other half of merging a part across the parallel cohorts: the siblings' own copies of it
	// go away, because from now on this one is held for them too.
	//
	// By kind rather than by id, because that is what "the lecture" means to the person doing it: a
	// cohort has one lecture, and after the merge the faculty holds one lecture for both. A sibling
	// part that something already hangs off refuses to go, and the merge fails as a whole.
	DeleteInstancePartsOfKind(ctx context.Context, arg DeleteInstancePartsOfKindParams) (int64, error)
	// Withdraw one's own wish.
	//
	// Ownership is in the WHERE clause rather than in a read-then-write in Go, which collapses three
	// things into one, exactly as RevokeTokenOfOwner does: the check cannot race with a concurrent
	// change, "no such wish" and "not your wish" become the same empty result — the difference is
	// not information the caller is entitled to — and there is no window in which an id has been
	// confirmed to exist before the write is refused.
	DeleteOwnWish(ctx context.Context, arg DeleteOwnWishParams) (int64, error)
	// Offerings the source no longer supports.
	//
	// The only catalogue table anything is deleted from, and it is safe for one reason that is
	// asserted by a test rather than assumed: nothing references an offering. A module keeps its
	// row and gains retired_at; a programme keeps its row and loses `active`; an offering is a
	// claim about somebody else's regulations, and when they stop making it the claim goes.
	DeleteStaleModuleOfferings(ctx context.Context) (int64, error)
	// Get this mail address a person row, creating one if there is none.
	//
	// The reconciliation of the protected administrators runs through here on every start, so it
	// has to be a no-op on the ordinary case. ON CONFLICT DO UPDATE rather than DO NOTHING,
	// because DO NOTHING returns no row and the caller would need a second query to find the id
	// of the person it just did not create.
	//
	// name is only written when the row is created: a person renamed through the interface, or by
	// a future ZPA import, must not be renamed back on the next restart by a value somebody typed
	// into a YAML file once. The DO UPDATE therefore writes a column back to itself — a true
	// no-op that still produces a row to return, which DO NOTHING does not.
	EnsurePerson(ctx context.Context, arg EnsurePersonParams) (Person, error)
	// Semesters and the phase each one is in.
	//
	// Two of these are compare-and-set rather than plain updates, and that is the theme of the
	// file. A phase advance and a publication are both "change this only if it is still what I
	// think it is": the alternative is to read the row, decide in Go, and write — which is correct
	// in a unit test and a race in production, because two people from the dean's office clicking
	// at the same moment is precisely the situation a phase switch happens in.
	// The row for a semester, created if this is the first decision anybody records about it.
	//
	// Nobody creates a semester — a semester is a name for a stretch of time and is there the way
	// next March is there. The row holds the decisions taken about one, so it comes into existence
	// with the first of them, and its defaults are what an untouched semester already means:
	// DEMAND_PLANNING, wishes confidential.
	//
	// ON CONFLICT DO UPDATE rather than DO NOTHING, because DO NOTHING returns nothing when the
	// row is already there and would need a second query to find out what it looks like — a race
	// for the sake of a statement that reads slightly better. Assigning the code to itself is the
	// idiom for "give me the row either way"; nothing is changed by it, and updated_at stays where
	// it was so that arriving at a semester does not look like deciding something about it.
	EnsureSemester(ctx context.Context, code string) (Semester, error)
	// Called at startup, beside the protected-admin reconciliation.
	//
	// A process that dies mid-sync leaves a RUNNING row forever, and forever is long enough that
	// the interface would show a run in progress that nothing is progressing. The cutoff is passed
	// in rather than hard-coded here so the caller's reasoning about it stays in Go.
	FailAbandonedZPASyncRuns(ctx context.Context, olderThan time.Time) ([]uuid.UUID, error)
	FinishCatalogueProjection(ctx context.Context, arg FinishCatalogueProjectionParams) (FinishCatalogueProjectionRow, error)
	FinishZPASyncRun(ctx context.Context, arg FinishZPASyncRunParams) (ZpaSyncRun, error)
	// Idempotent in the sense that matters: granting a role somebody already holds updates its
	// expiry rather than failing, so "give me DEANS_OFFICE for another hour" is one call and not
	// a read-then-write race.
	//
	// granted_at is refreshed with it. The row records the grant that is in force, and a
	// timestamp that pointed at a superseded one would be the wrong answer to the audit question.
	GrantRole(ctx context.Context, arg GrantRoleParams) error
	// Declare an instance. The unique key is the identity — semester, module, programme, cohort.
	//
	// A conflict is reported rather than absorbed: somebody declaring IF3A twice has made a mistake
	// worth naming, and the demand is not confidential, so naming it leaks nothing. The copy path is
	// the one place that wants a conflict to be a no-op, and it uses the statement below.
	InsertCourseInstance(ctx context.Context, arg InsertCourseInstanceParams) (uuid.UUID, error)
	// The copy path's insert: an instance that is already declared is left exactly as it is.
	//
	// DO NOTHING with a RETURNING of the id, so "created" and "was already there" are distinguished
	// by whether a row comes back rather than by a count read afterwards. DO UPDATE would overwrite
	// a cohort year somebody has since corrected in the target semester — a copy must never silently
	// undo work in the semester it is copying into.
	InsertCourseInstanceIfAbsent(ctx context.Context, arg InsertCourseInstanceIfAbsentParams) (uuid.UUID, error)
	InsertInstancePart(ctx context.Context, arg InsertInstancePartParams) (uuid.UUID, error)
	// A course the faculty enters itself: not in the examination office's catalogue, or not yet.
	//
	// No zpa_module_ref, and the constraint says so rather than this statement — see migration 11.
	// `active` and `official` keep their defaults: both are statements about what the examination
	// office says, and about a local row it says nothing.
	InsertLocalModule(ctx context.Context, arg InsertLocalModuleParams) (InsertLocalModuleRow, error)
	InsertModuleComponent(ctx context.Context, arg InsertModuleComponentParams) error
	// The parts of a set of instances, in one statement.
	InstancePartsFor(ctx context.Context, instanceIds []uuid.UUID) ([]InstancePartsForRow, error)
	// Whether a cohort already has a part of this kind, so that undoing a merge does not give it two.
	InstancePartsOfKindExist(ctx context.Context, arg InstancePartsOfKindExistParams) (bool, error)
	// The one number the interface shows largest, and the one the deploy smoke check asserts is
	// recent. PARTIAL counts: it fetched something, and a run that got three of four endpoints is
	// not the silence this is watching for.
	LastSuccessfulZPASyncRun(ctx context.Context) (LastSuccessfulZPASyncRunRow, error)
	LatestCatalogueProjections(ctx context.Context, limit int32) ([]LatestCatalogueProjectionsRow, error)
	// Connect each module to the person the source names as responsible for it.
	//
	// Runs after both, because it needs both. Matched on the address, lower-cased on the teacher
	// side by the view and here on the module side — the source writes it as somebody typed it.
	//
	// The 16 that do not resolve are set to NULL rather than left as they were: a module whose
	// responsible person the source has changed to somebody unknown must not keep pointing at the
	// previous one. What they were is reported, not stored — a mail address belongs in the table
	// about people.
	LinkModuleResponsibles(ctx context.Context) (int64, error)
	// The demand: which course instances a study programme needs in a semester.
	//
	// Same shape as the catalogue file next to it — a list costs a fixed number of statements and is
	// stitched in Go — and for the same measured reason. A semester's demand for one programme is
	// tens of instances with a handful of parts each, so "load the instances, load their parts, join
	// them here" is two statements where a field resolver per relation would be one per row.
	//
	// Two things in here are transactions rather than statements, and both are in this file's Go
	// neighbour: declaring an instance writes the instance and the parts made from the module's
	// split, and copying a semester's demand writes all of it or none of it. A half-copied semester
	// is worse than an uncopied one, because the person looking at it cannot tell which half.
	// The demand of a semester, optionally narrowed to one programme or one module.
	//
	// The semester is addressed by its code rather than its id, the way it is everywhere outside
	// this package: the code is what a URL and a colleague's script carry.
	//
	// Ordered the way the demand is read — by cohort year, then by module, then by parallel cohort,
	// so that IF3A and IF3B sit next to each other and a programme's list walks up the semesters.
	// The module's name is ordered by without being selected: it is attached from the catalogue
	// afterwards, and selecting it here would be a second copy of the same string that could drift
	// from the one the interface shows.
	ListCourseInstances(ctx context.Context, arg ListCourseInstancesParams) ([]ListCourseInstancesRow, error)
	// The catalogue, filtered.
	//
	// The programme filter is a union of two conditions and the second is not redundant: a module
	// counts in one of the programme's sets of regulations, OR the programme is its home. Measured
	// against the real catalogue, 26 active modules are reachable only through the second half, ten
	// of them in the largest programme — and the first thing a programme lead does is look for a
	// module they are responsible for.
	//
	// The duty filter is applied through the same subquery rather than beside it, so that
	// "compulsory in this programme" cannot accidentally mean "compulsory anywhere". MIXED is
	// expressed as "has both", which is what makes it a filter rather than a label.
	// A module with no name sorts last rather than first: the empty string would otherwise put the
	// handful of nameless ones at the top of every list in the system.
	ListModules(ctx context.Context, arg ListModulesParams) ([]ListModulesRow, error)
	// The administration screen: everybody, or everybody active, optionally narrowed by a
	// substring of the mail address or the name.
	//
	// Ordered by the surname, which is why the teacher list is joined in. `person.name` is the name
	// as somebody wrote it — "Prof. Dr. Vorname Nachname" — and a list sorted by that is a list
	// sorted by academic title. The examination office publishes the surname-first spelling for
	// everybody it knows, and joining it on the address costs nothing to keep in step: somebody
	// admitted this morning sorts correctly now rather than after the next import. Whoever it does
	// not know keeps their own name as the key, because the alternative is guessing which word of it
	// is the surname.
	//
	// Then by mail, so that the order is stable between calls — an administration table whose rows
	// move between reloads is one where somebody eventually clicks the wrong row. People with no
	// name yet sort first, which is also where the work is.
	ListPeople(ctx context.Context, arg ListPeopleParams) ([]ListPeopleRow, error)
	// Reading the module catalogue.
	//
	// The shape of this file is set by one decision: a list of modules is loaded in a fixed number
	// of statements rather than one per row. Four for a filtered list — the modules, their
	// components, their offerings, and the programmes — stitched together in Go. The catalogue is
	// 506 modules and 1784 offerings, so loading what a screen needs and joining it in memory is
	// both simpler than a loader framework and faster than the query-per-field it replaces.
	// The study programmes, including the one with no current regulations.
	//
	// Only the ones this faculty plans, unless the caller asks for the others too. The catalogue
	// holds every programme the examination office's regulations mention, and some of them are not
	// this faculty's business — a picker that offered them would be asking somebody to plan a
	// programme nobody here runs. See migration 12 for why this is a column and not a rule.
	//
	// Ordered by code, which is how the faculty says them and how a picker should show them.
	ListProgrammes(ctx context.Context, includeUnplanned bool) ([]ListProgrammesRow, error)
	// Every version of every programme's regulations, newest first within a programme.
	//
	// Loaded whole rather than per programme: 29 rows, and every screen that shows one programme's
	// versions also has the others in a picker beside it.
	ListSpos(ctx context.Context) ([]ListSposRow, error)
	// The people the examination office publishes, each with the account they have here.
	//
	// The same LEFT JOIN on the address that Teacher.is_user is derived from, and deliberately
	// without `AND p.active`: this list is the one screen that has to tell "nobody of this address
	// may sign in" apart from "somebody deactivated them", and those are two different next steps.
	// person_id is what distinguishes them; the other person columns are COALESCEd because a
	// LEFT JOIN makes NOT NULL columns nullable and scanning NULL into a string fails at runtime.
	//
	// Retired teachers — ones a successful import stopped mentioning — are left out. People the
	// source marks as no longer teaching are not: five such people are still named as responsible
	// for a module, and somebody who left has an account that still has to be closable.
	ListTeacherAccounts(ctx context.Context) ([]ListTeacherAccountsRow, error)
	// The people who teach, with whether somebody of that address may sign in here.
	//
	// The LEFT JOIN to person is the link between the two lists, and it is done here rather than
	// stored as a column so that somebody admitted this morning is connected now rather than after
	// the next import. `mail` is citext on both sides, so the casing the identity provider happens
	// to use does not decide the answer.
	//
	// `p.active` belongs in the join condition and not beside it: is_user says whether somebody of
	// this address may sign in, and a deactivated person may not — deactivating is how this system
	// takes everything away at once. In a WHERE it would instead drop the teacher from the list.
	//
	// Retired teachers — ones a successful import stopped mentioning — are left out entirely,
	// unlike the source's own `active` flag which is a column and a filter. The two are different
	// questions: "no longer teaching" is worth seeing, "no longer published" is not.
	// COALESCE, and it is not cosmetic: three of the 257 carry no address, sqlc cannot know that a
	// cast is nullable, and scanning NULL into a string fails at runtime rather than at build time.
	// Empty means absent, which is what the domain type says too.
	ListTeachers(ctx context.Context, arg ListTeachersParams) ([]ListTeachersRow, error)
	// The token list in the GUI. The secret hash is not in the projection: nothing outside
	// authentication has a use for it, and a column that is never selected cannot be logged.
	ListTokensOfPerson(ctx context.Context, ownerID uuid.UUID) ([]ListTokensOfPersonRow, error)
	// Serialise every change that could remove the last administrator.
	//
	// The rule to protect is "at least one active person holds an unexpired ADMIN grant", and it
	// is a statement about a *set* of rows. Two administrators can each check it, each see the
	// other, and each commit a change that was only safe while the other did not happen — the
	// textbook write skew, and here its outcome is an installation nobody can get into.
	//
	// A single clever statement does not fix it, because the two dangerous operations touch
	// different tables: revoking ADMIN writes person_role, deactivating an administrator writes
	// person. What they have in common is these rows, so both take this lock first and the second
	// one waits and then re-reads.
	//
	// Row locks rather than an advisory lock on a constant: this is scoped to the current schema,
	// which is what lets the integration tests run in parallel, and it needs no magic number that
	// somebody else could pick again for something unrelated.
	LockAdminGrants(ctx context.Context) error
	// The codes ProjectProgrammes had to leave out, so the report can name them.
	MalformedProgrammeCodes(ctx context.Context) ([]string, error)
	// Make this semester the one being planned.
	//
	// Unconditional and idempotent in effect: setting the semester that is already set rewrites the
	// same values. planning_set_at moves, and that is intended — it records the most recent time
	// somebody decided this, which is what a reader of the audit wants to know.
	MarkPlanningSemester(ctx context.Context, arg MarkPlanningSemesterParams) (Semester, error)
	// Coarse on purpose. "Last used" is answering "is this token still in use, can I revoke it",
	// and five-minute resolution answers that as well as microsecond resolution would.
	//
	// The guard is the point: without it, every API call takes a row lock and writes WAL, which
	// serialises the requests of a single script against itself and makes the busiest tokens the
	// slowest ones.
	MarkTokenUsed(ctx context.Context, tokenID string) error
	ModuleByID(ctx context.Context, id uuid.UUID) (ModuleByIDRow, error)
	// The splits of a set of modules, in one statement.
	ModuleComponentsFor(ctx context.Context, moduleIds []uuid.UUID) ([]ModuleComponentsForRow, error)
	// Where a set of modules counts, in one statement, joined to the regulations they count in.
	//
	// Unfiltered by programme on purpose, even when the list was filtered by one. A module's
	// offerings are what "where does this count" means, and answering it with only the programme
	// somebody happened to filter by would make the same module look different depending on how it
	// was found.
	ModuleOfferingsFor(ctx context.Context, moduleIds []uuid.UUID) ([]ModuleOfferingsForRow, error)
	// A handful of modules by id, for attaching them to the instances that offer them.
	//
	// The demand of a semester names tens of modules and the catalogue holds 506, so the list query
	// with a filter would read the whole table to answer a question about twenty rows. Same ordering
	// as the list, so that a screen sorted by module reads the same way in both places.
	ModulesByIDs(ctx context.Context, ids []uuid.UUID) ([]ModulesByIDsRow, error)
	// Which modules a subject group holds, for the screen that shows somebody what a group is about.
	//
	// The names and their home programme, and nothing else: this answers "is this my subject", not
	// "what does this module cost". Retired modules are left out — a group is described by what it
	// currently covers.
	ModulesOfSubjectGroup(ctx context.Context, subjectGroupID uuid.UUID) ([]ModulesOfSubjectGroupRow, error)
	// The work list as a number: "37 modules still have no subject group".
	//
	// Retired modules do not count. A module the examination office stopped publishing is not work
	// anybody has to finish, and counting it would make the list unfinishable.
	ModulesWithoutSubjectGroup(ctx context.Context) (int32, error)
	// Where a newly added part goes: after the last one.
	//
	// COALESCE with the cast outside, for the same reason as above — MAX over no rows is NULL, and
	// an instance with no parts yet is the ordinary state of one whose module has an empty split.
	NextInstancePartPosition(ctx context.Context, courseInstanceID uuid.UUID) (int32, error)
	// Joined to the teacher list like ListPeople, so that one person and the list agree about the
	// name a list is sorted by. Not so for PersonByMail above: that one authenticates every request
	// on the browser door, and a join it has no use for does not belong on that path.
	PersonByID(ctx context.Context, id uuid.UUID) (PersonByIDRow, error)
	// The authentication query of the browser door. mail is citext, so the comparison is
	// case-insensitive without a lower() that would defeat the unique index.
	//
	// role_scopes carries the grants that name a thing as well as an action — leading *one* study
	// programme, or *one* subject group, rather than leading in general. A correlated subquery
	// rather than a second LEFT JOIN, because joining two one-to-many tables in one SELECT
	// multiplies their rows and the roles array would repeat every role once per scope.
	//
	// It reads person_role_scope, the view that unions the two scope tables and applies the expiry
	// filter. That filter is the same rule as the one on the roles above and for the same reason —
	// a grant the database considers over must not still take effect — and it lives in the view
	// because this subquery appears three times in this file and once in token.sql. The composite
	// foreign keys mean a scope cannot outlive a *revoked* grant; the view covers the one that
	// merely ran out.
	//
	// The nil uuid stands for "this scope names no thing of that kind", which is exactly how
	// principal.RoleScope reads it. Coalescing here rather than emitting JSON null keeps the
	// decoding free of a subtlety about how null unmarshals into a non-pointer.
	PersonByMail(ctx context.Context, mail string) (PersonByMailRow, error)
	// The semester the faculty is planning, or no row while nobody has said.
	//
	// No LIMIT: the partial unique index makes "at most one" a property of the table rather than
	// of this statement, and a LIMIT here would quietly return one of several if that ever stopped
	// being true.
	PlanningSemester(ctx context.Context) (Semester, error)
	// One programme, whatever its planning status.
	//
	// Deliberately unfiltered: reading the demand of a programme that has run out is a legitimate
	// question — that is the record of what the faculty did — and the refusal to *write* one belongs
	// where the write is, with a sentence that says which of the two reasons applies.
	ProgrammeByCode(ctx context.Context, code string) (ProgrammeByCodeRow, error)
	// Which study programmes a set of people lead.
	//
	// For a list of people in one statement rather than one per row, the same shape the catalogue
	// uses. Joined through person_role with the expiry filter, so a grant the database considers
	// over carries no programmes — the composite foreign key covers a revoked grant, and this covers
	// one that merely ran out.
	ProgrammeScopesFor(ctx context.Context, personIds []uuid.UUID) ([]ProgrammeScopesForRow, error)
	// A handful of programmes by id, without their regulations.
	//
	// For `me`, which has to turn the programme ids an actor carries into codes a person reads. The
	// full list with its regulations attached would be two statements and 29 rows of examination
	// regulations for a field that renders two letters.
	ProgrammesByIDs(ctx context.Context, ids []uuid.UUID) ([]ProgrammesByIDsRow, error)
	// Where each module counts, folded to one row per module per set of regulations.
	//
	// The fold is the point. A module sits in up to four catalogue slots of one version — the
	// ordinary catalogue and the specialisations — and the slots differ in the module code and
	// sometimes in the earliest semester. Measured over the whole catalogue they never differ in
	// compulsory-or-elective, which is what makes this grain safe and one grain coarser unsafe.
	//
	// bool_and rather than bool_or, so that if the assumption ever breaks the result is the weaker
	// claim rather than the stronger one. DutyConflicts below reports it either way.
	// Both joins are inner, and each one drops a documented case: an association whose module was
	// skipped for having no home programme, and an association pointing at regulations the source
	// no longer returns. The second is 665 real rows and is reported by
	// AssociationsWithUnknownRegulations.
	ProjectModuleOfferings(ctx context.Context) (int64, error)
	// The catalogue itself.
	//
	// The two vocabularies arrive as German prose and are translated through a mapping passed in
	// from internal/domain, rather than through a CASE expression written here. The mapping already
	// has three homes that cannot import one another; a fourth inside a query would be the one
	// nobody updates, in the place where being wrong is silent.
	//
	// An unrecognised phrase becomes the safe value and is counted by UnmappedVocabulary below. It
	// must never be only the safe value: UNKNOWN is what the term filter treats as "show it
	// anyway", so a phrase that quietly fell to it would hide nothing and explain nothing.
	//
	// Modules whose home programme is absent are dropped by the inner join, which is the whole
	// mechanism — the column is NOT NULL by decision, and zpa_text() has already turned the
	// source's "None" into a real NULL. WithoutHomeProgramme below counts what fell out.
	ProjectModules(ctx context.Context, arg ProjectModulesParams) (int64, error)
	// The module catalogue, projected out of the cached payloads.
	//
	// The theme of this file is that the projection is a fold, not a copy. The source publishes one
	// row per module per set of regulations per catalogue slot; what planning asks about is a
	// module, a programme and whether the module is compulsory there. Every statement below turns
	// the first into the second, and every one of them is written so that running it twice changes
	// nothing.
	//
	// Two rules hold throughout. Nothing here joins a domain row to the cache at request time — the
	// zpa_*_ref columns are matched once, in these statements, and never again. And nothing here
	// writes a module's `responsible` field into a domain table: it is a colleague's mail address,
	// and this repository is public.
	// Every programme the source knows, from either direction.
	//
	// Two directions, because the source disagrees with itself about which programmes exist. Nineteen
	// appear in the regulations endpoint; nineteen are named as the home of a module; and they are
	// not the same nineteen. One programme has regulations and not a single module, another has six
	// modules and no regulations at all. Deriving the list from either side alone loses the other's
	// odd one out — and losing the second costs four active modules, because a module's home
	// programme is mandatory.
	//
	// `active` is exactly "the regulations endpoint knows it". A programme nobody publishes
	// regulations for is not an error and not a normal choice either: its modules stay planable and
	// it stays out of the pickers.
	//
	// `title` is written on insert only — never in the DO UPDATE. The source has no long name (its
	// `title` field carries the code again), so the column is for a human, and a projection that
	// refreshed it would overwrite what they typed on the next nightly run.
	// Defence rather than expectation: every real code is two to four upper-case letters. Without
	// the filter, one malformed code would abort the whole projection and take every other
	// programme's modules with it. What is filtered out is counted by MalformedProgrammeCodes below.
	ProjectProgrammes(ctx context.Context) (int64, error)
	// One row per version of one programme's regulations.
	//
	// Only the ones the endpoint returns. The 12 the association rows reference and the endpoint
	// does not are deliberately not synthesised from the copy embedded in those rows: that copy has
	// a version and a date but no programme, and a set of regulations belonging to no programme is
	// the same pathology as a module whose owner is the string "None", one level up.
	ProjectSpos(ctx context.Context) (int64, error)
	// The people who teach, as the examination office publishes them.
	//
	// Before the modules, because a module names one. Everybody is taken, including the 49 the
	// source marks inactive: five of them are still named as responsible for a module, and a
	// filter here would leave those modules pointing at nobody for a reason nobody could see. The
	// flag is a column, and the filtering happens where somebody is looking at a list.
	//
	// Note what this does NOT do: it creates no person rows and grants nothing. A teacher is
	// imported master data; who may use this installation is a decision somebody makes in the
	// people administration. Six of the 257 carry addresses the identity provider will never
	// assert, so the two sets are not the same even in principle.
	ProjectTeachers(ctx context.Context) (int64, error)
	// Delete what is older than the cutoff and say how much that was.
	//
	// Returning the count is not decoration: it goes into the nightly report, so a prune that has
	// silently stopped working shows up as a number that stops moving rather than as a table that
	// quietly grows for a year.
	PruneAccessLog(ctx context.Context, cutoff time.Time) (int64, error)
	// Idempotent, and it keeps the *first* timestamp.
	//
	// Publishing twice is not an error — the second caller wanted the wishes published and they
	// are — but the moment it happened is a fact about the process that a second call must not
	// overwrite. COALESCE does both in one statement, so there is no window between checking and
	// writing.
	//
	// updated_at stays untouched when nothing changed, so a repeated call does not make the row
	// look edited.
	PublishSemesterWishes(ctx context.Context, id uuid.UUID) (Semester, error)
	// The access log: one row per operation, plus the sign-ins that were refused before there was
	// an operation at all.
	//
	// The theme of this file is that every read is an aggregate or a bounded page. An audit trail
	// is the one table where "select everything and filter in Go" is not merely slow but wrong:
	// the row limit is what keeps a support question from pulling a term's worth of colleagues'
	// movements into a process that then logs its own memory usage.
	// Append one entry. Called on the request path, best-effort — see graph.RecordAccess.
	//
	// Nothing here is read back. The caller has no use for the id, and returning one would cost a
	// round trip on every single request for a value nobody wants.
	RecordAccess(ctx context.Context, arg RecordAccessParams) error
	// Only ever called with a positive count — a note saying "nothing happened" is noise in a
	// report whose whole value is that every line means something.
	RecordCatalogueProjectionNote(ctx context.Context, arg RecordCatalogueProjectionNoteParams) error
	RecordZPAChange(ctx context.Context, arg RecordZPAChangeParams) error
	RecordZPASyncRunKind(ctx context.Context, arg RecordZPASyncRunKindParams) error
	// The name only. The code is the address — it is in URLs and in colleagues' scripts — and
	// changing it is not a rename but a different group.
	RenameSubjectGroup(ctx context.Context, arg RenameSubjectGroupParams) (RenameSubjectGroupRow, error)
	// Clear a module's split, so the caller can write the new one in the same transaction.
	//
	// Delete-then-insert rather than a diff, because the entries only mean anything together: what
	// is being replaced is one statement about a module, not a set of independent rows. Inside a
	// transaction, so nobody reads the empty moment in between.
	ReplaceModuleComponents(ctx context.Context, moduleID uuid.UUID) error
	// Mark everything of one kind that a successful fetch did not mention.
	//
	// Only ever called after a fetch that succeeded and returned something — the client refuses an
	// empty result for exactly this reason. Rows are marked, never deleted.
	RetireMissingZPAObjects(ctx context.Context, arg RetireMissingZPAObjectsParams) ([]RetireMissingZPAObjectsRow, error)
	RevokeRole(ctx context.Context, arg RevokeRoleParams) error
	// A timestamp, not a DELETE: the audit log has to keep resolving this token id afterwards.
	// Idempotent — revoking twice keeps the first moment, which is the one that matters.
	RevokeToken(ctx context.Context, tokenID string) error
	// Revokes a token, but only the caller's own.
	//
	// Ownership is in the WHERE clause rather than in a read-then-write in Go, which collapses
	// three things into one: the check cannot race with a concurrent revocation, "no such token"
	// and "not your token" become the same empty result — the difference is not information the
	// caller is entitled to — and there is no window in which a token id has been confirmed to
	// exist before the write is refused.
	//
	// COALESCE keeps the first revocation moment. Revoking twice is not an error, and the moment
	// the audit log needs is the first one.
	RevokeTokenOfOwner(ctx context.Context, arg RevokeTokenOfOwnerParams) (RevokeTokenOfOwnerRow, error)
	// One person's grants as they actually are, expired ones included.
	//
	// Deliberately not filtered: this is the detail view, and "DEANS_OFFICE, granted on Tuesday
	// by X, expired on Wednesday" is the answer to the only question this table gets asked —
	// who could see what, when. The permission lookups above are the ones that filter.
	RoleGrantsByPerson(ctx context.Context, personID uuid.UUID) ([]RoleGrantsByPersonRow, error)
	// Which cohort year to propose for a new instance, from the regulations of its programme.
	//
	// The earliest the module may be taken in, across every version of that programme's regulations.
	// 23 of 1076 module/programme pairs disagree across versions, and the earliest is the one that
	// makes the instance appear where somebody looking for it expects it — the same choice the
	// catalogue projection makes for the same conflict.
	//
	// Zero means "the regulations do not say", which the CHECK on the column (1 to 12) makes an
	// unambiguous answer. COALESCE with the cast on the outside: without it sqlc types the aggregate
	// as an interface, and MIN over no rows is NULL, which is exactly the case this seeds for.
	SeedProgrammeSemester(ctx context.Context, arg SeedProgrammeSemesterParams) (int32, error)
	SemesterByCode(ctx context.Context, code string) (Semester, error)
	// Which semester a part belongs to, and whether its instance is still there.
	//
	// Needed before a write: the phase that decides whether wishes may be entered is the *semester's*
	// phase, and the part is all the caller names. One statement rather than three round trips
	// through the instance.
	SemesterOfInstancePart(ctx context.Context, id uuid.UUID) (SemesterOfInstancePartRow, error)
	// The recorded ones — the semesters somebody has decided something about. The ones nobody has
	// touched are not here to be listed, and the domain adds them from the calendar.
	//
	// Newest first, which for this code is also chronological: the year leads and SS sorts before
	// WS within a year, in the order the terms actually happen. Ordering by created_at instead
	// would list them by when somebody got round to entering them.
	Semesters(ctx context.Context) ([]Semester, error)
	SetInstancePartShared(ctx context.Context, arg SetInstancePartSharedParams) error
	// Deactivation is how a leaver loses access to everything at once, tokens included.
	//
	// The guard against deactivating the last administrator is not here. It cannot be: it depends
	// on a count over other rows, and a single statement that read that count would still race
	// with a concurrent deactivation. internal/store takes an advisory lock and checks first —
	// see AdminGrantLockKey.
	SetPersonActive(ctx context.Context, arg SetPersonActiveParams) error
	// Renaming somebody. Separate from the role and activity paths because it is the one edit
	// here that is not a permission change, and mixing it in would make every rename look like
	// one in the audit log.
	SetPersonName(ctx context.Context, arg SetPersonNameParams) error
	// Record that this faculty plans a programme, or no longer does.
	//
	// By code rather than by id: this is the one screen where somebody types what they mean, and the
	// code is what they mean. Returns no row for a code that names no programme, which the service
	// turns into the ordinary "no such programme".
	SetProgrammePlanningStatus(ctx context.Context, arg SetProgrammePlanningStatusParams) (SetProgrammePlanningStatusRow, error)
	// Retiring, and the way back. There is no delete: a group that was split still has to render in
	// the planning it was part of, and its module assignments are weeks of somebody's judgement.
	//
	// updated_at stays put when nothing changed, so retiring a group that is already retired does not
	// make the row look edited.
	SetSubjectGroupActive(ctx context.Context, arg SetSubjectGroupActiveParams) (SetSubjectGroupActiveRow, error)
	// The other parallel cohorts of one instance's module, in the same semester and programme.
	SiblingInstanceIDs(ctx context.Context, id uuid.UUID) ([]uuid.UUID, error)
	// The projection's own bookkeeping
	// --------------------------------
	// Written before the first statement, like the sync run it mirrors: a projection that crashed
	// leaves a row somebody can see rather than no row at all.
	StartCatalogueProjection(ctx context.Context, runID uuid.NullUUID) (StartCatalogueProjectionRow, error)
	// Written before the first fetch, not after the last one. A run that crashes then leaves a
	// RUNNING row somebody can see, rather than no row at all — which is indistinguishable from a
	// job that was never scheduled, and is how "the import stopped three weeks ago" happens.
	StartZPASyncRun(ctx context.Context, arg StartZPASyncRunParams) (ZpaSyncRun, error)
	SubjectGroupByID(ctx context.Context, id uuid.UUID) (SubjectGroupByIDRow, error)
	// Who leads each of these groups.
	//
	// The expiry filter is the same rule person_role_scope applies, applied again because this reads
	// the scope table directly for its people rather than the view for its ids. A lead whose grant
	// ran out is not a lead, and a screen that still showed them would be showing a permission that
	// no longer exists.
	SubjectGroupLeadsFor(ctx context.Context, groupIds []uuid.UUID) ([]SubjectGroupLeadsForRow, error)
	// Who is in each of these groups.
	//
	// No expiry filter, and the asymmetry with the query above is the point: membership is not a
	// grant. It says which subjects a colleague works in, it grants nothing, and it does not run out.
	SubjectGroupMembersFor(ctx context.Context, groupIds []uuid.UUID) ([]SubjectGroupMembersForRow, error)
	// Subject groups: the faculty's own grouping of modules and people.
	//
	// No semester anywhere in this file, and that is the shape of the thing rather than an omission.
	// A subject group is a statement about a subject; what is planned is derived through the module.
	// The list, newest decisions and all. Ordered by code, which is what a picker and a slide both
	// want and is stable between calls.
	//
	// The module count is a correlated subquery rather than a join with a GROUP BY, because the
	// other two things a group carries — its leads and its members — are read for a set of groups in
	// one statement each below. Three round trips for the whole screen, none of them per row.
	//
	// Counting modules is safe in a way counting anything over wishes never is: a module assignment
	// is catalogue data, and nobody is protected from it being known.
	SubjectGroups(ctx context.Context, includeInactive bool) ([]SubjectGroupsRow, error)
	// One person's memberships. What the wish screen offers first.
	//
	// Inactive groups are left out: a retired group is not a subject somebody is currently working
	// in, and offering it first would put a wound-up group at the top of the screen it exists to
	// shorten. The membership row survives, so bringing the group back brings the person back with
	// it.
	SubjectGroupsOfPerson(ctx context.Context, personID uuid.UUID) ([]SubjectGroupsOfPersonRow, error)
	// "Keine Fachgruppe ohne Person, die sich ihrer annimmt", as a number rather than as a NOT NULL.
	//
	// A constraint would mean a group could not be created before its lead was decided, and that a
	// lead could not be revoked without destroying the group. A count is the same requirement in the
	// form the beta testers can actually finish.
	SubjectGroupsWithoutLead(ctx context.Context) (int32, error)
	// One teacher and their account, by teacher id.
	//
	// No retired filter, unlike the list above. The id always comes from that list, so the only way
	// to be here with a retired teacher is that the import withdrew them between the screen loading
	// and somebody clicking — and answering "no such teacher" to a change that has already been
	// written would be a worse answer than the truth.
	TeacherAccountByID(ctx context.Context, teacherID uuid.UUID) (TeacherAccountByIDRow, error)
	// A handful of teachers by id, for attaching them to the modules they are responsible for.
	// COALESCE, and it is not cosmetic: three of the 257 carry no address, sqlc cannot know that a
	// cast is nullable, and scanning NULL into a string fails at runtime rather than at build time.
	// Empty means absent, which is what the domain type says too.
	TeachersByID(ctx context.Context, ids []uuid.UUID) ([]TeachersByIDRow, error)
	// The authentication query of the token door, in one round trip: the token, its owner and the
	// owner's roles.
	//
	// Permissions come from the person on every request, which is what makes "a token can never
	// exceed its owner's role" true by construction — revoking a role demotes every token that
	// person holds without touching a token row.
	//
	// Deliberately returns expired, revoked and inactive *tokens* instead of filtering them out.
	// Authentication has to tell "this token does not exist" from "this token expired" — the
	// caller owns the token and can be told why it stopped working — and a query that filters
	// would collapse both into the same silence. It also keeps the timing of the two cases
	// similar, which a WHERE clause on revoked_at would not.
	//
	// Expired *grants* are the opposite case and are filtered, exactly as in person.sql. The
	// distinction is who is being told what: the token's owner may learn why their credential
	// stopped working, but a grant the database considers over must not still take effect. The
	// filter belongs in the JOIN condition rather than a WHERE clause for the reason set out
	// there — a WHERE on the right-hand table of a LEFT JOIN makes it an inner one, which would
	// turn "this person has no live roles" into "this token does not exist".
	TokenByID(ctx context.Context, tokenID string) (TokenByIDRow, error)
	// Take away every programme of one grant, so the caller can write the new set in the same
	// transaction.
	//
	// Delete-then-insert rather than a diff: what is being replaced is one statement about who leads
	// what, and inside a transaction nobody reads the empty moment in between.
	UnassignProgrammes(ctx context.Context, arg UnassignProgrammesParams) error
	// The two things about an instance that are editable: which cohort it is, and which year.
	//
	// The module, the programme and the semester are not. Changing one of those is not an edit of
	// this instance, it is a different instance — and its parts, and later its wishes, belong to the
	// one that was declared.
	UpdateCourseInstance(ctx context.Context, arg UpdateCourseInstanceParams) error
	UpdateInstancePart(ctx context.Context, arg UpdateInstancePartParams) error
	// Correct one, or take it out of the lists with active = false.
	//
	// The home programme is not among the editable fields: it is what the permission is judged
	// against, so moving it would be moving the row out of the reach of the person doing it. The
	// WHERE clause names the source, so this can never touch an imported row — a mistyped id then
	// changes nothing rather than editing the catalogue.
	UpdateLocalModule(ctx context.Context, arg UpdateLocalModuleParams) (UpdateLocalModuleRow, error)
	// Register interest, or change your mind about something you already registered.
	//
	// An upsert rather than an insert that can fail: registering twice for the same part is not a
	// second wish and not an error, it is a correction. The unique constraint still exists — it is
	// what makes this one row per person per part — but the ordinary path never trips it.
	//
	// Only ever the caller's own row. person_id comes from the actor and never from the request; see
	// the header of migration 15.
	UpsertWish(ctx context.Context, arg UpsertWishParams) (Wish, error)
	// The cache of the examination office's module master data, its runs and its changes.
	//
	// The theme of this file is that a sync never deletes and never overwrites blindly. Every
	// write says what it expects to find, so that the difference between "unchanged", "changed",
	// "new" and "gone" is decided by the database against the row it actually holds, rather than
	// by Go against a row it read a moment ago.
	// One object, written whole.
	//
	// What kind of change this was — new, changed, or unchanged — is decided by the caller against
	// the hashes ZPAObjectStateByKind already returned, not here. Deciding it in SQL was the first
	// attempt and it was worse: it needed a subquery in RETURNING whose visibility rules are
	// subtle, to answer a question the caller had already answered for free.
	//
	// last_changed_at moves only when the content really differs, and that comparison is against
	// the generated content_hash — so it is the canonical jsonb form being compared, not whatever
	// key order arrived. A sync that changes nothing leaves every timestamp but last_seen_at
	// alone, which is what makes "what actually moved, and when" answerable months later.
	UpsertZPAObject(ctx context.Context, arg UpsertZPAObjectParams) (UpsertZPAObjectRow, error)
	// One wish, through the same filter. A detail view that skipped it would be the hole the list
	// does not have — and the realistic shape of that mistake is somebody adding a by-id lookup
	// because "it is only one row".
	WishByID(ctx context.Context, arg WishByIDParams) (WishByIDRow, error)
	// Wishes: one person's interest in one instance part.
	//
	// THE RULE THIS FILE IS MADE OF
	//
	// Every SELECT here carries the same four filter parameters, and they are not optional. The
	// visibility rule is a WHERE clause — internal/policy has it in two forms precisely so that this
	// one can run in the database — and a query written without it is not a slow query, it is a leak.
	//
	//     @scope = 'all'            no restriction
	//     @scope = 'own'            the caller's own entries
	//     @scope = 'own_or_scoped'  their own, plus the programmes and subject groups they lead
	//     anything else             nothing at all
	//
	// The last line is the important one: an unrecognised scope string matches no branch and
	// therefore no row, which is the same fail-closed reading WishFilter.Matches takes in its
	// default arm.
	//
	// WHAT IS NOT IN THIS FILE
	//
	// **There is no COUNT.** Not an oversight and not a gap to be filled: "3 Kolleg:innen haben
	// bereits Interesse" is the confidential fact with the names taken out, and an aggregate that
	// skipped the filter would be the same failure as a list that skipped it, only harder to notice.
	// Anybody who wants a number counts the rows they were allowed to see. There is nothing here that
	// could answer differently.
	//
	// store.TestEveryWishQueryIsFiltered reads this file and requires the predicate in every SELECT,
	// so a new query cannot quietly be written without it.
	// The wishes of one semester, filtered, with everything a screen needs to render a row.
	//
	// One query for the wish screen and for the planning screens both, because they differ only in
	// what the filter lets through — which is the property the whole design rests on. A second query
	// "for planners" would be a second place for the rule to be forgotten.
	//
	// The joins carry the two things the rule is scoped by. module_subject_group is a LEFT JOIN and
	// has to be: a module nobody has sorted into a subject group yet is the ordinary state until the
	// faculty has worked through its catalogue, and its wishes still belong to somebody.
	WishesInSemester(ctx context.Context, arg WishesInSemesterParams) ([]WishesInSemesterRow, error)
	ZPAChangesByRun(ctx context.Context, runID uuid.UUID) ([]ZPAChangesByRunRow, error)
	ZPAObjectPayload(ctx context.Context, arg ZPAObjectPayloadParams) (ZPAObjectPayloadRow, error)
	// What is currently held for one kind: enough to decide the diff without reading the payloads.
	//
	// The payload itself is fetched only for the objects that turn out to have changed, which
	// keeps a nightly run that changes nothing from moving 2.7 MB through the wire for no reason.
	ZPAObjectStateByKind(ctx context.Context, kind string) ([]ZPAObjectStateByKindRow, error)
	ZPASyncRunByID(ctx context.Context, id uuid.UUID) (ZPASyncRunByIDRow, error)
	ZPASyncRunKinds(ctx context.Context, runID uuid.UUID) ([]ZpaSyncRunKind, error)
	ZPASyncRuns(ctx context.Context, limit int32) ([]ZPASyncRunsRow, error)
}

var _ Querier = (*Queries)(nil)
