// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: semester.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const advanceSemesterPhase = `-- name: AdvanceSemesterPhase :one
UPDATE semester
SET phase = $2,
    updated_at = now()
WHERE id = $1
  AND phase = $3
RETURNING id, code, phase, wishes_published_at, created_at, updated_at,
       is_planning_semester, planning_set_at, planning_set_by, assignments_published_at
`

type AdvanceSemesterPhaseParams struct {
	ID      uuid.UUID
	Phase   string
	Phase_2 string
}

// Compare-and-set: $3 is the phase the caller believes the semester is in, and no rows come
// back if it has moved on since they looked.
//
// That is what makes "one step at a time" hold under concurrency. Without the second
// predicate, two switches issued together would both read DEMAND_PLANNING, and the second
// would write ASSIGNMENT over the first one's WISHES — a skipped phase, arrived at by nobody's
// decision, and invisible afterwards because the row looks like somebody chose it.
func (q *Queries) AdvanceSemesterPhase(ctx context.Context, arg AdvanceSemesterPhaseParams) (Semester, error) {
	row := q.db.QueryRow(ctx, advanceSemesterPhase, arg.ID, arg.Phase, arg.Phase_2)
	var i Semester
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Phase,
		&i.WishesPublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPlanningSemester,
		&i.PlanningSetAt,
		&i.PlanningSetBy,
		&i.AssignmentsPublishedAt,
	)
	return i, err
}

const clearPlanningSemester = `-- name: ClearPlanningSemester :exec
UPDATE semester
SET is_planning_semester = false,
    updated_at = now()
WHERE is_planning_semester
  AND id <> $1
`

// Take the mark off whichever semester carries it, except the one about to receive it.
//
// Runs first in the transaction that moves the mark, and that order is most of what makes
// concurrency boring: this UPDATE takes a row lock on the current planning semester, so two
// people setting different semesters at the same moment serialise here instead of colliding on
// the unique index afterwards. The second one wins, which is the right outcome for a decision
// somebody is taking on purpose.
//
// It is most of it and not all of it, and the gap is not visible from this statement. Under READ
// COMMITTED the caller that waited here re-evaluates the row it locked and does not rescan for
// rows that became eligible while it waited — so it can miss the mark the other transaction just
// set, and hit the unique index anyway. store.SetPlanningSemester retries once for that; the
// whole sequence is written out there.
//
// The exception for the target is not decoration: without it, setting the semester that is
// already set would clear the mark and then set it again, moving planning_set_at and making a
// no-op look like a decision.
func (q *Queries) ClearPlanningSemester(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearPlanningSemester, id)
	return err
}

const ensureSemester = `-- name: EnsureSemester :one

INSERT INTO semester (code)
VALUES ($1)
ON CONFLICT (code) DO UPDATE SET code = EXCLUDED.code
RETURNING id, code, phase, wishes_published_at, created_at, updated_at,
       is_planning_semester, planning_set_at, planning_set_by, assignments_published_at
`

// Semesters and the phase each one is in.
//
// Two of these are compare-and-set rather than plain updates, and that is the theme of the
// file. A phase advance and a publication are both "change this only if it is still what I
// think it is": the alternative is to read the row, decide in Go, and write — which is correct
// in a unit test and a race in production, because two people from the dean's office clicking
// at the same moment is precisely the situation a phase switch happens in.
// The row for a semester, created if this is the first decision anybody records about it.
//
// Nobody creates a semester — a semester is a name for a stretch of time and is there the way
// next March is there. The row holds the decisions taken about one, so it comes into existence
// with the first of them, and its defaults are what an untouched semester already means:
// DEMAND_PLANNING, wishes confidential.
//
// ON CONFLICT DO UPDATE rather than DO NOTHING, because DO NOTHING returns nothing when the
// row is already there and would need a second query to find out what it looks like — a race
// for the sake of a statement that reads slightly better. Assigning the code to itself is the
// idiom for "give me the row either way"; nothing is changed by it, and updated_at stays where
// it was so that arriving at a semester does not look like deciding something about it.
func (q *Queries) EnsureSemester(ctx context.Context, code string) (Semester, error) {
	row := q.db.QueryRow(ctx, ensureSemester, code)
	var i Semester
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Phase,
		&i.WishesPublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPlanningSemester,
		&i.PlanningSetAt,
		&i.PlanningSetBy,
		&i.AssignmentsPublishedAt,
	)
	return i, err
}

const markPlanningSemester = `-- name: MarkPlanningSemester :one
UPDATE semester
SET is_planning_semester = true,
    planning_set_at = now(),
    planning_set_by = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, code, phase, wishes_published_at, created_at, updated_at,
       is_planning_semester, planning_set_at, planning_set_by, assignments_published_at
`

type MarkPlanningSemesterParams struct {
	ID    uuid.UUID
	SetBy uuid.NullUUID
}

// Make this semester the one being planned.
//
// Unconditional and idempotent in effect: setting the semester that is already set rewrites the
// same values. planning_set_at moves, and that is intended — it records the most recent time
// somebody decided this, which is what a reader of the audit wants to know.
func (q *Queries) MarkPlanningSemester(ctx context.Context, arg MarkPlanningSemesterParams) (Semester, error) {
	row := q.db.QueryRow(ctx, markPlanningSemester, arg.ID, arg.SetBy)
	var i Semester
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Phase,
		&i.WishesPublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPlanningSemester,
		&i.PlanningSetAt,
		&i.PlanningSetBy,
		&i.AssignmentsPublishedAt,
	)
	return i, err
}

const planningSemester = `-- name: PlanningSemester :one
SELECT id, code, phase, wishes_published_at, created_at, updated_at,
       is_planning_semester, planning_set_at, planning_set_by, assignments_published_at
FROM semester
WHERE is_planning_semester
`

// The semester the faculty is planning, or no row while nobody has said.
//
// No LIMIT: the partial unique index makes "at most one" a property of the table rather than
// of this statement, and a LIMIT here would quietly return one of several if that ever stopped
// being true.
func (q *Queries) PlanningSemester(ctx context.Context) (Semester, error) {
	row := q.db.QueryRow(ctx, planningSemester)
	var i Semester
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Phase,
		&i.WishesPublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPlanningSemester,
		&i.PlanningSetAt,
		&i.PlanningSetBy,
		&i.AssignmentsPublishedAt,
	)
	return i, err
}

const publishSemesterAssignments = `-- name: PublishSemesterAssignments :one
UPDATE semester
SET assignments_published_at = COALESCE(assignments_published_at, now()),
    updated_at = CASE WHEN assignments_published_at IS NULL THEN now() ELSE updated_at END
WHERE id = $1
RETURNING id, code, phase, wishes_published_at, created_at, updated_at,
       is_planning_semester, planning_set_at, planning_set_by, assignments_published_at
`

// Idempotent, and it keeps the *first* timestamp. Same shape as PublishSemesterWishes, and the
// same argument: publishing twice is not an error, but the moment it happened is a fact about the
// process that a second call must not overwrite.
//
// A separate statement rather than a parameterised one over a column name, because the two marks
// are two decisions and a caller should not be able to reach the wrong one by passing a string.
func (q *Queries) PublishSemesterAssignments(ctx context.Context, id uuid.UUID) (Semester, error) {
	row := q.db.QueryRow(ctx, publishSemesterAssignments, id)
	var i Semester
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Phase,
		&i.WishesPublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPlanningSemester,
		&i.PlanningSetAt,
		&i.PlanningSetBy,
		&i.AssignmentsPublishedAt,
	)
	return i, err
}

const publishSemesterWishes = `-- name: PublishSemesterWishes :one
UPDATE semester
SET wishes_published_at = COALESCE(wishes_published_at, now()),
    updated_at = CASE WHEN wishes_published_at IS NULL THEN now() ELSE updated_at END
WHERE id = $1
RETURNING id, code, phase, wishes_published_at, created_at, updated_at,
       is_planning_semester, planning_set_at, planning_set_by, assignments_published_at
`

// Idempotent, and it keeps the *first* timestamp.
//
// Publishing twice is not an error — the second caller wanted the wishes published and they
// are — but the moment it happened is a fact about the process that a second call must not
// overwrite. COALESCE does both in one statement, so there is no window between checking and
// writing.
//
// updated_at stays untouched when nothing changed, so a repeated call does not make the row
// look edited.
func (q *Queries) PublishSemesterWishes(ctx context.Context, id uuid.UUID) (Semester, error) {
	row := q.db.QueryRow(ctx, publishSemesterWishes, id)
	var i Semester
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Phase,
		&i.WishesPublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPlanningSemester,
		&i.PlanningSetAt,
		&i.PlanningSetBy,
		&i.AssignmentsPublishedAt,
	)
	return i, err
}

const semesterByCode = `-- name: SemesterByCode :one
SELECT id, code, phase, wishes_published_at, created_at, updated_at,
       is_planning_semester, planning_set_at, planning_set_by, assignments_published_at
FROM semester
WHERE code = $1
`

func (q *Queries) SemesterByCode(ctx context.Context, code string) (Semester, error) {
	row := q.db.QueryRow(ctx, semesterByCode, code)
	var i Semester
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Phase,
		&i.WishesPublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPlanningSemester,
		&i.PlanningSetAt,
		&i.PlanningSetBy,
		&i.AssignmentsPublishedAt,
	)
	return i, err
}

const semesters = `-- name: Semesters :many
SELECT id, code, phase, wishes_published_at, created_at, updated_at,
       is_planning_semester, planning_set_at, planning_set_by, assignments_published_at
FROM semester
ORDER BY code DESC
`

// The recorded ones — the semesters somebody has decided something about. The ones nobody has
// touched are not here to be listed, and the domain adds them from the calendar.
//
// Newest first, which for this code is also chronological: the year leads and SS sorts before
// WS within a year, in the order the terms actually happen. Ordering by created_at instead
// would list them by when somebody got round to entering them.
func (q *Queries) Semesters(ctx context.Context) ([]Semester, error) {
	rows, err := q.db.Query(ctx, semesters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Semester{}
	for rows.Next() {
		var i Semester
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Phase,
			&i.WishesPublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsPlanningSemester,
			&i.PlanningSetAt,
			&i.PlanningSetBy,
			&i.AssignmentsPublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
