// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: subject_group.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addSubjectGroupLead = `-- name: AddSubjectGroupLead :exec
INSERT INTO person_subject_group_scope (person_id, role, subject_group_id, granted_by)
VALUES ($1, 'SUBJECT_GROUP_LEAD', $2, $3)
ON CONFLICT (person_id, role, subject_group_id) DO NOTHING
`

type AddSubjectGroupLeadParams struct {
	PersonID       uuid.UUID
	SubjectGroupID uuid.UUID
	GrantedBy      uuid.NullUUID
}

// The foreign key to person_role is what refuses a lead who does not hold the role. The service
// checks first so that the ordinary case gets a sentence; this is the race the constraint closes.
func (q *Queries) AddSubjectGroupLead(ctx context.Context, arg AddSubjectGroupLeadParams) error {
	_, err := q.db.Exec(ctx, addSubjectGroupLead, arg.PersonID, arg.SubjectGroupID, arg.GrantedBy)
	return err
}

const addSubjectGroupMembership = `-- name: AddSubjectGroupMembership :exec
INSERT INTO person_subject_group (person_id, subject_group_id, granted_by)
VALUES ($1, $2, $3)
ON CONFLICT (person_id, subject_group_id) DO NOTHING
`

type AddSubjectGroupMembershipParams struct {
	PersonID       uuid.UUID
	SubjectGroupID uuid.UUID
	GrantedBy      uuid.NullUUID
}

func (q *Queries) AddSubjectGroupMembership(ctx context.Context, arg AddSubjectGroupMembershipParams) error {
	_, err := q.db.Exec(ctx, addSubjectGroupMembership, arg.PersonID, arg.SubjectGroupID, arg.GrantedBy)
	return err
}

const assignModulesToSubjectGroup = `-- name: AssignModulesToSubjectGroup :execrows
INSERT INTO module_subject_group (module_id, subject_group_id, assigned_by)
SELECT m, $1::uuid, $2::uuid
FROM unnest($3::uuid[]) AS m
ON CONFLICT (module_id) DO UPDATE
SET subject_group_id = EXCLUDED.subject_group_id,
    assigned_at = now(),
    assigned_by = EXCLUDED.assigned_by
`

type AssignModulesToSubjectGroupParams struct {
	SubjectGroupID uuid.UUID
	AssignedBy     uuid.NullUUID
	ModuleIds      []uuid.UUID
}

// A batch, because the task this exists for is assigning 506 modules and a screen that saves one
// row per click is a task nobody finishes.
//
// An upsert rather than delete-then-insert: moving a module between groups is one statement, so
// there is no moment in which the module belongs to nothing. assigned_by moves with it, because
// the question this column answers — who says this module is mathematics — is about the current
// assignment and not about the first one.
func (q *Queries) AssignModulesToSubjectGroup(ctx context.Context, arg AssignModulesToSubjectGroupParams) (int64, error) {
	result, err := q.db.Exec(ctx, assignModulesToSubjectGroup, arg.SubjectGroupID, arg.AssignedBy, arg.ModuleIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearModulesSubjectGroup = `-- name: ClearModulesSubjectGroup :execrows
DELETE FROM module_subject_group
WHERE module_id = ANY ($1::uuid[])
`

// Taking modules out of every group, which is the same screen's other button. A module with no
// group is a normal state and the whole of October's work list.
func (q *Queries) ClearModulesSubjectGroup(ctx context.Context, moduleIds []uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, clearModulesSubjectGroup, moduleIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearSubjectGroupLeads = `-- name: ClearSubjectGroupLeads :exec
DELETE FROM person_subject_group_scope
WHERE subject_group_id = $1 AND role = 'SUBJECT_GROUP_LEAD'
`

func (q *Queries) ClearSubjectGroupLeads(ctx context.Context, subjectGroupID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearSubjectGroupLeads, subjectGroupID)
	return err
}

const clearSubjectGroupMembers = `-- name: ClearSubjectGroupMembers :exec
DELETE FROM person_subject_group WHERE subject_group_id = $1
`

func (q *Queries) ClearSubjectGroupMembers(ctx context.Context, subjectGroupID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearSubjectGroupMembers, subjectGroupID)
	return err
}

const createSubjectGroup = `-- name: CreateSubjectGroup :one
INSERT INTO subject_group (code, name)
VALUES ($1, $2)
RETURNING id, code, name, active, created_at, updated_at, 0::int AS module_count
`

type CreateSubjectGroupParams struct {
	Code string
	Name string
}

type CreateSubjectGroupRow struct {
	ID          uuid.UUID
	Code        string
	Name        string
	Active      bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ModuleCount int32
}

func (q *Queries) CreateSubjectGroup(ctx context.Context, arg CreateSubjectGroupParams) (CreateSubjectGroupRow, error) {
	row := q.db.QueryRow(ctx, createSubjectGroup, arg.Code, arg.Name)
	var i CreateSubjectGroupRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModuleCount,
	)
	return i, err
}

const modulesWithoutSubjectGroup = `-- name: ModulesWithoutSubjectGroup :one
SELECT count(*)::int
FROM module m
LEFT JOIN module_subject_group g ON g.module_id = m.id
WHERE g.module_id IS NULL AND m.retired_at IS NULL AND m.active
`

// The work list as a number: "37 modules still have no subject group".
//
// Retired modules do not count. A module the examination office stopped publishing is not work
// anybody has to finish, and counting it would make the list unfinishable.
func (q *Queries) ModulesWithoutSubjectGroup(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, modulesWithoutSubjectGroup)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const renameSubjectGroup = `-- name: RenameSubjectGroup :one
UPDATE subject_group
SET name = $2, updated_at = now()
WHERE id = $1
RETURNING id, code, name, active, created_at, updated_at,
          (SELECT count(*) FROM module_subject_group m WHERE m.subject_group_id = subject_group.id)::int
              AS module_count
`

type RenameSubjectGroupParams struct {
	ID   uuid.UUID
	Name string
}

type RenameSubjectGroupRow struct {
	ID          uuid.UUID
	Code        string
	Name        string
	Active      bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ModuleCount int32
}

// The name only. The code is the address — it is in URLs and in colleagues' scripts — and
// changing it is not a rename but a different group.
func (q *Queries) RenameSubjectGroup(ctx context.Context, arg RenameSubjectGroupParams) (RenameSubjectGroupRow, error) {
	row := q.db.QueryRow(ctx, renameSubjectGroup, arg.ID, arg.Name)
	var i RenameSubjectGroupRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModuleCount,
	)
	return i, err
}

const setSubjectGroupActive = `-- name: SetSubjectGroupActive :one
UPDATE subject_group
SET active = $2,
    updated_at = CASE WHEN active IS DISTINCT FROM $2 THEN now() ELSE updated_at END
WHERE id = $1
RETURNING id, code, name, active, created_at, updated_at,
          (SELECT count(*) FROM module_subject_group m WHERE m.subject_group_id = subject_group.id)::int
              AS module_count
`

type SetSubjectGroupActiveParams struct {
	ID     uuid.UUID
	Active bool
}

type SetSubjectGroupActiveRow struct {
	ID          uuid.UUID
	Code        string
	Name        string
	Active      bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ModuleCount int32
}

// Retiring, and the way back. There is no delete: a group that was split still has to render in
// the planning it was part of, and its module assignments are weeks of somebody's judgement.
//
// updated_at stays put when nothing changed, so retiring a group that is already retired does not
// make the row look edited.
func (q *Queries) SetSubjectGroupActive(ctx context.Context, arg SetSubjectGroupActiveParams) (SetSubjectGroupActiveRow, error) {
	row := q.db.QueryRow(ctx, setSubjectGroupActive, arg.ID, arg.Active)
	var i SetSubjectGroupActiveRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModuleCount,
	)
	return i, err
}

const subjectGroupByID = `-- name: SubjectGroupByID :one
SELECT
    g.id, g.code, g.name, g.active, g.created_at, g.updated_at,
    (SELECT count(*) FROM module_subject_group m WHERE m.subject_group_id = g.id)::int
        AS module_count
FROM subject_group g
WHERE g.id = $1
`

type SubjectGroupByIDRow struct {
	ID          uuid.UUID
	Code        string
	Name        string
	Active      bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ModuleCount int32
}

func (q *Queries) SubjectGroupByID(ctx context.Context, id uuid.UUID) (SubjectGroupByIDRow, error) {
	row := q.db.QueryRow(ctx, subjectGroupByID, id)
	var i SubjectGroupByIDRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModuleCount,
	)
	return i, err
}

const subjectGroupLeadsFor = `-- name: SubjectGroupLeadsFor :many
SELECT
    s.subject_group_id,
    p.id, p.mail, p.name,
    COALESCE(t.short_name, '')::text AS sort_name,
    p.active
FROM person_subject_group_scope s
JOIN person p ON p.id = s.person_id
JOIN person_role r ON r.person_id = s.person_id AND r.role = s.role
LEFT JOIN teacher t ON t.mail = p.mail
WHERE s.subject_group_id = ANY ($1::uuid[])
  AND (r.expires_at IS NULL OR r.expires_at > now())
ORDER BY s.subject_group_id, COALESCE(NULLIF(t.short_name, ''), p.name), p.mail
`

type SubjectGroupLeadsForRow struct {
	SubjectGroupID uuid.UUID
	ID             uuid.UUID
	Mail           string
	Name           string
	SortName       string
	Active         bool
}

// Who leads each of these groups.
//
// The expiry filter is the same rule person_role_scope applies, applied again because this reads
// the scope table directly for its people rather than the view for its ids. A lead whose grant
// ran out is not a lead, and a screen that still showed them would be showing a permission that
// no longer exists.
func (q *Queries) SubjectGroupLeadsFor(ctx context.Context, groupIds []uuid.UUID) ([]SubjectGroupLeadsForRow, error) {
	rows, err := q.db.Query(ctx, subjectGroupLeadsFor, groupIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubjectGroupLeadsForRow{}
	for rows.Next() {
		var i SubjectGroupLeadsForRow
		if err := rows.Scan(
			&i.SubjectGroupID,
			&i.ID,
			&i.Mail,
			&i.Name,
			&i.SortName,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subjectGroupMembersFor = `-- name: SubjectGroupMembersFor :many
SELECT
    s.subject_group_id,
    p.id, p.mail, p.name,
    COALESCE(t.short_name, '')::text AS sort_name,
    p.active
FROM person_subject_group s
JOIN person p ON p.id = s.person_id
LEFT JOIN teacher t ON t.mail = p.mail
WHERE s.subject_group_id = ANY ($1::uuid[])
ORDER BY s.subject_group_id, COALESCE(NULLIF(t.short_name, ''), p.name), p.mail
`

type SubjectGroupMembersForRow struct {
	SubjectGroupID uuid.UUID
	ID             uuid.UUID
	Mail           string
	Name           string
	SortName       string
	Active         bool
}

// Who is in each of these groups.
//
// No expiry filter, and the asymmetry with the query above is the point: membership is not a
// grant. It says which subjects a colleague works in, it grants nothing, and it does not run out.
func (q *Queries) SubjectGroupMembersFor(ctx context.Context, groupIds []uuid.UUID) ([]SubjectGroupMembersForRow, error) {
	rows, err := q.db.Query(ctx, subjectGroupMembersFor, groupIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubjectGroupMembersForRow{}
	for rows.Next() {
		var i SubjectGroupMembersForRow
		if err := rows.Scan(
			&i.SubjectGroupID,
			&i.ID,
			&i.Mail,
			&i.Name,
			&i.SortName,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subjectGroups = `-- name: SubjectGroups :many

SELECT
    g.id, g.code, g.name, g.active, g.created_at, g.updated_at,
    (SELECT count(*) FROM module_subject_group m WHERE m.subject_group_id = g.id)::int
        AS module_count
FROM subject_group g
WHERE $1::boolean OR g.active
ORDER BY g.code
`

type SubjectGroupsRow struct {
	ID          uuid.UUID
	Code        string
	Name        string
	Active      bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ModuleCount int32
}

// Subject groups: the faculty's own grouping of modules and people.
//
// No semester anywhere in this file, and that is the shape of the thing rather than an omission.
// A subject group is a statement about a subject; what is planned is derived through the module.
// The list, newest decisions and all. Ordered by code, which is what a picker and a slide both
// want and is stable between calls.
//
// The module count is a correlated subquery rather than a join with a GROUP BY, because the
// other two things a group carries — its leads and its members — are read for a set of groups in
// one statement each below. Three round trips for the whole screen, none of them per row.
//
// Counting modules is safe in a way counting anything over wishes never is: a module assignment
// is catalogue data, and nobody is protected from it being known.
func (q *Queries) SubjectGroups(ctx context.Context, includeInactive bool) ([]SubjectGroupsRow, error) {
	rows, err := q.db.Query(ctx, subjectGroups, includeInactive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubjectGroupsRow{}
	for rows.Next() {
		var i SubjectGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ModuleCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subjectGroupsOfPerson = `-- name: SubjectGroupsOfPerson :many
SELECT
    g.id, g.code, g.name, g.active, g.created_at, g.updated_at,
    (SELECT count(*) FROM module_subject_group m WHERE m.subject_group_id = g.id)::int
        AS module_count
FROM person_subject_group s
JOIN subject_group g ON g.id = s.subject_group_id
WHERE s.person_id = $1 AND g.active
ORDER BY g.code
`

type SubjectGroupsOfPersonRow struct {
	ID          uuid.UUID
	Code        string
	Name        string
	Active      bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ModuleCount int32
}

// One person's memberships. What the wish screen offers first.
//
// Inactive groups are left out: a retired group is not a subject somebody is currently working
// in, and offering it first would put a wound-up group at the top of the screen it exists to
// shorten. The membership row survives, so bringing the group back brings the person back with
// it.
func (q *Queries) SubjectGroupsOfPerson(ctx context.Context, personID uuid.UUID) ([]SubjectGroupsOfPersonRow, error) {
	rows, err := q.db.Query(ctx, subjectGroupsOfPerson, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubjectGroupsOfPersonRow{}
	for rows.Next() {
		var i SubjectGroupsOfPersonRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ModuleCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subjectGroupsWithoutLead = `-- name: SubjectGroupsWithoutLead :one
SELECT count(*)::int
FROM subject_group g
WHERE g.active
  AND NOT EXISTS (
      SELECT 1
      FROM person_subject_group_scope s
      JOIN person_role r ON r.person_id = s.person_id AND r.role = s.role
      WHERE s.subject_group_id = g.id
        AND (r.expires_at IS NULL OR r.expires_at > now())
  )
`

// "Keine Fachgruppe ohne Person, die sich ihrer annimmt", as a number rather than as a NOT NULL.
//
// A constraint would mean a group could not be created before its lead was decided, and that a
// lead could not be revoked without destroying the group. A count is the same requirement in the
// form the beta testers can actually finish.
func (q *Queries) SubjectGroupsWithoutLead(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, subjectGroupsWithoutLead)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
