// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: wish.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOwnWish = `-- name: DeleteOwnWish :execrows
DELETE FROM wish WHERE id = $1 AND person_id = $2
`

type DeleteOwnWishParams struct {
	ID       uuid.UUID
	PersonID uuid.UUID
}

// Withdraw one's own wish.
//
// Ownership is in the WHERE clause rather than in a read-then-write in Go, which collapses three
// things into one, exactly as RevokeTokenOfOwner does: the check cannot race with a concurrent
// change, "no such wish" and "not your wish" become the same empty result — the difference is
// not information the caller is entitled to — and there is no window in which an id has been
// confirmed to exist before the write is refused.
func (q *Queries) DeleteOwnWish(ctx context.Context, arg DeleteOwnWishParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOwnWish, arg.ID, arg.PersonID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const semesterOfCourseInstance = `-- name: SemesterOfCourseInstance :one
SELECT s.id, s.code, s.phase, s.wishes_published_at
FROM course_instance ci
JOIN semester s ON s.id = ci.semester_id
WHERE ci.id = $1
`

type SemesterOfCourseInstanceRow struct {
	ID                uuid.UUID
	Code              string
	Phase             string
	WishesPublishedAt pgtype.Timestamptz
}

// Which semester an instance belongs to, and whether it is still there.
//
// Needed before a write: the phase that decides whether wishes may be entered is the *semester's*
// phase, and the instance is all the caller names. One statement rather than two round trips, and
// an empty result is the answer to both questions at once — an instance that has been withdrawn
// has no semester to ask about.
func (q *Queries) SemesterOfCourseInstance(ctx context.Context, id uuid.UUID) (SemesterOfCourseInstanceRow, error) {
	row := q.db.QueryRow(ctx, semesterOfCourseInstance, id)
	var i SemesterOfCourseInstanceRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Phase,
		&i.WishesPublishedAt,
	)
	return i, err
}

const upsertWish = `-- name: UpsertWish :one
INSERT INTO wish (course_instance_id, person_id, priority, note)
VALUES ($1, $2, $3, $4)
ON CONFLICT (course_instance_id, person_id) DO UPDATE
SET priority = EXCLUDED.priority,
    note = EXCLUDED.note,
    updated_at = now()
RETURNING id, course_instance_id, person_id, priority, note, created_at, updated_at
`

type UpsertWishParams struct {
	CourseInstanceID uuid.UUID
	PersonID         uuid.UUID
	Priority         int16
	Note             string
}

type UpsertWishRow struct {
	ID               uuid.UUID
	CourseInstanceID uuid.UUID
	PersonID         uuid.UUID
	Priority         int16
	Note             string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

// Register interest, or change your mind about something you already registered.
//
// An upsert rather than an insert that can fail: registering twice for the same instance is not a
// second wish and not an error, it is a correction. The unique constraint still exists — it is
// what makes this one row per person per instance — but the ordinary path never trips it.
//
// Only ever the caller's own row. person_id comes from the actor and never from the request; see
// the header of migration 15.
func (q *Queries) UpsertWish(ctx context.Context, arg UpsertWishParams) (UpsertWishRow, error) {
	row := q.db.QueryRow(ctx, upsertWish,
		arg.CourseInstanceID,
		arg.PersonID,
		arg.Priority,
		arg.Note,
	)
	var i UpsertWishRow
	err := row.Scan(
		&i.ID,
		&i.CourseInstanceID,
		&i.PersonID,
		&i.Priority,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const wishByID = `-- name: WishByID :one
SELECT
    w.id, w.course_instance_id, w.person_id, w.priority, w.note, w.created_at, w.updated_at,
    ci.track, ci.programme_semester,
    sem.code AS semester_code, sem.phase AS semester_phase,
    prog.id AS programme_id, prog.code AS programme_code, prog.title AS programme_title,
    m.id AS module_id, m.name AS module_name,
    person.mail AS person_mail, person.name AS person_name,
    COALESCE(t.short_name, '')::text AS person_sort_name
FROM wish w
JOIN course_instance ci ON ci.id = w.course_instance_id
JOIN semester sem ON sem.id = ci.semester_id
JOIN programme prog ON prog.id = ci.programme_id
JOIN module m ON m.id = ci.module_id
LEFT JOIN module_subject_group msg ON msg.module_id = m.id
JOIN person ON person.id = w.person_id
LEFT JOIN teacher t ON t.mail = person.mail
WHERE w.id = $1::uuid
  AND (
      $2::text = 'all'
      OR ($2::text = 'own'
          AND w.person_id = $3::uuid)
      OR ($2::text = 'own_or_scoped'
          AND (w.person_id = $3::uuid
               OR prog.id = ANY ($4::uuid[])
               OR msg.subject_group_id = ANY ($5::uuid[])))
  )
`

type WishByIDParams struct {
	ID              uuid.UUID
	Scope           string
	OwnerID         uuid.UUID
	ProgrammeIds    []uuid.UUID
	SubjectGroupIds []uuid.UUID
}

type WishByIDRow struct {
	ID                uuid.UUID
	CourseInstanceID  uuid.UUID
	PersonID          uuid.UUID
	Priority          int16
	Note              string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	Track             string
	ProgrammeSemester *int32
	SemesterCode      string
	SemesterPhase     string
	ProgrammeID       uuid.UUID
	ProgrammeCode     string
	ProgrammeTitle    string
	ModuleID          uuid.UUID
	ModuleName        string
	PersonMail        string
	PersonName        string
	PersonSortName    string
}

// One wish, through the same filter. A detail view that skipped it would be the hole the list
// does not have — and the realistic shape of that mistake is somebody adding a by-id lookup
// because "it is only one row".
func (q *Queries) WishByID(ctx context.Context, arg WishByIDParams) (WishByIDRow, error) {
	row := q.db.QueryRow(ctx, wishByID,
		arg.ID,
		arg.Scope,
		arg.OwnerID,
		arg.ProgrammeIds,
		arg.SubjectGroupIds,
	)
	var i WishByIDRow
	err := row.Scan(
		&i.ID,
		&i.CourseInstanceID,
		&i.PersonID,
		&i.Priority,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Track,
		&i.ProgrammeSemester,
		&i.SemesterCode,
		&i.SemesterPhase,
		&i.ProgrammeID,
		&i.ProgrammeCode,
		&i.ProgrammeTitle,
		&i.ModuleID,
		&i.ModuleName,
		&i.PersonMail,
		&i.PersonName,
		&i.PersonSortName,
	)
	return i, err
}

const wishesOfSemester = `-- name: WishesOfSemester :many

SELECT
    w.id, w.course_instance_id, w.person_id, w.priority, w.note, w.created_at, w.updated_at,
    ci.track, ci.programme_semester,
    sem.code AS semester_code, sem.phase AS semester_phase,
    prog.id AS programme_id, prog.code AS programme_code, prog.title AS programme_title,
    m.id AS module_id, m.name AS module_name,
    person.mail AS person_mail, person.name AS person_name,
    COALESCE(t.short_name, '')::text AS person_sort_name
FROM wish w
JOIN course_instance ci ON ci.id = w.course_instance_id
JOIN semester sem ON sem.id = ci.semester_id
JOIN programme prog ON prog.id = ci.programme_id
JOIN module m ON m.id = ci.module_id
LEFT JOIN module_subject_group msg ON msg.module_id = m.id
JOIN person ON person.id = w.person_id
LEFT JOIN teacher t ON t.mail = person.mail
WHERE ($1::uuid IS NULL
       OR ci.semester_id = $1::uuid)
  AND ($2::text IS NULL OR prog.code = $2::text)
  AND ($3::uuid IS NULL OR m.id = $3::uuid)
  AND ($4::uuid IS NULL OR ci.id = $4::uuid)
  AND ($5::uuid IS NULL OR w.person_id = $5::uuid)
  AND (
      $6::text = 'all'
      OR ($6::text = 'own'
          AND w.person_id = $7::uuid)
      OR ($6::text = 'own_or_scoped'
          AND (w.person_id = $7::uuid
               OR prog.id = ANY ($8::uuid[])
               OR msg.subject_group_id = ANY ($9::uuid[])))
  )
ORDER BY sem.code, m.name, ci.track, w.priority,
         COALESCE(NULLIF(t.short_name, ''), person.name), w.id
`

type WishesOfSemesterParams struct {
	SemesterID      uuid.NullUUID
	Programme       *string
	Module          uuid.NullUUID
	Instance        uuid.NullUUID
	Person          uuid.NullUUID
	Scope           string
	OwnerID         uuid.UUID
	ProgrammeIds    []uuid.UUID
	SubjectGroupIds []uuid.UUID
}

type WishesOfSemesterRow struct {
	ID                uuid.UUID
	CourseInstanceID  uuid.UUID
	PersonID          uuid.UUID
	Priority          int16
	Note              string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	Track             string
	ProgrammeSemester *int32
	SemesterCode      string
	SemesterPhase     string
	ProgrammeID       uuid.UUID
	ProgrammeCode     string
	ProgrammeTitle    string
	ModuleID          uuid.UUID
	ModuleName        string
	PersonMail        string
	PersonName        string
	PersonSortName    string
}

// Wishes: one person's interest in one course instance.
//
// # THE RULE THIS FILE IS MADE OF
//
// Every SELECT here carries the same four filter parameters, and they are not optional. The
// visibility rule is a WHERE clause — internal/policy has it in two forms precisely so that this
// one can run in the database — and a query written without it is not a slow query, it is a leak.
//
//	@scope = 'all'            no restriction
//	@scope = 'own'            the caller's own entries
//	@scope = 'own_or_scoped'  their own, plus the programmes and subject groups they lead
//	anything else             nothing at all
//
// The last line is the important one: an unrecognised scope string matches no branch and
// therefore no row, which is the same fail-closed reading WishFilter.Matches takes in its
// default arm.
//
// # WHAT IS NOT IN THIS FILE
//
// **There is no COUNT.** Not an oversight and not a gap to be filled: "3 Kolleg:innen haben
// bereits Interesse" is the confidential fact with the names taken out, and an aggregate that
// skipped the filter would be the same failure as a list that skipped it, only harder to notice.
// Anybody who wants a number counts the rows they were allowed to see. There is nothing here that
// could answer differently.
//
// store.TestEveryWishQueryIsFiltered reads this file and requires the predicate in every SELECT,
// so a new query cannot quietly be written without it.
// The wishes of one semester — or of every semester — filtered, with everything a screen needs to
// render a row.
//
// The semester is optional, and there is exactly one caller allowed to leave it out: "my own
// entries, everywhere". That question does not depend on the confidentiality rule at all, so it
// needs no semester to read a publication date from. Every other caller passes one, because the
// rule *is* per semester — one may be published and the next not — and a filter built without
// knowing which would be a filter for the wrong one.
//
// One query for the wish screen and for the planning screens both, because they differ only in
// what the filter lets through — which is the property the whole design rests on. A second query
// "for planners" would be a second place for the rule to be forgotten.
//
// The joins carry the two things the rule is scoped by — the programme of the instance and the
// subject group of its module. module_subject_group is a LEFT JOIN and has to be: a module nobody has sorted into a subject group yet is the ordinary state until the
// faculty has worked through its catalogue, and its wishes still belong to somebody.
// The semester first, because the list across all of them is grouped by it — and because the
// code sorts chronologically as text, which is what its format is for.
func (q *Queries) WishesOfSemester(ctx context.Context, arg WishesOfSemesterParams) ([]WishesOfSemesterRow, error) {
	rows, err := q.db.Query(ctx, wishesOfSemester,
		arg.SemesterID,
		arg.Programme,
		arg.Module,
		arg.Instance,
		arg.Person,
		arg.Scope,
		arg.OwnerID,
		arg.ProgrammeIds,
		arg.SubjectGroupIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WishesOfSemesterRow{}
	for rows.Next() {
		var i WishesOfSemesterRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseInstanceID,
			&i.PersonID,
			&i.Priority,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Track,
			&i.ProgrammeSemester,
			&i.SemesterCode,
			&i.SemesterPhase,
			&i.ProgrammeID,
			&i.ProgrammeCode,
			&i.ProgrammeTitle,
			&i.ModuleID,
			&i.ModuleName,
			&i.PersonMail,
			&i.PersonName,
			&i.PersonSortName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
