// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: zpa.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const failAbandonedZPASyncRuns = `-- name: FailAbandonedZPASyncRuns :many
UPDATE zpa_sync_run
SET status      = 'FAILED',
    finished_at = now(),
    error       = 'der Prozess wurde beendet, bevor der Lauf fertig war'
WHERE status = 'RUNNING'
  AND started_at < $1::timestamptz
RETURNING id
`

// Called at startup, beside the protected-admin reconciliation.
//
// A process that dies mid-sync leaves a RUNNING row forever, and forever is long enough that
// the interface would show a run in progress that nothing is progressing. The cutoff is passed
// in rather than hard-coded here so the caller's reasoning about it stays in Go.
func (q *Queries) FailAbandonedZPASyncRuns(ctx context.Context, olderThan time.Time) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, failAbandonedZPASyncRuns, olderThan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishZPASyncRun = `-- name: FinishZPASyncRun :one
UPDATE zpa_sync_run
SET status      = $2,
    finished_at = now(),
    fetched     = $3,
    appeared    = $4,
    changed     = $5,
    disappeared = $6,
    error       = $7
WHERE id = $1
RETURNING id, trigger, started_by, started_at, finished_at, status,
          fetched, appeared, changed, disappeared, error
`

type FinishZPASyncRunParams struct {
	ID          uuid.UUID
	Status      string
	Fetched     int32
	Appeared    int32
	Changed     int32
	Disappeared int32
	Error       *string
}

func (q *Queries) FinishZPASyncRun(ctx context.Context, arg FinishZPASyncRunParams) (ZpaSyncRun, error) {
	row := q.db.QueryRow(ctx, finishZPASyncRun,
		arg.ID,
		arg.Status,
		arg.Fetched,
		arg.Appeared,
		arg.Changed,
		arg.Disappeared,
		arg.Error,
	)
	var i ZpaSyncRun
	err := row.Scan(
		&i.ID,
		&i.Trigger,
		&i.StartedBy,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.Fetched,
		&i.Appeared,
		&i.Changed,
		&i.Disappeared,
		&i.Error,
	)
	return i, err
}

const lastSuccessfulZPASyncRun = `-- name: LastSuccessfulZPASyncRun :one
SELECT r.id, r.trigger, r.started_by, p.name AS started_by_name, r.started_at,
       r.finished_at, r.status, r.fetched, r.appeared, r.changed, r.disappeared, r.error
FROM zpa_sync_run r
LEFT JOIN person p ON p.id = r.started_by
WHERE r.status IN ('SUCCEEDED', 'PARTIAL')
ORDER BY r.started_at DESC
LIMIT 1
`

type LastSuccessfulZPASyncRunRow struct {
	ID            uuid.UUID
	Trigger       string
	StartedBy     uuid.NullUUID
	StartedByName *string
	StartedAt     time.Time
	FinishedAt    pgtype.Timestamptz
	Status        string
	Fetched       int32
	Appeared      int32
	Changed       int32
	Disappeared   int32
	Error         *string
}

// The one number the interface shows largest, and the one the deploy smoke check asserts is
// recent. PARTIAL counts: it fetched something, and a run that got three of four endpoints is
// not the silence this is watching for.
func (q *Queries) LastSuccessfulZPASyncRun(ctx context.Context) (LastSuccessfulZPASyncRunRow, error) {
	row := q.db.QueryRow(ctx, lastSuccessfulZPASyncRun)
	var i LastSuccessfulZPASyncRunRow
	err := row.Scan(
		&i.ID,
		&i.Trigger,
		&i.StartedBy,
		&i.StartedByName,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.Fetched,
		&i.Appeared,
		&i.Changed,
		&i.Disappeared,
		&i.Error,
	)
	return i, err
}

const recordZPAChange = `-- name: RecordZPAChange :exec
INSERT INTO zpa_change (run_id, object_id, kind, zpa_id, label, change,
                        payload_before, payload_after, changed_keys)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type RecordZPAChangeParams struct {
	RunID         uuid.UUID
	ObjectID      uuid.UUID
	Kind          string
	ZpaID         int64
	Label         *string
	Change        string
	PayloadBefore []byte
	PayloadAfter  []byte
	ChangedKeys   []string
}

func (q *Queries) RecordZPAChange(ctx context.Context, arg RecordZPAChangeParams) error {
	_, err := q.db.Exec(ctx, recordZPAChange,
		arg.RunID,
		arg.ObjectID,
		arg.Kind,
		arg.ZpaID,
		arg.Label,
		arg.Change,
		arg.PayloadBefore,
		arg.PayloadAfter,
		arg.ChangedKeys,
	)
	return err
}

const recordZPASyncRunKind = `-- name: RecordZPASyncRunKind :exec
INSERT INTO zpa_sync_run_kind (run_id, kind, status, fetched, error)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (run_id, kind) DO UPDATE
SET status = EXCLUDED.status, fetched = EXCLUDED.fetched, error = EXCLUDED.error
`

type RecordZPASyncRunKindParams struct {
	RunID   uuid.UUID
	Kind    string
	Status  string
	Fetched int32
	Error   *string
}

func (q *Queries) RecordZPASyncRunKind(ctx context.Context, arg RecordZPASyncRunKindParams) error {
	_, err := q.db.Exec(ctx, recordZPASyncRunKind,
		arg.RunID,
		arg.Kind,
		arg.Status,
		arg.Fetched,
		arg.Error,
	)
	return err
}

const retireMissingZPAObjects = `-- name: RetireMissingZPAObjects :many
UPDATE zpa_object
SET gone_at = now()
WHERE kind = $1
  AND gone_at IS NULL
  AND NOT (zpa_id = ANY ($2::bigint[]))
RETURNING id, zpa_id, label, payload
`

type RetireMissingZPAObjectsParams struct {
	Kind    string
	Present []int64
}

type RetireMissingZPAObjectsRow struct {
	ID      uuid.UUID
	ZpaID   int64
	Label   *string
	Payload []byte
}

// Mark everything of one kind that a successful fetch did not mention.
//
// Only ever called after a fetch that succeeded and returned something — the client refuses an
// empty result for exactly this reason. Rows are marked, never deleted.
func (q *Queries) RetireMissingZPAObjects(ctx context.Context, arg RetireMissingZPAObjectsParams) ([]RetireMissingZPAObjectsRow, error) {
	rows, err := q.db.Query(ctx, retireMissingZPAObjects, arg.Kind, arg.Present)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RetireMissingZPAObjectsRow{}
	for rows.Next() {
		var i RetireMissingZPAObjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.ZpaID,
			&i.Label,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startZPASyncRun = `-- name: StartZPASyncRun :one
INSERT INTO zpa_sync_run (trigger, started_by)
VALUES ($1, $2)
RETURNING id, trigger, started_by, started_at, finished_at, status,
          fetched, appeared, changed, disappeared, error
`

type StartZPASyncRunParams struct {
	Trigger   string
	StartedBy uuid.NullUUID
}

// Written before the first fetch, not after the last one. A run that crashes then leaves a
// RUNNING row somebody can see, rather than no row at all — which is indistinguishable from a
// job that was never scheduled, and is how "the import stopped three weeks ago" happens.
func (q *Queries) StartZPASyncRun(ctx context.Context, arg StartZPASyncRunParams) (ZpaSyncRun, error) {
	row := q.db.QueryRow(ctx, startZPASyncRun, arg.Trigger, arg.StartedBy)
	var i ZpaSyncRun
	err := row.Scan(
		&i.ID,
		&i.Trigger,
		&i.StartedBy,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.Fetched,
		&i.Appeared,
		&i.Changed,
		&i.Disappeared,
		&i.Error,
	)
	return i, err
}

const upsertZPAObject = `-- name: UpsertZPAObject :one

INSERT INTO zpa_object (kind, zpa_id, payload, label)
VALUES ($1, $2, $3, $4)
ON CONFLICT (kind, zpa_id) DO UPDATE
SET payload         = EXCLUDED.payload,
    label           = EXCLUDED.label,
    last_seen_at    = now(),
    last_changed_at = CASE
                          WHEN zpa_object.content_hash IS DISTINCT FROM
                               encode(digest(EXCLUDED.payload::text, 'sha256'), 'hex')
                              THEN now()
                          ELSE zpa_object.last_changed_at
                      END,
    -- A returning object is present again. first_seen_at is deliberately untouched: the day we
    -- first saw it is a fact, and overwriting it would lose the only evidence it had ever been
    -- away.
    gone_at         = NULL
RETURNING id, content_hash, first_seen_at, last_changed_at
`

type UpsertZPAObjectParams struct {
	Kind    string
	ZpaID   int64
	Payload []byte
	Label   *string
}

type UpsertZPAObjectRow struct {
	ID            uuid.UUID
	ContentHash   *string
	FirstSeenAt   time.Time
	LastChangedAt time.Time
}

// The cache of the examination office's module master data, its runs and its changes.
//
// The theme of this file is that a sync never deletes and never overwrites blindly. Every
// write says what it expects to find, so that the difference between "unchanged", "changed",
// "new" and "gone" is decided by the database against the row it actually holds, rather than
// by Go against a row it read a moment ago.
// One object, written whole.
//
// What kind of change this was — new, changed, or unchanged — is decided by the caller against
// the hashes ZPAObjectStateByKind already returned, not here. Deciding it in SQL was the first
// attempt and it was worse: it needed a subquery in RETURNING whose visibility rules are
// subtle, to answer a question the caller had already answered for free.
//
// last_changed_at moves only when the content really differs, and that comparison is against
// the generated content_hash — so it is the canonical jsonb form being compared, not whatever
// key order arrived. A sync that changes nothing leaves every timestamp but last_seen_at
// alone, which is what makes "what actually moved, and when" answerable months later.
func (q *Queries) UpsertZPAObject(ctx context.Context, arg UpsertZPAObjectParams) (UpsertZPAObjectRow, error) {
	row := q.db.QueryRow(ctx, upsertZPAObject,
		arg.Kind,
		arg.ZpaID,
		arg.Payload,
		arg.Label,
	)
	var i UpsertZPAObjectRow
	err := row.Scan(
		&i.ID,
		&i.ContentHash,
		&i.FirstSeenAt,
		&i.LastChangedAt,
	)
	return i, err
}

const zPAChangesByRun = `-- name: ZPAChangesByRun :many
SELECT id, run_id, object_id, kind, zpa_id, label, change, changed_keys, detected_at
FROM zpa_change
WHERE run_id = $1
ORDER BY kind, zpa_id
`

type ZPAChangesByRunRow struct {
	ID          uuid.UUID
	RunID       uuid.UUID
	ObjectID    uuid.UUID
	Kind        string
	ZpaID       int64
	Label       *string
	Change      string
	ChangedKeys []string
	DetectedAt  time.Time
}

func (q *Queries) ZPAChangesByRun(ctx context.Context, runID uuid.UUID) ([]ZPAChangesByRunRow, error) {
	rows, err := q.db.Query(ctx, zPAChangesByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ZPAChangesByRunRow{}
	for rows.Next() {
		var i ZPAChangesByRunRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.ObjectID,
			&i.Kind,
			&i.ZpaID,
			&i.Label,
			&i.Change,
			&i.ChangedKeys,
			&i.DetectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const zPAObjectPayload = `-- name: ZPAObjectPayload :one
SELECT id, payload, label
FROM zpa_object
WHERE kind = $1 AND zpa_id = $2
`

type ZPAObjectPayloadParams struct {
	Kind  string
	ZpaID int64
}

type ZPAObjectPayloadRow struct {
	ID      uuid.UUID
	Payload []byte
	Label   *string
}

func (q *Queries) ZPAObjectPayload(ctx context.Context, arg ZPAObjectPayloadParams) (ZPAObjectPayloadRow, error) {
	row := q.db.QueryRow(ctx, zPAObjectPayload, arg.Kind, arg.ZpaID)
	var i ZPAObjectPayloadRow
	err := row.Scan(&i.ID, &i.Payload, &i.Label)
	return i, err
}

const zPAObjectStateByKind = `-- name: ZPAObjectStateByKind :many
SELECT zpa_id, content_hash, (gone_at IS NOT NULL)::boolean AS is_gone
FROM zpa_object
WHERE kind = $1
`

type ZPAObjectStateByKindRow struct {
	ZpaID       int64
	ContentHash *string
	IsGone      bool
}

// What is currently held for one kind: enough to decide the diff without reading the payloads.
//
// The payload itself is fetched only for the objects that turn out to have changed, which
// keeps a nightly run that changes nothing from moving 2.7 MB through the wire for no reason.
func (q *Queries) ZPAObjectStateByKind(ctx context.Context, kind string) ([]ZPAObjectStateByKindRow, error) {
	rows, err := q.db.Query(ctx, zPAObjectStateByKind, kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ZPAObjectStateByKindRow{}
	for rows.Next() {
		var i ZPAObjectStateByKindRow
		if err := rows.Scan(&i.ZpaID, &i.ContentHash, &i.IsGone); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const zPASyncRunByID = `-- name: ZPASyncRunByID :one
SELECT r.id, r.trigger, r.started_by, p.name AS started_by_name, r.started_at,
       r.finished_at, r.status, r.fetched, r.appeared, r.changed, r.disappeared, r.error
FROM zpa_sync_run r
LEFT JOIN person p ON p.id = r.started_by
WHERE r.id = $1
`

type ZPASyncRunByIDRow struct {
	ID            uuid.UUID
	Trigger       string
	StartedBy     uuid.NullUUID
	StartedByName *string
	StartedAt     time.Time
	FinishedAt    pgtype.Timestamptz
	Status        string
	Fetched       int32
	Appeared      int32
	Changed       int32
	Disappeared   int32
	Error         *string
}

func (q *Queries) ZPASyncRunByID(ctx context.Context, id uuid.UUID) (ZPASyncRunByIDRow, error) {
	row := q.db.QueryRow(ctx, zPASyncRunByID, id)
	var i ZPASyncRunByIDRow
	err := row.Scan(
		&i.ID,
		&i.Trigger,
		&i.StartedBy,
		&i.StartedByName,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.Fetched,
		&i.Appeared,
		&i.Changed,
		&i.Disappeared,
		&i.Error,
	)
	return i, err
}

const zPASyncRunKinds = `-- name: ZPASyncRunKinds :many
SELECT run_id, kind, status, fetched, error
FROM zpa_sync_run_kind
WHERE run_id = $1
ORDER BY kind
`

func (q *Queries) ZPASyncRunKinds(ctx context.Context, runID uuid.UUID) ([]ZpaSyncRunKind, error) {
	rows, err := q.db.Query(ctx, zPASyncRunKinds, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ZpaSyncRunKind{}
	for rows.Next() {
		var i ZpaSyncRunKind
		if err := rows.Scan(
			&i.RunID,
			&i.Kind,
			&i.Status,
			&i.Fetched,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const zPASyncRuns = `-- name: ZPASyncRuns :many
SELECT r.id, r.trigger, r.started_by, p.name AS started_by_name, r.started_at,
       r.finished_at, r.status, r.fetched, r.appeared, r.changed, r.disappeared, r.error
FROM zpa_sync_run r
LEFT JOIN person p ON p.id = r.started_by
ORDER BY r.started_at DESC
LIMIT $1
`

type ZPASyncRunsRow struct {
	ID            uuid.UUID
	Trigger       string
	StartedBy     uuid.NullUUID
	StartedByName *string
	StartedAt     time.Time
	FinishedAt    pgtype.Timestamptz
	Status        string
	Fetched       int32
	Appeared      int32
	Changed       int32
	Disappeared   int32
	Error         *string
}

func (q *Queries) ZPASyncRuns(ctx context.Context, limit int32) ([]ZPASyncRunsRow, error) {
	rows, err := q.db.Query(ctx, zPASyncRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ZPASyncRunsRow{}
	for rows.Next() {
		var i ZPASyncRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.Trigger,
			&i.StartedBy,
			&i.StartedByName,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.Fetched,
			&i.Appeared,
			&i.Changed,
			&i.Disappeared,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
