package auth_test

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"time"

	"github.com/obcode/tallox.go/internal/auth"
	"github.com/obcode/tallox.go/internal/policy"
	"github.com/obcode/tallox.go/internal/principal"
	"github.com/obcode/tallox.go/internal/testdata"
)

// The two lookups, in memory.
//
// Hand-written rather than generated by a mock library, as CLAUDE.md asks: the seams are two
// methods wide, and a fake this small is easier to read than the expectations a framework
// would need. These stand in for the *shape* of the answers — that the real queries produce
// the right answers is a question for the integration tests in internal/store, against a real
// PostgreSQL, because that is where those rules actually live.
type fakeUsers struct {
	people map[string]*auth.Person
	err    error
}

func (f fakeUsers) PersonByMail(_ context.Context, mail string) (*auth.Person, error) {
	if f.err != nil {
		return nil, f.err
	}
	return f.people[mail], nil // absent → nil, nil, the "not found" convention
}

type fakeTokens struct {
	tokens map[string]*auth.Token
	err    error
	used   chan string
}

func (f fakeTokens) TokenByID(_ context.Context, id string) (*auth.Token, error) {
	if f.err != nil {
		return nil, f.err
	}
	return f.tokens[id], nil
}

func (f fakeTokens) MarkTokenUsed(_ context.Context, id string) error {
	if f.used != nil {
		f.used <- id
	}
	return nil
}

func person(p testdata.Persona, roles ...policy.Role) *auth.Person {
	out := &auth.Person{ID: p.ID(), Mail: p.Mail, Name: p.Name, Active: true}
	for _, r := range roles {
		out.Roles = append(out.Roles, string(r))
	}
	return out
}

// tokenFor builds a stored token matching the persona's fixture token.
func tokenFor(t *testing.T, p testdata.Persona, owner *auth.Person) *auth.Token {
	t.Helper()

	parsed, err := auth.ParseToken(p.Token)
	if err != nil {
		t.Fatalf("fixture token of %s does not parse: %v", p.Name, err)
	}
	return &auth.Token{
		ID:         parsed.ID,
		SecretHash: auth.HashSecret(parsed.Secret),
		Scopes:     []string{"wishes:read"},
		ExpiresAt:  time.Now().Add(24 * time.Hour),
		Owner:      *owner,
	}
}

func request(header, value string) *http.Request {
	r := httptest.NewRequest(http.MethodPost, "/query", nil)
	if header != "" {
		r.Header.Set(header, value)
	}
	return r
}

// TestProxyDoorResolvesTheHeaderAgainstTheDatabase covers the browser door's happy path, and
// with it the decision that the header carries an identity and nothing else: the name and the
// roles come from the person row, so renaming somebody is one edit rather than a fact that
// depends on which identity provider answered.
func TestProxyDoorResolvesTheHeaderAgainstTheDatabase(t *testing.T) {
	t.Parallel()

	users := fakeUsers{people: map[string]*auth.Person{
		testdata.Vier.Mail: person(testdata.Vier, policy.RoleLecturer, policy.RoleProgrammeLead),
	}}
	a := auth.NewProxyAuthenticator(auth.Config{Mode: auth.ModeProxy, Users: users})

	got, err := a.Authenticate(t.Context(), request(auth.HeaderRemoteUser, testdata.Vier.Mail))
	if err != nil {
		t.Fatalf("authentication failed: %v", err)
	}

	if got.ID != testdata.Vier.ID() || got.Mail != testdata.Vier.Mail {
		t.Errorf("authenticated as %v/%s", got.ID, got.Mail)
	}
	if got.Kind != principal.KindInteractive {
		t.Errorf("kind is %q, want %q", got.Kind, principal.KindInteractive)
	}
	if got.TokenID != "" {
		t.Errorf("a browser session carries token id %q", got.TokenID)
	}
	if !policy.RolesOf(got).Has(policy.RoleProgrammeLead) {
		t.Errorf("roles %v did not survive the lookup", got.Roles)
	}
}

// TestProxyDoorRefusals covers the three ways the browser door says no, and the status each
// one has to produce. The distinction that matters most is the last one: an unreachable
// database is a 503, because a 401 would tell a whole faculty that their session is broken.
func TestProxyDoorRefusals(t *testing.T) {
	t.Parallel()

	inactive := person(testdata.Zwei, policy.RoleLecturer)
	inactive.Active = false

	users := fakeUsers{people: map[string]*auth.Person{
		testdata.Eins.Mail: person(testdata.Eins, policy.RoleLecturer),
		testdata.Zwei.Mail: inactive,
	}}

	for _, tc := range []struct {
		name    string
		users   auth.UserLookup
		mail    string
		want    error
		status  int
		message string
	}{
		{
			name:   "no header at all",
			users:  users,
			mail:   "",
			want:   auth.ErrNoCredential,
			status: http.StatusOK, // handled as anonymous, the request continues
		},
		{
			name:   "somebody this installation does not know",
			users:  users,
			mail:   "neu@example.org",
			want:   auth.ErrUnknownUser,
			status: http.StatusUnauthorized,
		},
		{
			name:   "a deactivated account",
			users:  users,
			mail:   testdata.Zwei.Mail,
			want:   auth.ErrInactiveUser,
			status: http.StatusUnauthorized,
		},
		{
			name:   "the lookup itself fails",
			users:  fakeUsers{err: errors.New("connection refused")},
			mail:   testdata.Eins.Mail,
			want:   auth.ErrUnavailable,
			status: http.StatusServiceUnavailable,
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			a := auth.NewProxyAuthenticator(auth.Config{Mode: auth.ModeProxy, Users: tc.users})

			_, err := a.Authenticate(t.Context(), request(auth.HeaderRemoteUser, tc.mail))
			if !errors.Is(err, tc.want) {
				t.Fatalf("got %v, want %v", err, tc.want)
			}

			// And the same case through the middleware, because the status code is the part
			// the GUI and every script actually react to.
			rec := serve(mounted(a), request(auth.HeaderRemoteUser, tc.mail))
			if rec.Code != tc.status {
				t.Errorf("middleware answered %d, want %d: %s", rec.Code, tc.status, rec.Body)
			}
		})
	}
}

// TestProxyDoorIgnoresBearerTokens: the two doors are separate routes, and each reads only
// its own credential.
//
// If the browser door accepted a bearer token, every rule that is allowed to differ by
// principal.Kind — the @interactiveOnly ones, personnel data, other people's unpublished
// wishes — could be reached from a script by aiming it at the other path.
func TestProxyDoorIgnoresBearerTokens(t *testing.T) {
	t.Parallel()

	users := fakeUsers{people: map[string]*auth.Person{
		testdata.Eins.Mail: person(testdata.Eins, policy.RoleLecturer),
	}}
	a := auth.NewProxyAuthenticator(auth.Config{Mode: auth.ModeProxy, Users: users})

	got, err := a.Authenticate(t.Context(), request("Authorization", "Bearer "+testdata.Eins.Token))
	if !errors.Is(err, auth.ErrNoCredential) {
		t.Errorf("the browser door authenticated a bearer token as %s (err=%v)", got, err)
	}
}

// TestDevModeInjectsAUserButKeepsTheHeaderWorking covers both halves of auth.mode=dev.
//
// Without a header there is a development user, so the GUI is usable without an auth proxy.
// With a header the ordinary lookup applies, which is how a developer checks what a Dozent
// actually sees — and the reason granting the development user every role does not remove the
// ability to test role gating locally.
func TestDevModeInjectsAUserButKeepsTheHeaderWorking(t *testing.T) {
	t.Parallel()

	users := fakeUsers{people: map[string]*auth.Person{
		testdata.Eins.Mail: person(testdata.Eins, policy.RoleLecturer),
	}}
	a := auth.NewProxyAuthenticator(auth.Config{Mode: auth.ModeDev, Users: users})

	dev, err := a.Authenticate(t.Context(), request("", ""))
	if err != nil {
		t.Fatalf("dev mode refused a request with no header: %v", err)
	}
	if !dev.Authenticated() {
		t.Fatal("the development user is not authenticated")
	}
	if dev.ID == (principal.Actor{}).ID {
		t.Error("the development user has the nil UUID — principal.Actor.Owns refuses to " +
			"match it, so nothing would ever be 'theirs'")
	}
	if len(policy.RolesOf(dev)) != len(policy.AllRoles()) {
		t.Errorf("the development user holds %v, want every role", dev.Roles)
	}

	// The header still wins, with the real roles.
	actual, err := a.Authenticate(t.Context(), request(auth.HeaderRemoteUser, testdata.Eins.Mail))
	if err != nil {
		t.Fatalf("dev mode refused a real identity: %v", err)
	}
	if actual.ID != testdata.Eins.ID() {
		t.Errorf("dev mode resolved the header to %v, want %v", actual.ID, testdata.Eins.ID())
	}
	if policy.RolesOf(actual).Has(policy.RoleAdmin) {
		t.Error("dev mode granted ADMIN to a person who does not hold it — testing what a " +
			"colleague sees would then prove nothing")
	}
}

// TestTokenDoorAuthenticatesItsOwner covers the token door's happy path and the invariant
// that hangs off it: roles come from the owner, so a token is never more than its holder.
func TestTokenDoorAuthenticatesItsOwner(t *testing.T) {
	t.Parallel()

	owner := person(testdata.Vier, policy.RoleLecturer, policy.RoleProgrammeLead)
	used := make(chan string, 1)
	tokens := fakeTokens{
		tokens: map[string]*auth.Token{testdata.Vier.TokenID: tokenFor(t, testdata.Vier, owner)},
		used:   used,
	}

	a := auth.NewTokenAuthenticator(auth.Config{Mode: auth.ModeProxy, Tokens: tokens})
	got, err := a.Authenticate(t.Context(), request("Authorization", "Bearer "+testdata.Vier.Token))
	if err != nil {
		t.Fatalf("authentication failed: %v", err)
	}
	t.Cleanup(a.Wait)

	if got.ID != testdata.Vier.ID() {
		t.Errorf("authenticated as %v, want %v", got.ID, testdata.Vier.ID())
	}
	if got.Kind != principal.KindToken {
		t.Errorf("kind is %q, want %q", got.Kind, principal.KindToken)
	}
	if got.TokenID != testdata.Vier.TokenID {
		t.Errorf("token id is %q, want %q", got.TokenID, testdata.Vier.TokenID)
	}
	if len(got.Scopes) != 1 || got.Scopes[0] != "wishes:read" {
		t.Errorf("scopes are %v", got.Scopes)
	}
	if !policy.RolesOf(got).Has(policy.RoleProgrammeLead) {
		t.Errorf("the owner's roles did not reach the actor: %v", got.Roles)
	}

	// Use is recorded off the request path; the authenticator only promises that it happens.
	select {
	case id := <-used:
		if id != testdata.Vier.TokenID {
			t.Errorf("recorded use of %q", id)
		}
	case <-time.After(2 * time.Second):
		t.Error("the token's use was never recorded")
	}
}

// TestTokenDoorRefusals is the table that matters most on this door: every way a token can
// fail, and what the caller is told.
//
// The pairing is deliberate. An unknown id and a wrong secret produce the *same* refusal,
// because the difference is exactly what somebody without a token would like to learn. Expiry
// and revocation are specific, because only somebody holding the secret gets that far, and
// they own the token.
func TestTokenDoorRefusals(t *testing.T) {
	t.Parallel()

	owner := person(testdata.Eins, policy.RoleLecturer)

	expired := tokenFor(t, testdata.Eins, owner)
	expired.ExpiresAt = time.Now().Add(-time.Minute)

	revoked := tokenFor(t, testdata.Eins, owner)
	revoked.RevokedAt = time.Now().Add(-time.Hour)

	inactiveOwner := person(testdata.Eins, policy.RoleLecturer)
	inactiveOwner.Active = false
	leaver := tokenFor(t, testdata.Eins, inactiveOwner)

	wrongSecret := tokenFor(t, testdata.Eins, owner)
	wrongSecret.SecretHash = auth.HashSecret("something else entirely")

	for _, tc := range []struct {
		name       string
		tokens     auth.TokenLookup
		header     string
		want       error
		status     int
		wantInBody string
	}{
		{
			name:   "no Authorization header",
			tokens: fakeTokens{},
			header: "",
			want:   auth.ErrNoCredential,
			status: http.StatusOK,
		},
		{
			name:   "not a Bearer credential",
			tokens: fakeTokens{},
			header: "Basic " + testdata.Eins.Token,
			want:   auth.ErrMalformedToken,
			status: http.StatusUnauthorized,
		},
		{
			name:   "not a Tallox token",
			tokens: fakeTokens{},
			header: "Bearer eyJhbGciOiJIUzI1NiJ9.e30.c2ln",
			want:   auth.ErrMalformedToken,
			status: http.StatusUnauthorized,
		},
		{
			name:   "no such token",
			tokens: fakeTokens{tokens: map[string]*auth.Token{}},
			header: "Bearer " + testdata.Eins.Token,
			want:   auth.ErrInvalidToken,
			status: http.StatusUnauthorized,
		},
		{
			name:   "wrong secret",
			tokens: fakeTokens{tokens: map[string]*auth.Token{testdata.Eins.TokenID: wrongSecret}},
			header: "Bearer " + testdata.Eins.Token,
			want:   auth.ErrInvalidToken,
			status: http.StatusUnauthorized,
		},
		{
			name:       "expired",
			tokens:     fakeTokens{tokens: map[string]*auth.Token{testdata.Eins.TokenID: expired}},
			header:     "Bearer " + testdata.Eins.Token,
			want:       auth.ErrExpiredToken,
			status:     http.StatusUnauthorized,
			wantInBody: "abgelaufen",
		},
		{
			name:       "revoked",
			tokens:     fakeTokens{tokens: map[string]*auth.Token{testdata.Eins.TokenID: revoked}},
			header:     "Bearer " + testdata.Eins.Token,
			want:       auth.ErrRevokedToken,
			status:     http.StatusUnauthorized,
			wantInBody: "widerrufen",
		},
		{
			name:   "owner has left",
			tokens: fakeTokens{tokens: map[string]*auth.Token{testdata.Eins.TokenID: leaver}},
			header: "Bearer " + testdata.Eins.Token,
			want:   auth.ErrInactiveUser,
			status: http.StatusUnauthorized,
		},
		{
			name:   "the lookup itself fails",
			tokens: fakeTokens{err: errors.New("connection refused")},
			header: "Bearer " + testdata.Eins.Token,
			want:   auth.ErrUnavailable,
			status: http.StatusServiceUnavailable,
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			a := auth.NewTokenAuthenticator(auth.Config{Mode: auth.ModeProxy, Tokens: tc.tokens})
			t.Cleanup(a.Wait)

			req := request("", "")
			if tc.header != "" {
				req = request("Authorization", tc.header)
			}

			if _, err := a.Authenticate(t.Context(), req); !errors.Is(err, tc.want) {
				t.Fatalf("got %v, want %v", err, tc.want)
			}

			rec := serve(mounted(a), req)
			if rec.Code != tc.status {
				t.Errorf("middleware answered %d, want %d: %s", rec.Code, tc.status, rec.Body)
			}
			if tc.wantInBody != "" && !strings.Contains(rec.Body.String(), tc.wantInBody) {
				t.Errorf("the message does not say %q, so the owner cannot tell why their "+
					"token stopped working: %s", tc.wantInBody, rec.Body)
			}
		})
	}
}

// TestRefusalsNeverNameSomebodyElse: the messages a caller reads are a leak channel of their
// own. A refusal that named the owner of a token, or listed who does have an account, would
// hand out exactly the information the confidentiality rule withholds.
func TestRefusalsNeverNameSomebodyElse(t *testing.T) {
	t.Parallel()

	tokens := fakeTokens{tokens: map[string]*auth.Token{
		testdata.Eins.TokenID: tokenFor(t, testdata.Eins, person(testdata.Eins, policy.RoleLecturer)),
	}}
	a := auth.NewTokenAuthenticator(auth.Config{Mode: auth.ModeProxy, Tokens: tokens})
	t.Cleanup(a.Wait)

	// Right id, wrong secret: the one case where the server knows whose token it is.
	forged := "tallox_" + testdata.Eins.TokenID + "_" +
		"exampleXforgedXsecretX0000000000000000000000"[:43]

	rec := serve(mounted(a), request("Authorization", "Bearer "+forged))
	body := rec.Body.String()

	for _, forbidden := range append(testdata.Mails(testdata.All()), "prof.eins") {
		if strings.Contains(body, forbidden) {
			t.Errorf("the refusal names %q: %s", forbidden, body)
		}
	}
}

// TestAnonymousRequestsReachTheHandler pins the exception the whole design leans on.
//
// buildInfo answers without a session — the GUI footer renders on the login page, and a smoke
// test that fails on authorization cannot tell a broken proxy from a broken server. So a
// request with no credential must arrive at the handler carrying the anonymous actor, on both
// doors, rather than being turned away by the middleware.
func TestAnonymousRequestsReachTheHandler(t *testing.T) {
	t.Parallel()

	for _, tc := range []struct {
		name string
		auth auth.Authenticator
	}{
		{"browser", auth.NewProxyAuthenticator(auth.Config{Mode: auth.ModeProxy, Users: fakeUsers{}})},
		{"token", auth.NewTokenAuthenticator(auth.Config{Mode: auth.ModeProxy, Tokens: fakeTokens{}})},
	} {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			var seen principal.Actor
			var ran bool
			handler := auth.Middleware(tc.auth, nil)(http.HandlerFunc(
				func(_ http.ResponseWriter, r *http.Request) {
					ran = true
					// Lookup rather than From: the middleware has to have put something in,
					// so that a handler can tell "nobody is logged in" from "this route is
					// not authenticated at all".
					var ok bool
					seen, ok = principal.Lookup(r.Context())
					if !ok {
						t.Error("the middleware ran but put no actor in the context")
					}
				}))

			rec := serve(handler, request("", ""))

			if !ran {
				t.Fatalf("the handler was never reached: %d %s", rec.Code, rec.Body)
			}
			if seen.Authenticated() {
				t.Errorf("an anonymous request arrived as %s", seen)
			}
		})
	}
}

// TestRefusalsAreGraphQLShaped: both doors serve GraphQL, so a refusal has to look like a
// GraphQL error. Plain text would surface in the GUI as a JSON parse error and in a script as
// something that says nothing about logging in.
func TestRefusalsAreGraphQLShaped(t *testing.T) {
	t.Parallel()

	a := auth.NewTokenAuthenticator(auth.Config{Mode: auth.ModeProxy, Tokens: fakeTokens{}})
	t.Cleanup(a.Wait)

	rec := serve(mounted(a), request("Authorization", "Bearer "+testdata.Eins.Token))

	if ct := rec.Header().Get("Content-Type"); ct != "application/json" {
		t.Errorf("Content-Type is %q", ct)
	}
	if challenge := rec.Header().Get("WWW-Authenticate"); challenge == "" {
		t.Error("a 401 without WWW-Authenticate")
	}

	var body struct {
		Data   any `json:"data"`
		Errors []struct {
			Message    string         `json:"message"`
			Extensions map[string]any `json:"extensions"`
		} `json:"errors"`
	}
	if err := json.Unmarshal(rec.Body.Bytes(), &body); err != nil {
		t.Fatalf("the refusal is not JSON: %v\n%s", err, rec.Body)
	}
	if len(body.Errors) != 1 {
		t.Fatalf("expected exactly one error: %s", rec.Body)
	}
	if body.Errors[0].Message == "" {
		t.Error("the error carries no message")
	}
	if code := fmt.Sprint(body.Errors[0].Extensions["code"]); code != "UNAUTHENTICATED" {
		t.Errorf("extensions.code is %q, want UNAUTHENTICATED — that is what a client "+
			"switches on to decide whether to send the user to the login page", code)
	}
}

// TestParseMode covers the configuration value that decides whether the machine door exists
// at all. A typo has to stop the server, not silently select a default.
func TestParseMode(t *testing.T) {
	t.Parallel()

	for _, valid := range []auth.Mode{auth.ModeDev, auth.ModeProxy, auth.ModeOffToken} {
		got, err := auth.ParseMode(string(valid))
		if err != nil || got != valid {
			t.Errorf("ParseMode(%q) = %q, %v", valid, got, err)
		}
	}
	for _, invalid := range []string{"", "Dev", "production", "off", "off_token", "true"} {
		if _, err := auth.ParseMode(invalid); err == nil {
			t.Errorf("ParseMode(%q) was accepted", invalid)
		}
	}

	if !auth.ModeProxy.TokenDoorEnabled() || !auth.ModeDev.TokenDoorEnabled() {
		t.Error("the token door is off outside off-token mode")
	}
	if auth.ModeOffToken.TokenDoorEnabled() {
		t.Error("off-token still mounts the token door — the emergency stop does nothing")
	}
}

// mounted wraps an authenticator in the middleware, behind a handler that simply answers 200.
//
// The trivial handler is the assertion: reaching it at all means the middleware let the
// request through, so "200" reads as "not refused" in every table above.
func mounted(a auth.Authenticator) http.Handler {
	return auth.Middleware(a, nil)(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusOK)
	}))
}

func serve(h http.Handler, r *http.Request) *httptest.ResponseRecorder {
	rec := httptest.NewRecorder()
	h.ServeHTTP(rec, r)
	return rec
}
